package et.po;



/**
 * AddresslistsortInfo generated by MyEclipse - Hibernate Tools
 */

public class AddresslistsortInfo  implements java.io.Serializable {


    // Fields    

     private String id;
     private SysUser sysUser;
     private String sortExplain;
     private String sortName;
     private String sortMark;


    // Constructors

    /** default constructor */
    public AddresslistsortInfo() {
    }

	/** minimal constructor */
    public AddresslistsortInfo(String id, SysUser sysUser, String sortName) {
        this.id = id;
        this.sysUser = sysUser;
        this.sortName = sortName;
    }
    
    /** full constructor */
    public AddresslistsortInfo(String id, SysUser sysUser, String sortExplain, String sortName, String sortMark) {
        this.id = id;
        this.sysUser = sysUser;
        this.sortExplain = sortExplain;
        this.sortName = sortName;
        this.sortMark = sortMark;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public SysUser getSysUser() {
        return this.sysUser;
    }
    
    public void setSysUser(SysUser sysUser) {
        this.sysUser = sysUser;
    }

    public String getSortExplain() {
        return this.sortExplain;
    }
    
    public void setSortExplain(String sortExplain) {
        this.sortExplain = sortExplain;
    }

    public String getSortName() {
        return this.sortName;
    }
    
    public void setSortName(String sortName) {
        this.sortName = sortName;
    }

    public String getSortMark() {
        return this.sortMark;
    }
    
    public void setSortMark(String sortMark) {
        this.sortMark = sortMark;
    }
   








}