package et.po;



/**
 * AssetsInfo generated by MyEclipse - Hibernate Tools
 */

public class AssetsInfo  implements java.io.Serializable {


    // Fields    

     private String assetsId;
     private AssetsOper assetsOper;
     private String assetsName;
     private Integer assetsNum;
     private String assetsWithfor;
     private String assetsType;
     private String remark;


    // Constructors

    /** default constructor */
    public AssetsInfo() {
    }

	/** minimal constructor */
    public AssetsInfo(String assetsId) {
        this.assetsId = assetsId;
    }
    
    /** full constructor */
    public AssetsInfo(String assetsId, AssetsOper assetsOper, String assetsName, Integer assetsNum, String assetsWithfor, String assetsType, String remark) {
        this.assetsId = assetsId;
        this.assetsOper = assetsOper;
        this.assetsName = assetsName;
        this.assetsNum = assetsNum;
        this.assetsWithfor = assetsWithfor;
        this.assetsType = assetsType;
        this.remark = remark;
    }

   
    // Property accessors

    public String getAssetsId() {
        return this.assetsId;
    }
    
    public void setAssetsId(String assetsId) {
        this.assetsId = assetsId;
    }

    public AssetsOper getAssetsOper() {
        return this.assetsOper;
    }
    
    public void setAssetsOper(AssetsOper assetsOper) {
        this.assetsOper = assetsOper;
    }

    public String getAssetsName() {
        return this.assetsName;
    }
    
    public void setAssetsName(String assetsName) {
        this.assetsName = assetsName;
    }

    public Integer getAssetsNum() {
        return this.assetsNum;
    }
    
    public void setAssetsNum(Integer assetsNum) {
        this.assetsNum = assetsNum;
    }

    public String getAssetsWithfor() {
        return this.assetsWithfor;
    }
    
    public void setAssetsWithfor(String assetsWithfor) {
        this.assetsWithfor = assetsWithfor;
    }

    public String getAssetsType() {
        return this.assetsType;
    }
    
    public void setAssetsType(String assetsType) {
        this.assetsType = assetsType;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
   








}