package et.po;



/**
 * CheckworkTime generated by MyEclipse - Hibernate Tools
 */

public class CheckworkTime  implements java.io.Serializable {


    // Fields    

     private CheckworkTimeId id;


    // Constructors

    /** default constructor */
    public CheckworkTime() {
    }

    
    /** full constructor */
    public CheckworkTime(CheckworkTimeId id) {
        this.id = id;
    }

   
    // Property accessors

    public CheckworkTimeId getId() {
        return this.id;
    }
    
    public void setId(CheckworkTimeId id) {
        this.id = id;
    }
   








}