package et.po;

import java.util.Date;


/**
 * CheckworkAbsence generated by MyEclipse - Hibernate Tools
 */

public class CheckworkAbsence  implements java.io.Serializable {


    // Fields    

     private String id;
     private String userId;
     private String employeeId;
     private String employeeDepart;
     private String absenceType;
     private Date absenceDate;
     private String absenceTime;
     private String absenceReason;
     private Date beginTime;
     private String STime;
     private Date endTime;
     private String ETime;
     private String absenceState;
     private String remark;
     private Date signDate;


    // Constructors

    /** default constructor */
    public CheckworkAbsence() {
    }

	/** minimal constructor */
    public CheckworkAbsence(String id, String userId) {
        this.id = id;
        this.userId = userId;
    }
    
    /** full constructor */
    public CheckworkAbsence(String id, String userId, String employeeId, String employeeDepart, String absenceType, Date absenceDate, String absenceTime, String absenceReason, Date beginTime, String STime, Date endTime, String ETime, String absenceState, String remark, Date signDate) {
        this.id = id;
        this.userId = userId;
        this.employeeId = employeeId;
        this.employeeDepart = employeeDepart;
        this.absenceType = absenceType;
        this.absenceDate = absenceDate;
        this.absenceTime = absenceTime;
        this.absenceReason = absenceReason;
        this.beginTime = beginTime;
        this.STime = STime;
        this.endTime = endTime;
        this.ETime = ETime;
        this.absenceState = absenceState;
        this.remark = remark;
        this.signDate = signDate;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

    public String getEmployeeDepart() {
        return this.employeeDepart;
    }
    
    public void setEmployeeDepart(String employeeDepart) {
        this.employeeDepart = employeeDepart;
    }

    public String getAbsenceType() {
        return this.absenceType;
    }
    
    public void setAbsenceType(String absenceType) {
        this.absenceType = absenceType;
    }

    public Date getAbsenceDate() {
        return this.absenceDate;
    }
    
    public void setAbsenceDate(Date absenceDate) {
        this.absenceDate = absenceDate;
    }

    public String getAbsenceTime() {
        return this.absenceTime;
    }
    
    public void setAbsenceTime(String absenceTime) {
        this.absenceTime = absenceTime;
    }

    public String getAbsenceReason() {
        return this.absenceReason;
    }
    
    public void setAbsenceReason(String absenceReason) {
        this.absenceReason = absenceReason;
    }

    public Date getBeginTime() {
        return this.beginTime;
    }
    
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    public String getSTime() {
        return this.STime;
    }
    
    public void setSTime(String STime) {
        this.STime = STime;
    }

    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public String getETime() {
        return this.ETime;
    }
    
    public void setETime(String ETime) {
        this.ETime = ETime;
    }

    public String getAbsenceState() {
        return this.absenceState;
    }
    
    public void setAbsenceState(String absenceState) {
        this.absenceState = absenceState;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Date getSignDate() {
        return this.signDate;
    }
    
    public void setSignDate(Date signDate) {
        this.signDate = signDate;
    }
   








}