package et.po;



/**
 * GovAntithesesInfo generated by MyEclipse - Hibernate Tools
 */

public class GovAntithesesInfo  implements java.io.Serializable {


    // Fields    

     private String id;
     private String driverId;
     private String motorId;
     private String remark;


    // Constructors

    /** default constructor */
    public GovAntithesesInfo() {
    }

	/** minimal constructor */
    public GovAntithesesInfo(String id, String driverId, String motorId) {
        this.id = id;
        this.driverId = driverId;
        this.motorId = motorId;
    }
    
    /** full constructor */
    public GovAntithesesInfo(String id, String driverId, String motorId, String remark) {
        this.id = id;
        this.driverId = driverId;
        this.motorId = motorId;
        this.remark = remark;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getDriverId() {
        return this.driverId;
    }
    
    public void setDriverId(String driverId) {
        this.driverId = driverId;
    }

    public String getMotorId() {
        return this.motorId;
    }
    
    public void setMotorId(String motorId) {
        this.motorId = motorId;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
   








}