package et.po;

import java.util.Date;


/**
 * PlanDetail generated by MyEclipse - Hibernate Tools
 */

public class PlanDetail  implements java.io.Serializable {


    // Fields    

     private String id;
     private PlanInfo planInfo;
     private Date beginTime;
     private Date endTime;
     private String planInfo_1;
     private String carryState;
     private String carryUser;
     private String carryInfo;
     private String planSign;
     private String remark;


    // Constructors

    /** default constructor */
    public PlanDetail() {
    }

	/** minimal constructor */
    public PlanDetail(String id, PlanInfo planInfo) {
        this.id = id;
        this.planInfo = planInfo;
    }
    
    /** full constructor */
    public PlanDetail(String id, PlanInfo planInfo, Date beginTime, Date endTime, String planInfo_1, String carryState, String carryUser, String carryInfo, String planSign, String remark) {
        this.id = id;
        this.planInfo = planInfo;
        this.beginTime = beginTime;
        this.endTime = endTime;
        this.planInfo_1 = planInfo_1;
        this.carryState = carryState;
        this.carryUser = carryUser;
        this.carryInfo = carryInfo;
        this.planSign = planSign;
        this.remark = remark;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public PlanInfo getPlanInfo() {
        return this.planInfo;
    }
    
    public void setPlanInfo(PlanInfo planInfo) {
        this.planInfo = planInfo;
    }

    public Date getBeginTime() {
        return this.beginTime;
    }
    
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public String getPlanInfo_1() {
        return this.planInfo_1;
    }
    
    public void setPlanInfo_1(String planInfo_1) {
        this.planInfo_1 = planInfo_1;
    }

    public String getCarryState() {
        return this.carryState;
    }
    
    public void setCarryState(String carryState) {
        this.carryState = carryState;
    }

    public String getCarryUser() {
        return this.carryUser;
    }
    
    public void setCarryUser(String carryUser) {
        this.carryUser = carryUser;
    }

    public String getCarryInfo() {
        return this.carryInfo;
    }
    
    public void setCarryInfo(String carryInfo) {
        this.carryInfo = carryInfo;
    }

    public String getPlanSign() {
        return this.planSign;
    }
    
    public void setPlanSign(String planSign) {
        this.planSign = planSign;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
   








}