package et.po;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * PlanInfo generated by MyEclipse - Hibernate Tools
 */

public class PlanInfo  implements java.io.Serializable {


    // Fields    

     private String id;
     private String employeeId;
     private String planType;
     private String planTitle;
     private String flowId;
     private Date planDate;
     private String remark;
     private Date beginDate;
     private Date endDate;
     private String approveMan;
     private Date approveTime;
     private Set planDetails = new HashSet(0);


    // Constructors

    /** default constructor */
    public PlanInfo() {
    }

	/** minimal constructor */
    public PlanInfo(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public PlanInfo(String id, String employeeId, String planType, String planTitle, String flowId, Date planDate, String remark, Date beginDate, Date endDate, String approveMan, Date approveTime, Set planDetails) {
        this.id = id;
        this.employeeId = employeeId;
        this.planType = planType;
        this.planTitle = planTitle;
        this.flowId = flowId;
        this.planDate = planDate;
        this.remark = remark;
        this.beginDate = beginDate;
        this.endDate = endDate;
        this.approveMan = approveMan;
        this.approveTime = approveTime;
        this.planDetails = planDetails;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

    public String getPlanType() {
        return this.planType;
    }
    
    public void setPlanType(String planType) {
        this.planType = planType;
    }

    public String getPlanTitle() {
        return this.planTitle;
    }
    
    public void setPlanTitle(String planTitle) {
        this.planTitle = planTitle;
    }

    public String getFlowId() {
        return this.flowId;
    }
    
    public void setFlowId(String flowId) {
        this.flowId = flowId;
    }

    public Date getPlanDate() {
        return this.planDate;
    }
    
    public void setPlanDate(Date planDate) {
        this.planDate = planDate;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public String getApproveMan() {
        return this.approveMan;
    }
    
    public void setApproveMan(String approveMan) {
        this.approveMan = approveMan;
    }

    public Date getApproveTime() {
        return this.approveTime;
    }
    
    public void setApproveTime(Date approveTime) {
        this.approveTime = approveTime;
    }

    public Set getPlanDetails() {
        return this.planDetails;
    }
    
    public void setPlanDetails(Set planDetails) {
        this.planDetails = planDetails;
    }
   








}