package et.po;



/**
 * WorkflowInstance generated by MyEclipse - Hibernate Tools
 */

public class WorkflowInstance  implements java.io.Serializable {


    // Fields    

     private String id;
     private WorkflowDefine workflowDefine;
     private String instanceId;


    // Constructors

    /** default constructor */
    public WorkflowInstance() {
    }

	/** minimal constructor */
    public WorkflowInstance(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public WorkflowInstance(String id, WorkflowDefine workflowDefine, String instanceId) {
        this.id = id;
        this.workflowDefine = workflowDefine;
        this.instanceId = instanceId;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public WorkflowDefine getWorkflowDefine() {
        return this.workflowDefine;
    }
    
    public void setWorkflowDefine(WorkflowDefine workflowDefine) {
        this.workflowDefine = workflowDefine;
    }

    public String getInstanceId() {
        return this.instanceId;
    }
    
    public void setInstanceId(String instanceId) {
        this.instanceId = instanceId;
    }
   








}