package et.po;

import java.util.Date;


/**
 * WorkPlanMission generated by MyEclipse - Hibernate Tools
 */

public class WorkPlanMission  implements java.io.Serializable {


    // Fields    

     private String id;
     private WorkPlanInfo workPlanInfoByPlanId;
     private WorkPlanInfo workPlanInfoByCreatePlanId;
     private String name;
     private Date createTime;
     private String keyword;
     private String missionType;
     private String missionClasses;
     private Date beginTime;
     private Date endTime;
     private String missionPri;
     private String missionPriType;
     private String missionInfo;
     private String missionSign;
     private String missionComplete;
     private Date completeTime;
     private String remark;
     private String checkId;
     private String createUser;
     private String planmissionSignDel;


    // Constructors

    /** default constructor */
    public WorkPlanMission() {
    }

	/** minimal constructor */
    public WorkPlanMission(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public WorkPlanMission(String id, WorkPlanInfo workPlanInfoByPlanId, WorkPlanInfo workPlanInfoByCreatePlanId, String name, Date createTime, String keyword, String missionType, String missionClasses, Date beginTime, Date endTime, String missionPri, String missionPriType, String missionInfo, String missionSign, String missionComplete, Date completeTime, String remark, String checkId, String createUser, String planmissionSignDel) {
        this.id = id;
        this.workPlanInfoByPlanId = workPlanInfoByPlanId;
        this.workPlanInfoByCreatePlanId = workPlanInfoByCreatePlanId;
        this.name = name;
        this.createTime = createTime;
        this.keyword = keyword;
        this.missionType = missionType;
        this.missionClasses = missionClasses;
        this.beginTime = beginTime;
        this.endTime = endTime;
        this.missionPri = missionPri;
        this.missionPriType = missionPriType;
        this.missionInfo = missionInfo;
        this.missionSign = missionSign;
        this.missionComplete = missionComplete;
        this.completeTime = completeTime;
        this.remark = remark;
        this.checkId = checkId;
        this.createUser = createUser;
        this.planmissionSignDel = planmissionSignDel;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public WorkPlanInfo getWorkPlanInfoByPlanId() {
        return this.workPlanInfoByPlanId;
    }
    
    public void setWorkPlanInfoByPlanId(WorkPlanInfo workPlanInfoByPlanId) {
        this.workPlanInfoByPlanId = workPlanInfoByPlanId;
    }

    public WorkPlanInfo getWorkPlanInfoByCreatePlanId() {
        return this.workPlanInfoByCreatePlanId;
    }
    
    public void setWorkPlanInfoByCreatePlanId(WorkPlanInfo workPlanInfoByCreatePlanId) {
        this.workPlanInfoByCreatePlanId = workPlanInfoByCreatePlanId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getKeyword() {
        return this.keyword;
    }
    
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public String getMissionType() {
        return this.missionType;
    }
    
    public void setMissionType(String missionType) {
        this.missionType = missionType;
    }

    public String getMissionClasses() {
        return this.missionClasses;
    }
    
    public void setMissionClasses(String missionClasses) {
        this.missionClasses = missionClasses;
    }

    public Date getBeginTime() {
        return this.beginTime;
    }
    
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public String getMissionPri() {
        return this.missionPri;
    }
    
    public void setMissionPri(String missionPri) {
        this.missionPri = missionPri;
    }

    public String getMissionPriType() {
        return this.missionPriType;
    }
    
    public void setMissionPriType(String missionPriType) {
        this.missionPriType = missionPriType;
    }

    public String getMissionInfo() {
        return this.missionInfo;
    }
    
    public void setMissionInfo(String missionInfo) {
        this.missionInfo = missionInfo;
    }

    public String getMissionSign() {
        return this.missionSign;
    }
    
    public void setMissionSign(String missionSign) {
        this.missionSign = missionSign;
    }

    public String getMissionComplete() {
        return this.missionComplete;
    }
    
    public void setMissionComplete(String missionComplete) {
        this.missionComplete = missionComplete;
    }

    public Date getCompleteTime() {
        return this.completeTime;
    }
    
    public void setCompleteTime(Date completeTime) {
        this.completeTime = completeTime;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getCheckId() {
        return this.checkId;
    }
    
    public void setCheckId(String checkId) {
        this.checkId = checkId;
    }

    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    public String getPlanmissionSignDel() {
        return this.planmissionSignDel;
    }
    
    public void setPlanmissionSignDel(String planmissionSignDel) {
        this.planmissionSignDel = planmissionSignDel;
    }
   








}