package et.po;

import java.util.Date;


/**
 * WorkNewPlan generated by MyEclipse - Hibernate Tools
 */

public class WorkNewPlan  implements java.io.Serializable {


    // Fields    

     private String id;
     private WorkParentPlan workParentPlan;
     private String planType;
     private String planTitle;
     private String planCreateUser;
     private String planOperUser;
     private Date createDate;
     private Date beginDate;
     private Date endDate;
     private String planInfo;
     private String planComplete;
     private String planSign;
     private Date complete;
     private String remark;


    // Constructors

    /** default constructor */
    public WorkNewPlan() {
    }

	/** minimal constructor */
    public WorkNewPlan(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public WorkNewPlan(String id, WorkParentPlan workParentPlan, String planType, String planTitle, String planCreateUser, String planOperUser, Date createDate, Date beginDate, Date endDate, String planInfo, String planComplete, String planSign, Date complete, String remark) {
        this.id = id;
        this.workParentPlan = workParentPlan;
        this.planType = planType;
        this.planTitle = planTitle;
        this.planCreateUser = planCreateUser;
        this.planOperUser = planOperUser;
        this.createDate = createDate;
        this.beginDate = beginDate;
        this.endDate = endDate;
        this.planInfo = planInfo;
        this.planComplete = planComplete;
        this.planSign = planSign;
        this.complete = complete;
        this.remark = remark;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public WorkParentPlan getWorkParentPlan() {
        return this.workParentPlan;
    }
    
    public void setWorkParentPlan(WorkParentPlan workParentPlan) {
        this.workParentPlan = workParentPlan;
    }

    public String getPlanType() {
        return this.planType;
    }
    
    public void setPlanType(String planType) {
        this.planType = planType;
    }

    public String getPlanTitle() {
        return this.planTitle;
    }
    
    public void setPlanTitle(String planTitle) {
        this.planTitle = planTitle;
    }

    public String getPlanCreateUser() {
        return this.planCreateUser;
    }
    
    public void setPlanCreateUser(String planCreateUser) {
        this.planCreateUser = planCreateUser;
    }

    public String getPlanOperUser() {
        return this.planOperUser;
    }
    
    public void setPlanOperUser(String planOperUser) {
        this.planOperUser = planOperUser;
    }

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public String getPlanInfo() {
        return this.planInfo;
    }
    
    public void setPlanInfo(String planInfo) {
        this.planInfo = planInfo;
    }

    public String getPlanComplete() {
        return this.planComplete;
    }
    
    public void setPlanComplete(String planComplete) {
        this.planComplete = planComplete;
    }

    public String getPlanSign() {
        return this.planSign;
    }
    
    public void setPlanSign(String planSign) {
        this.planSign = planSign;
    }

    public Date getComplete() {
        return this.complete;
    }
    
    public void setComplete(Date complete) {
        this.complete = complete;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
   








}