package et.po;



/**
 * CallinState generated by MyEclipse - Hibernate Tools
 */

public class CallinState  implements java.io.Serializable {


    // Fields    

     private String id;
     private String port;
     private String ip;


    // Constructors

    /** default constructor */
    public CallinState() {
    }

	/** minimal constructor */
    public CallinState(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public CallinState(String id, String port, String ip) {
        this.id = id;
        this.port = port;
        this.ip = ip;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getPort() {
        return this.port;
    }
    
    public void setPort(String port) {
        this.port = port;
    }

    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
   








}