package et.po;

import java.util.Date;


/**
 * OperatorWorkInfo generated by MyEclipse - Hibernate Tools
 */

public class OperatorWorkInfo  implements java.io.Serializable {


    // Fields    

     private String id;
     private String operator;
     private Date operateDate;
     private Date operateTime;
     private String operatorState;


    // Constructors

    /** default constructor */
    public OperatorWorkInfo() {
    }

	/** minimal constructor */
    public OperatorWorkInfo(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public OperatorWorkInfo(String id, String operator, Date operateDate, Date operateTime, String operatorState) {
        this.id = id;
        this.operator = operator;
        this.operateDate = operateDate;
        this.operateTime = operateTime;
        this.operatorState = operatorState;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getOperator() {
        return this.operator;
    }
    
    public void setOperator(String operator) {
        this.operator = operator;
    }

    public Date getOperateDate() {
        return this.operateDate;
    }
    
    public void setOperateDate(Date operateDate) {
        this.operateDate = operateDate;
    }

    public Date getOperateTime() {
        return this.operateTime;
    }
    
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    public String getOperatorState() {
        return this.operatorState;
    }
    
    public void setOperatorState(String operatorState) {
        this.operatorState = operatorState;
    }
   








}