package et.po;



/**
 * Pbcattbl generated by MyEclipse - Hibernate Tools
 */

public class Pbcattbl  implements java.io.Serializable {


    // Fields    

     private PbcattblId id;


    // Constructors

    /** default constructor */
    public Pbcattbl() {
    }

    
    /** full constructor */
    public Pbcattbl(PbcattblId id) {
        this.id = id;
    }

   
    // Property accessors

    public PbcattblId getId() {
        return this.id;
    }
    
    public void setId(PbcattblId id) {
        this.id = id;
    }
   








}