package et.po;



/**
 * Pbcatfmt generated by MyEclipse - Hibernate Tools
 */

public class Pbcatfmt  implements java.io.Serializable {


    // Fields    

     private PbcatfmtId id;


    // Constructors

    /** default constructor */
    public Pbcatfmt() {
    }

    
    /** full constructor */
    public Pbcatfmt(PbcatfmtId id) {
        this.id = id;
    }

   
    // Property accessors

    public PbcatfmtId getId() {
        return this.id;
    }
    
    public void setId(PbcatfmtId id) {
        this.id = id;
    }
   








}