package et.po;



/**
 * PoliceCallinInfo generated by MyEclipse - Hibernate Tools
 */

public class PoliceCallinInfo  implements java.io.Serializable {


    // Fields    

     private String id;
     private PoliceCallin policeCallin;
     private String tagInfo;
     private String quInfo;
     private String content;
     private String remark;


    // Constructors

    /** default constructor */
    public PoliceCallinInfo() {
    }

	/** minimal constructor */
    public PoliceCallinInfo(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public PoliceCallinInfo(String id, PoliceCallin policeCallin, String tagInfo, String quInfo, String content, String remark) {
        this.id = id;
        this.policeCallin = policeCallin;
        this.tagInfo = tagInfo;
        this.quInfo = quInfo;
        this.content = content;
        this.remark = remark;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public PoliceCallin getPoliceCallin() {
        return this.policeCallin;
    }
    
    public void setPoliceCallin(PoliceCallin policeCallin) {
        this.policeCallin = policeCallin;
    }

    public String getTagInfo() {
        return this.tagInfo;
    }
    
    public void setTagInfo(String tagInfo) {
        this.tagInfo = tagInfo;
    }

    public String getQuInfo() {
        return this.quInfo;
    }
    
    public void setQuInfo(String quInfo) {
        this.quInfo = quInfo;
    }

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
   








}