package et.po;



/**
 * SysRightUser generated by MyEclipse - Hibernate Tools
 */

public class SysRightUser  implements java.io.Serializable {


    // Fields    

     private String id;
     private SysUser sysUser;
     private SysModule sysModule;


    // Constructors

    /** default constructor */
    public SysRightUser() {
    }

	/** minimal constructor */
    public SysRightUser(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public SysRightUser(String id, SysUser sysUser, SysModule sysModule) {
        this.id = id;
        this.sysUser = sysUser;
        this.sysModule = sysModule;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public SysUser getSysUser() {
        return this.sysUser;
    }
    
    public void setSysUser(SysUser sysUser) {
        this.sysUser = sysUser;
    }

    public SysModule getSysModule() {
        return this.sysModule;
    }
    
    public void setSysModule(SysModule sysModule) {
        this.sysModule = sysModule;
    }
   








}