package et.po;

import java.util.Date;


/**
 * BookBorrowInfo generated by MyEclipse - Hibernate Tools
 */

public class BookBorrowInfo  implements java.io.Serializable {


    // Fields    

     private String id;
     private BookInfo bookInfo;
     private String bookUser;
     private Date borrowTime;
     private Date returnTime;


    // Constructors

    /** default constructor */
    public BookBorrowInfo() {
    }

	/** minimal constructor */
    public BookBorrowInfo(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public BookBorrowInfo(String id, BookInfo bookInfo, String bookUser, Date borrowTime, Date returnTime) {
        this.id = id;
        this.bookInfo = bookInfo;
        this.bookUser = bookUser;
        this.borrowTime = borrowTime;
        this.returnTime = returnTime;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public BookInfo getBookInfo() {
        return this.bookInfo;
    }
    
    public void setBookInfo(BookInfo bookInfo) {
        this.bookInfo = bookInfo;
    }

    public String getBookUser() {
        return this.bookUser;
    }
    
    public void setBookUser(String bookUser) {
        this.bookUser = bookUser;
    }

    public Date getBorrowTime() {
        return this.borrowTime;
    }
    
    public void setBorrowTime(Date borrowTime) {
        this.borrowTime = borrowTime;
    }

    public Date getReturnTime() {
        return this.returnTime;
    }
    
    public void setReturnTime(Date returnTime) {
        this.returnTime = returnTime;
    }
   








}