package et.po;



/**
 * CheckworkTimeId generated by MyEclipse - Hibernate Tools
 */

public class CheckworkTimeId  implements java.io.Serializable {


    // Fields    

     private String id;
     private String ondutyTime;
     private String offdutyTime;


    // Constructors

    /** default constructor */
    public CheckworkTimeId() {
    }

    
    /** full constructor */
    public CheckworkTimeId(String id, String ondutyTime, String offdutyTime) {
        this.id = id;
        this.ondutyTime = ondutyTime;
        this.offdutyTime = offdutyTime;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getOndutyTime() {
        return this.ondutyTime;
    }
    
    public void setOndutyTime(String ondutyTime) {
        this.ondutyTime = ondutyTime;
    }

    public String getOffdutyTime() {
        return this.offdutyTime;
    }
    
    public void setOffdutyTime(String offdutyTime) {
        this.offdutyTime = offdutyTime;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CheckworkTimeId) ) return false;
		 CheckworkTimeId castOther = ( CheckworkTimeId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getOndutyTime()==castOther.getOndutyTime()) || ( this.getOndutyTime()!=null && castOther.getOndutyTime()!=null && this.getOndutyTime().equals(castOther.getOndutyTime()) ) )
 && ( (this.getOffdutyTime()==castOther.getOffdutyTime()) || ( this.getOffdutyTime()!=null && castOther.getOffdutyTime()!=null && this.getOffdutyTime().equals(castOther.getOffdutyTime()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getOndutyTime() == null ? 0 : this.getOndutyTime().hashCode() );
         result = 37 * result + ( getOffdutyTime() == null ? 0 : this.getOffdutyTime().hashCode() );
         return result;
   }   





}