package et.po;

import java.util.Date;


/**
 * CheckworkInfo generated by MyEclipse - Hibernate Tools
 */

public class CheckworkInfo  implements java.io.Serializable {


    // Fields    

     private String id;
     private String userId;
     private String employeeId;
     private String departId;
     private Date checkDate;
     private String beginTime;
     private String endTime;
     private String remark;
     private String signMark;
     private Date repairDate;
     private String repairTime;
     private Date signDate;


    // Constructors

    /** default constructor */
    public CheckworkInfo() {
    }

	/** minimal constructor */
    public CheckworkInfo(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public CheckworkInfo(String id, String userId, String employeeId, String departId, Date checkDate, String beginTime, String endTime, String remark, String signMark, Date repairDate, String repairTime, Date signDate) {
        this.id = id;
        this.userId = userId;
        this.employeeId = employeeId;
        this.departId = departId;
        this.checkDate = checkDate;
        this.beginTime = beginTime;
        this.endTime = endTime;
        this.remark = remark;
        this.signMark = signMark;
        this.repairDate = repairDate;
        this.repairTime = repairTime;
        this.signDate = signDate;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

    public String getDepartId() {
        return this.departId;
    }
    
    public void setDepartId(String departId) {
        this.departId = departId;
    }

    public Date getCheckDate() {
        return this.checkDate;
    }
    
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    public String getBeginTime() {
        return this.beginTime;
    }
    
    public void setBeginTime(String beginTime) {
        this.beginTime = beginTime;
    }

    public String getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getSignMark() {
        return this.signMark;
    }
    
    public void setSignMark(String signMark) {
        this.signMark = signMark;
    }

    public Date getRepairDate() {
        return this.repairDate;
    }
    
    public void setRepairDate(Date repairDate) {
        this.repairDate = repairDate;
    }

    public String getRepairTime() {
        return this.repairTime;
    }
    
    public void setRepairTime(String repairTime) {
        this.repairTime = repairTime;
    }

    public Date getSignDate() {
        return this.signDate;
    }
    
    public void setSignDate(Date signDate) {
        this.signDate = signDate;
    }
   








}