package et.po;

import java.util.Date;


/**
 * DriverStudentInfo generated by MyEclipse - Hibernate Tools
 */

public class DriverStudentInfo  implements java.io.Serializable {


    // Fields    

     private String id;
     private String classId;
     private String classStuId;
     private String classGrade;
     private Date classOpentime;


    // Constructors

    /** default constructor */
    public DriverStudentInfo() {
    }

	/** minimal constructor */
    public DriverStudentInfo(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public DriverStudentInfo(String id, String classId, String classStuId, String classGrade, Date classOpentime) {
        this.id = id;
        this.classId = classId;
        this.classStuId = classStuId;
        this.classGrade = classGrade;
        this.classOpentime = classOpentime;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getClassId() {
        return this.classId;
    }
    
    public void setClassId(String classId) {
        this.classId = classId;
    }

    public String getClassStuId() {
        return this.classStuId;
    }
    
    public void setClassStuId(String classStuId) {
        this.classStuId = classStuId;
    }

    public String getClassGrade() {
        return this.classGrade;
    }
    
    public void setClassGrade(String classGrade) {
        this.classGrade = classGrade;
    }

    public Date getClassOpentime() {
        return this.classOpentime;
    }
    
    public void setClassOpentime(Date classOpentime) {
        this.classOpentime = classOpentime;
    }
   








}