package et.po;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * FileManager generated by MyEclipse - Hibernate Tools
 */

public class FileManager  implements java.io.Serializable {


    // Fields    

     private String id;
     private String parentId;
     private String name;
     private String isFile;
     private String fileCode;
     private String fileKeyWord;
     private Date createTime;
     private Date updateTime;
     private String fileEdition;
     private String isAvailable;
     private String remark;
     private String fileSize;
     private String fileType;
     private String fileUploadMan;
     private String fileDetail;
     private String fileCheckMan;
     private String fileName;
     private Set fileRights = new HashSet(0);


    // Constructors

    /** default constructor */
    public FileManager() {
    }

	/** minimal constructor */
    public FileManager(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public FileManager(String id, String parentId, String name, String isFile, String fileCode, String fileKeyWord, Date createTime, Date updateTime, String fileEdition, String isAvailable, String remark, String fileSize, String fileType, String fileUploadMan, String fileDetail, String fileCheckMan, String fileName, Set fileRights) {
        this.id = id;
        this.parentId = parentId;
        this.name = name;
        this.isFile = isFile;
        this.fileCode = fileCode;
        this.fileKeyWord = fileKeyWord;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.fileEdition = fileEdition;
        this.isAvailable = isAvailable;
        this.remark = remark;
        this.fileSize = fileSize;
        this.fileType = fileType;
        this.fileUploadMan = fileUploadMan;
        this.fileDetail = fileDetail;
        this.fileCheckMan = fileCheckMan;
        this.fileName = fileName;
        this.fileRights = fileRights;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getParentId() {
        return this.parentId;
    }
    
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getIsFile() {
        return this.isFile;
    }
    
    public void setIsFile(String isFile) {
        this.isFile = isFile;
    }

    public String getFileCode() {
        return this.fileCode;
    }
    
    public void setFileCode(String fileCode) {
        this.fileCode = fileCode;
    }

    public String getFileKeyWord() {
        return this.fileKeyWord;
    }
    
    public void setFileKeyWord(String fileKeyWord) {
        this.fileKeyWord = fileKeyWord;
    }

    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getFileEdition() {
        return this.fileEdition;
    }
    
    public void setFileEdition(String fileEdition) {
        this.fileEdition = fileEdition;
    }

    public String getIsAvailable() {
        return this.isAvailable;
    }
    
    public void setIsAvailable(String isAvailable) {
        this.isAvailable = isAvailable;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }

    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    public String getFileUploadMan() {
        return this.fileUploadMan;
    }
    
    public void setFileUploadMan(String fileUploadMan) {
        this.fileUploadMan = fileUploadMan;
    }

    public String getFileDetail() {
        return this.fileDetail;
    }
    
    public void setFileDetail(String fileDetail) {
        this.fileDetail = fileDetail;
    }

    public String getFileCheckMan() {
        return this.fileCheckMan;
    }
    
    public void setFileCheckMan(String fileCheckMan) {
        this.fileCheckMan = fileCheckMan;
    }

    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public Set getFileRights() {
        return this.fileRights;
    }
    
    public void setFileRights(Set fileRights) {
        this.fileRights = fileRights;
    }
   








}