package et.po;



/**
 * FileRight generated by MyEclipse - Hibernate Tools
 */

public class FileRight  implements java.io.Serializable {


    // Fields    

     private String id;
     private SysUser sysUser;
     private FileManager fileManager;
     private String rightNew;
     private String rightManager;
     private String rightView;


    // Constructors

    /** default constructor */
    public FileRight() {
    }

	/** minimal constructor */
    public FileRight(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public FileRight(String id, SysUser sysUser, FileManager fileManager, String rightNew, String rightManager, String rightView) {
        this.id = id;
        this.sysUser = sysUser;
        this.fileManager = fileManager;
        this.rightNew = rightNew;
        this.rightManager = rightManager;
        this.rightView = rightView;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public SysUser getSysUser() {
        return this.sysUser;
    }
    
    public void setSysUser(SysUser sysUser) {
        this.sysUser = sysUser;
    }

    public FileManager getFileManager() {
        return this.fileManager;
    }
    
    public void setFileManager(FileManager fileManager) {
        this.fileManager = fileManager;
    }

    public String getRightNew() {
        return this.rightNew;
    }
    
    public void setRightNew(String rightNew) {
        this.rightNew = rightNew;
    }

    public String getRightManager() {
        return this.rightManager;
    }
    
    public void setRightManager(String rightManager) {
        this.rightManager = rightManager;
    }

    public String getRightView() {
        return this.rightView;
    }
    
    public void setRightView(String rightView) {
        this.rightView = rightView;
    }
   








}