package et.po;

import java.util.HashSet;
import java.util.Set;


/**
 * FlowDefine generated by MyEclipse - Hibernate Tools
 */

public class FlowDefine  implements java.io.Serializable {


    // Fields    

     private String id;
     private WorkflowDefine workflowDefine;
     private String flowDefId;
     private String flowDefType;
     private String flowDefName;
     private String flowDefAction;
     private String flowDefActor;
     private String flowDefNextActor;
     private Set flowNextSteps = new HashSet(0);
     private Set flowInstances = new HashSet(0);


    // Constructors

    /** default constructor */
    public FlowDefine() {
    }

	/** minimal constructor */
    public FlowDefine(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public FlowDefine(String id, WorkflowDefine workflowDefine, String flowDefId, String flowDefType, String flowDefName, String flowDefAction, String flowDefActor, String flowDefNextActor, Set flowNextSteps, Set flowInstances) {
        this.id = id;
        this.workflowDefine = workflowDefine;
        this.flowDefId = flowDefId;
        this.flowDefType = flowDefType;
        this.flowDefName = flowDefName;
        this.flowDefAction = flowDefAction;
        this.flowDefActor = flowDefActor;
        this.flowDefNextActor = flowDefNextActor;
        this.flowNextSteps = flowNextSteps;
        this.flowInstances = flowInstances;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public WorkflowDefine getWorkflowDefine() {
        return this.workflowDefine;
    }
    
    public void setWorkflowDefine(WorkflowDefine workflowDefine) {
        this.workflowDefine = workflowDefine;
    }

    public String getFlowDefId() {
        return this.flowDefId;
    }
    
    public void setFlowDefId(String flowDefId) {
        this.flowDefId = flowDefId;
    }

    public String getFlowDefType() {
        return this.flowDefType;
    }
    
    public void setFlowDefType(String flowDefType) {
        this.flowDefType = flowDefType;
    }

    public String getFlowDefName() {
        return this.flowDefName;
    }
    
    public void setFlowDefName(String flowDefName) {
        this.flowDefName = flowDefName;
    }

    public String getFlowDefAction() {
        return this.flowDefAction;
    }
    
    public void setFlowDefAction(String flowDefAction) {
        this.flowDefAction = flowDefAction;
    }

    public String getFlowDefActor() {
        return this.flowDefActor;
    }
    
    public void setFlowDefActor(String flowDefActor) {
        this.flowDefActor = flowDefActor;
    }

    public String getFlowDefNextActor() {
        return this.flowDefNextActor;
    }
    
    public void setFlowDefNextActor(String flowDefNextActor) {
        this.flowDefNextActor = flowDefNextActor;
    }

    public Set getFlowNextSteps() {
        return this.flowNextSteps;
    }
    
    public void setFlowNextSteps(Set flowNextSteps) {
        this.flowNextSteps = flowNextSteps;
    }

    public Set getFlowInstances() {
        return this.flowInstances;
    }
    
    public void setFlowInstances(Set flowInstances) {
        this.flowInstances = flowInstances;
    }
   








}