package et.po;



/**
 * FlowRight generated by MyEclipse - Hibernate Tools
 */

public class FlowRight  implements java.io.Serializable {


    // Fields    

     private String id;
     private String flowActor;
     private String oaUser;
     private String oaRole;


    // Constructors

    /** default constructor */
    public FlowRight() {
    }

	/** minimal constructor */
    public FlowRight(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public FlowRight(String id, String flowActor, String oaUser, String oaRole) {
        this.id = id;
        this.flowActor = flowActor;
        this.oaUser = oaUser;
        this.oaRole = oaRole;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getFlowActor() {
        return this.flowActor;
    }
    
    public void setFlowActor(String flowActor) {
        this.flowActor = flowActor;
    }

    public String getOaUser() {
        return this.oaUser;
    }
    
    public void setOaUser(String oaUser) {
        this.oaUser = oaUser;
    }

    public String getOaRole() {
        return this.oaRole;
    }
    
    public void setOaRole(String oaRole) {
        this.oaRole = oaRole;
    }
   








}