package et.po;

import java.util.Date;


/**
 * ForumUserInfo generated by MyEclipse - Hibernate Tools
 */

public class ForumUserInfo  implements java.io.Serializable {


    // Fields    

     private String id;
     private String name;
     private String password;
     private String question;
     private String answer;
     private String groomUser;
     private String email;
     private String qq;
     private String msn;
     private String icq;
     private String homepage;
     private String introself;
     private String country;
     private Date birthday;
     private String style;
     private String language;
     private String areaId;
     private String forumPublishId;
     private Integer point;
     private String forumRole;
     private String experience;
     private Date registerDate;
     private String sex;
     private Date lastLogin;
     private String headImage;
     private String underWrite;
     private String remark;
     private String registerIp;
     private String newlyIp;
     private Integer sendPostNum;
     private Integer answerPostNum;


    // Constructors

    /** default constructor */
    public ForumUserInfo() {
    }

	/** minimal constructor */
    public ForumUserInfo(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public ForumUserInfo(String id, String name, String password, String question, String answer, String groomUser, String email, String qq, String msn, String icq, String homepage, String introself, String country, Date birthday, String style, String language, String areaId, String forumPublishId, Integer point, String forumRole, String experience, Date registerDate, String sex, Date lastLogin, String headImage, String underWrite, String remark, String registerIp, String newlyIp, Integer sendPostNum, Integer answerPostNum) {
        this.id = id;
        this.name = name;
        this.password = password;
        this.question = question;
        this.answer = answer;
        this.groomUser = groomUser;
        this.email = email;
        this.qq = qq;
        this.msn = msn;
        this.icq = icq;
        this.homepage = homepage;
        this.introself = introself;
        this.country = country;
        this.birthday = birthday;
        this.style = style;
        this.language = language;
        this.areaId = areaId;
        this.forumPublishId = forumPublishId;
        this.point = point;
        this.forumRole = forumRole;
        this.experience = experience;
        this.registerDate = registerDate;
        this.sex = sex;
        this.lastLogin = lastLogin;
        this.headImage = headImage;
        this.underWrite = underWrite;
        this.remark = remark;
        this.registerIp = registerIp;
        this.newlyIp = newlyIp;
        this.sendPostNum = sendPostNum;
        this.answerPostNum = answerPostNum;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }

    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public String getGroomUser() {
        return this.groomUser;
    }
    
    public void setGroomUser(String groomUser) {
        this.groomUser = groomUser;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getQq() {
        return this.qq;
    }
    
    public void setQq(String qq) {
        this.qq = qq;
    }

    public String getMsn() {
        return this.msn;
    }
    
    public void setMsn(String msn) {
        this.msn = msn;
    }

    public String getIcq() {
        return this.icq;
    }
    
    public void setIcq(String icq) {
        this.icq = icq;
    }

    public String getHomepage() {
        return this.homepage;
    }
    
    public void setHomepage(String homepage) {
        this.homepage = homepage;
    }

    public String getIntroself() {
        return this.introself;
    }
    
    public void setIntroself(String introself) {
        this.introself = introself;
    }

    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getStyle() {
        return this.style;
    }
    
    public void setStyle(String style) {
        this.style = style;
    }

    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }

    public String getAreaId() {
        return this.areaId;
    }
    
    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    public String getForumPublishId() {
        return this.forumPublishId;
    }
    
    public void setForumPublishId(String forumPublishId) {
        this.forumPublishId = forumPublishId;
    }

    public Integer getPoint() {
        return this.point;
    }
    
    public void setPoint(Integer point) {
        this.point = point;
    }

    public String getForumRole() {
        return this.forumRole;
    }
    
    public void setForumRole(String forumRole) {
        this.forumRole = forumRole;
    }

    public String getExperience() {
        return this.experience;
    }
    
    public void setExperience(String experience) {
        this.experience = experience;
    }

    public Date getRegisterDate() {
        return this.registerDate;
    }
    
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    public String getHeadImage() {
        return this.headImage;
    }
    
    public void setHeadImage(String headImage) {
        this.headImage = headImage;
    }

    public String getUnderWrite() {
        return this.underWrite;
    }
    
    public void setUnderWrite(String underWrite) {
        this.underWrite = underWrite;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getRegisterIp() {
        return this.registerIp;
    }
    
    public void setRegisterIp(String registerIp) {
        this.registerIp = registerIp;
    }

    public String getNewlyIp() {
        return this.newlyIp;
    }
    
    public void setNewlyIp(String newlyIp) {
        this.newlyIp = newlyIp;
    }

    public Integer getSendPostNum() {
        return this.sendPostNum;
    }
    
    public void setSendPostNum(Integer sendPostNum) {
        this.sendPostNum = sendPostNum;
    }

    public Integer getAnswerPostNum() {
        return this.answerPostNum;
    }
    
    public void setAnswerPostNum(Integer answerPostNum) {
        this.answerPostNum = answerPostNum;
    }
   








}