package et.po;

import java.util.Date;


/**
 * GovMotorInfo generated by MyEclipse - Hibernate Tools
 */

public class GovMotorInfo  implements java.io.Serializable {


    // Fields    

     private String motorId;
     private String driverId;
     private String motorType;
     private String motorCode;
     private String motorPlate;
     private Date motorDate;
     private Integer motorYear;
     private String motorColor;
     private String motorHome;
     private String motorSign;
     private String motorReject;
     private String motorImage;
     private String motorRemark;
     private String motorCheck;


    // Constructors

    /** default constructor */
    public GovMotorInfo() {
    }

	/** minimal constructor */
    public GovMotorInfo(String motorId) {
        this.motorId = motorId;
    }
    
    /** full constructor */
    public GovMotorInfo(String motorId, String driverId, String motorType, String motorCode, String motorPlate, Date motorDate, Integer motorYear, String motorColor, String motorHome, String motorSign, String motorReject, String motorImage, String motorRemark, String motorCheck) {
        this.motorId = motorId;
        this.driverId = driverId;
        this.motorType = motorType;
        this.motorCode = motorCode;
        this.motorPlate = motorPlate;
        this.motorDate = motorDate;
        this.motorYear = motorYear;
        this.motorColor = motorColor;
        this.motorHome = motorHome;
        this.motorSign = motorSign;
        this.motorReject = motorReject;
        this.motorImage = motorImage;
        this.motorRemark = motorRemark;
        this.motorCheck = motorCheck;
    }

   
    // Property accessors

    public String getMotorId() {
        return this.motorId;
    }
    
    public void setMotorId(String motorId) {
        this.motorId = motorId;
    }

    public String getDriverId() {
        return this.driverId;
    }
    
    public void setDriverId(String driverId) {
        this.driverId = driverId;
    }

    public String getMotorType() {
        return this.motorType;
    }
    
    public void setMotorType(String motorType) {
        this.motorType = motorType;
    }

    public String getMotorCode() {
        return this.motorCode;
    }
    
    public void setMotorCode(String motorCode) {
        this.motorCode = motorCode;
    }

    public String getMotorPlate() {
        return this.motorPlate;
    }
    
    public void setMotorPlate(String motorPlate) {
        this.motorPlate = motorPlate;
    }

    public Date getMotorDate() {
        return this.motorDate;
    }
    
    public void setMotorDate(Date motorDate) {
        this.motorDate = motorDate;
    }

    public Integer getMotorYear() {
        return this.motorYear;
    }
    
    public void setMotorYear(Integer motorYear) {
        this.motorYear = motorYear;
    }

    public String getMotorColor() {
        return this.motorColor;
    }
    
    public void setMotorColor(String motorColor) {
        this.motorColor = motorColor;
    }

    public String getMotorHome() {
        return this.motorHome;
    }
    
    public void setMotorHome(String motorHome) {
        this.motorHome = motorHome;
    }

    public String getMotorSign() {
        return this.motorSign;
    }
    
    public void setMotorSign(String motorSign) {
        this.motorSign = motorSign;
    }

    public String getMotorReject() {
        return this.motorReject;
    }
    
    public void setMotorReject(String motorReject) {
        this.motorReject = motorReject;
    }

    public String getMotorImage() {
        return this.motorImage;
    }
    
    public void setMotorImage(String motorImage) {
        this.motorImage = motorImage;
    }

    public String getMotorRemark() {
        return this.motorRemark;
    }
    
    public void setMotorRemark(String motorRemark) {
        this.motorRemark = motorRemark;
    }

    public String getMotorCheck() {
        return this.motorCheck;
    }
    
    public void setMotorCheck(String motorCheck) {
        this.motorCheck = motorCheck;
    }
   








}