package et.po;

import java.util.Date;


/**
 * GovUserInfo generated by MyEclipse - Hibernate Tools
 */

public class GovUserInfo  implements java.io.Serializable {


    // Fields    

     private String userId;
     private String userPwd;
     private String userName;
     private Integer userSex;
     private Date userDate;
     private String userQq;
     private String userEmail;
     private String userAddress;
     private String userPhone;
     private String userMobile;
     private String userCompany;
     private String userDuty;
     private String userImage;
     private String delMark;
     private String userRemark;


    // Constructors

    /** default constructor */
    public GovUserInfo() {
    }

	/** minimal constructor */
    public GovUserInfo(String userId) {
        this.userId = userId;
    }
    
    /** full constructor */
    public GovUserInfo(String userId, String userPwd, String userName, Integer userSex, Date userDate, String userQq, String userEmail, String userAddress, String userPhone, String userMobile, String userCompany, String userDuty, String userImage, String delMark, String userRemark) {
        this.userId = userId;
        this.userPwd = userPwd;
        this.userName = userName;
        this.userSex = userSex;
        this.userDate = userDate;
        this.userQq = userQq;
        this.userEmail = userEmail;
        this.userAddress = userAddress;
        this.userPhone = userPhone;
        this.userMobile = userMobile;
        this.userCompany = userCompany;
        this.userDuty = userDuty;
        this.userImage = userImage;
        this.delMark = delMark;
        this.userRemark = userRemark;
    }

   
    // Property accessors

    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserPwd() {
        return this.userPwd;
    }
    
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }

    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Integer getUserSex() {
        return this.userSex;
    }
    
    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }

    public Date getUserDate() {
        return this.userDate;
    }
    
    public void setUserDate(Date userDate) {
        this.userDate = userDate;
    }

    public String getUserQq() {
        return this.userQq;
    }
    
    public void setUserQq(String userQq) {
        this.userQq = userQq;
    }

    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public String getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

    public String getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    public String getUserMobile() {
        return this.userMobile;
    }
    
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile;
    }

    public String getUserCompany() {
        return this.userCompany;
    }
    
    public void setUserCompany(String userCompany) {
        this.userCompany = userCompany;
    }

    public String getUserDuty() {
        return this.userDuty;
    }
    
    public void setUserDuty(String userDuty) {
        this.userDuty = userDuty;
    }

    public String getUserImage() {
        return this.userImage;
    }
    
    public void setUserImage(String userImage) {
        this.userImage = userImage;
    }

    public String getDelMark() {
        return this.delMark;
    }
    
    public void setDelMark(String delMark) {
        this.delMark = delMark;
    }

    public String getUserRemark() {
        return this.userRemark;
    }
    
    public void setUserRemark(String userRemark) {
        this.userRemark = userRemark;
    }
   








}