package et.po;

import java.util.Date;


/**
 * InadjunctInfo generated by MyEclipse - Hibernate Tools
 */

public class InadjunctInfo  implements java.io.Serializable {


    // Fields    

     private String id;
     private InemailInfo inemailInfo;
     private String adjunctAddr;
     private String adjunctType;
     private String adjunctName;
     private String adjunctKey;
     private Date delTime;
     private Date createTime;
     private String operUser;
     private String remark;


    // Constructors

    /** default constructor */
    public InadjunctInfo() {
    }

	/** minimal constructor */
    public InadjunctInfo(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public InadjunctInfo(String id, InemailInfo inemailInfo, String adjunctAddr, String adjunctType, String adjunctName, String adjunctKey, Date delTime, Date createTime, String operUser, String remark) {
        this.id = id;
        this.inemailInfo = inemailInfo;
        this.adjunctAddr = adjunctAddr;
        this.adjunctType = adjunctType;
        this.adjunctName = adjunctName;
        this.adjunctKey = adjunctKey;
        this.delTime = delTime;
        this.createTime = createTime;
        this.operUser = operUser;
        this.remark = remark;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public InemailInfo getInemailInfo() {
        return this.inemailInfo;
    }
    
    public void setInemailInfo(InemailInfo inemailInfo) {
        this.inemailInfo = inemailInfo;
    }

    public String getAdjunctAddr() {
        return this.adjunctAddr;
    }
    
    public void setAdjunctAddr(String adjunctAddr) {
        this.adjunctAddr = adjunctAddr;
    }

    public String getAdjunctType() {
        return this.adjunctType;
    }
    
    public void setAdjunctType(String adjunctType) {
        this.adjunctType = adjunctType;
    }

    public String getAdjunctName() {
        return this.adjunctName;
    }
    
    public void setAdjunctName(String adjunctName) {
        this.adjunctName = adjunctName;
    }

    public String getAdjunctKey() {
        return this.adjunctKey;
    }
    
    public void setAdjunctKey(String adjunctKey) {
        this.adjunctKey = adjunctKey;
    }

    public Date getDelTime() {
        return this.delTime;
    }
    
    public void setDelTime(Date delTime) {
        this.delTime = delTime;
    }

    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getOperUser() {
        return this.operUser;
    }
    
    public void setOperUser(String operUser) {
        this.operUser = operUser;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
   








}