package et.po;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * InemailInfo generated by MyEclipse - Hibernate Tools
 */

public class InemailInfo  implements java.io.Serializable {


    // Fields    

     private String id;
     private String sendUser;
     private String takeUser;
     private String takeList;
     private String copyList;
     private String secretList;
     private String emailTitle;
     private String emailInfo;
     private Date createTime;
     private Date sendTime;
     private String sendType;
     private String emailType;
     private String emailSign;
     private String issend;
     private String operSign;
     private String inorout;
     private String emailboxId;
     private String delSign;
     private String remark;
     private Set inadjunctInfos = new HashSet(0);


    // Constructors

    /** default constructor */
    public InemailInfo() {
    }

	/** minimal constructor */
    public InemailInfo(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public InemailInfo(String id, String sendUser, String takeUser, String takeList, String copyList, String secretList, String emailTitle, String emailInfo, Date createTime, Date sendTime, String sendType, String emailType, String emailSign, String issend, String operSign, String inorout, String emailboxId, String delSign, String remark, Set inadjunctInfos) {
        this.id = id;
        this.sendUser = sendUser;
        this.takeUser = takeUser;
        this.takeList = takeList;
        this.copyList = copyList;
        this.secretList = secretList;
        this.emailTitle = emailTitle;
        this.emailInfo = emailInfo;
        this.createTime = createTime;
        this.sendTime = sendTime;
        this.sendType = sendType;
        this.emailType = emailType;
        this.emailSign = emailSign;
        this.issend = issend;
        this.operSign = operSign;
        this.inorout = inorout;
        this.emailboxId = emailboxId;
        this.delSign = delSign;
        this.remark = remark;
        this.inadjunctInfos = inadjunctInfos;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getSendUser() {
        return this.sendUser;
    }
    
    public void setSendUser(String sendUser) {
        this.sendUser = sendUser;
    }

    public String getTakeUser() {
        return this.takeUser;
    }
    
    public void setTakeUser(String takeUser) {
        this.takeUser = takeUser;
    }

    public String getTakeList() {
        return this.takeList;
    }
    
    public void setTakeList(String takeList) {
        this.takeList = takeList;
    }

    public String getCopyList() {
        return this.copyList;
    }
    
    public void setCopyList(String copyList) {
        this.copyList = copyList;
    }

    public String getSecretList() {
        return this.secretList;
    }
    
    public void setSecretList(String secretList) {
        this.secretList = secretList;
    }

    public String getEmailTitle() {
        return this.emailTitle;
    }
    
    public void setEmailTitle(String emailTitle) {
        this.emailTitle = emailTitle;
    }

    public String getEmailInfo() {
        return this.emailInfo;
    }
    
    public void setEmailInfo(String emailInfo) {
        this.emailInfo = emailInfo;
    }

    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getSendTime() {
        return this.sendTime;
    }
    
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    public String getSendType() {
        return this.sendType;
    }
    
    public void setSendType(String sendType) {
        this.sendType = sendType;
    }

    public String getEmailType() {
        return this.emailType;
    }
    
    public void setEmailType(String emailType) {
        this.emailType = emailType;
    }

    public String getEmailSign() {
        return this.emailSign;
    }
    
    public void setEmailSign(String emailSign) {
        this.emailSign = emailSign;
    }

    public String getIssend() {
        return this.issend;
    }
    
    public void setIssend(String issend) {
        this.issend = issend;
    }

    public String getOperSign() {
        return this.operSign;
    }
    
    public void setOperSign(String operSign) {
        this.operSign = operSign;
    }

    public String getInorout() {
        return this.inorout;
    }
    
    public void setInorout(String inorout) {
        this.inorout = inorout;
    }

    public String getEmailboxId() {
        return this.emailboxId;
    }
    
    public void setEmailboxId(String emailboxId) {
        this.emailboxId = emailboxId;
    }

    public String getDelSign() {
        return this.delSign;
    }
    
    public void setDelSign(String delSign) {
        this.delSign = delSign;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Set getInadjunctInfos() {
        return this.inadjunctInfos;
    }
    
    public void setInadjunctInfos(Set inadjunctInfos) {
        this.inadjunctInfos = inadjunctInfos;
    }
   








}