package et.po;

import java.util.HashSet;
import java.util.Set;


/**
 * NewsFormatInfo generated by MyEclipse - Hibernate Tools
 */

public class NewsFormatInfo  implements java.io.Serializable {


    // Fields    

     private String classId;
     private Integer formatType;
     private Integer delMark;
     private String remark;
     private Set newsFormatDetails = new HashSet(0);


    // Constructors

    /** default constructor */
    public NewsFormatInfo() {
    }

	/** minimal constructor */
    public NewsFormatInfo(String classId) {
        this.classId = classId;
    }
    
    /** full constructor */
    public NewsFormatInfo(String classId, Integer formatType, Integer delMark, String remark, Set newsFormatDetails) {
        this.classId = classId;
        this.formatType = formatType;
        this.delMark = delMark;
        this.remark = remark;
        this.newsFormatDetails = newsFormatDetails;
    }

   
    // Property accessors

    public String getClassId() {
        return this.classId;
    }
    
    public void setClassId(String classId) {
        this.classId = classId;
    }

    public Integer getFormatType() {
        return this.formatType;
    }
    
    public void setFormatType(Integer formatType) {
        this.formatType = formatType;
    }

    public Integer getDelMark() {
        return this.delMark;
    }
    
    public void setDelMark(Integer delMark) {
        this.delMark = delMark;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Set getNewsFormatDetails() {
        return this.newsFormatDetails;
    }
    
    public void setNewsFormatDetails(Set newsFormatDetails) {
        this.newsFormatDetails = newsFormatDetails;
    }
   








}