package et.po;



/**
 * NewsStyle generated by MyEclipse - Hibernate Tools
 */

public class NewsStyle  implements java.io.Serializable {


    // Fields    

     private String id;
     private String styleDescribe;
     private String newsNum;
     private String showStyle;
     private String titleCharNum;
     private String titleCharColor;
     private String titleCharFont;
     private String titleCharSize;
     private String contentCharNum;
     private String articleProperty;
     private String author;
     private String clickTimes;
     private String updatetime;
     private String showMore;
     private String isHot;
     private String hotArticle;
     private String tuijianArticle;
     private String dateRange;
     private String paixuField;
     private String paixuMethod;


    // Constructors

    /** default constructor */
    public NewsStyle() {
    }

	/** minimal constructor */
    public NewsStyle(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public NewsStyle(String id, String styleDescribe, String newsNum, String showStyle, String titleCharNum, String titleCharColor, String titleCharFont, String titleCharSize, String contentCharNum, String articleProperty, String author, String clickTimes, String updatetime, String showMore, String isHot, String hotArticle, String tuijianArticle, String dateRange, String paixuField, String paixuMethod) {
        this.id = id;
        this.styleDescribe = styleDescribe;
        this.newsNum = newsNum;
        this.showStyle = showStyle;
        this.titleCharNum = titleCharNum;
        this.titleCharColor = titleCharColor;
        this.titleCharFont = titleCharFont;
        this.titleCharSize = titleCharSize;
        this.contentCharNum = contentCharNum;
        this.articleProperty = articleProperty;
        this.author = author;
        this.clickTimes = clickTimes;
        this.updatetime = updatetime;
        this.showMore = showMore;
        this.isHot = isHot;
        this.hotArticle = hotArticle;
        this.tuijianArticle = tuijianArticle;
        this.dateRange = dateRange;
        this.paixuField = paixuField;
        this.paixuMethod = paixuMethod;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getStyleDescribe() {
        return this.styleDescribe;
    }
    
    public void setStyleDescribe(String styleDescribe) {
        this.styleDescribe = styleDescribe;
    }

    public String getNewsNum() {
        return this.newsNum;
    }
    
    public void setNewsNum(String newsNum) {
        this.newsNum = newsNum;
    }

    public String getShowStyle() {
        return this.showStyle;
    }
    
    public void setShowStyle(String showStyle) {
        this.showStyle = showStyle;
    }

    public String getTitleCharNum() {
        return this.titleCharNum;
    }
    
    public void setTitleCharNum(String titleCharNum) {
        this.titleCharNum = titleCharNum;
    }

    public String getTitleCharColor() {
        return this.titleCharColor;
    }
    
    public void setTitleCharColor(String titleCharColor) {
        this.titleCharColor = titleCharColor;
    }

    public String getTitleCharFont() {
        return this.titleCharFont;
    }
    
    public void setTitleCharFont(String titleCharFont) {
        this.titleCharFont = titleCharFont;
    }

    public String getTitleCharSize() {
        return this.titleCharSize;
    }
    
    public void setTitleCharSize(String titleCharSize) {
        this.titleCharSize = titleCharSize;
    }

    public String getContentCharNum() {
        return this.contentCharNum;
    }
    
    public void setContentCharNum(String contentCharNum) {
        this.contentCharNum = contentCharNum;
    }

    public String getArticleProperty() {
        return this.articleProperty;
    }
    
    public void setArticleProperty(String articleProperty) {
        this.articleProperty = articleProperty;
    }

    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }

    public String getClickTimes() {
        return this.clickTimes;
    }
    
    public void setClickTimes(String clickTimes) {
        this.clickTimes = clickTimes;
    }

    public String getUpdatetime() {
        return this.updatetime;
    }
    
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime;
    }

    public String getShowMore() {
        return this.showMore;
    }
    
    public void setShowMore(String showMore) {
        this.showMore = showMore;
    }

    public String getIsHot() {
        return this.isHot;
    }
    
    public void setIsHot(String isHot) {
        this.isHot = isHot;
    }

    public String getHotArticle() {
        return this.hotArticle;
    }
    
    public void setHotArticle(String hotArticle) {
        this.hotArticle = hotArticle;
    }

    public String getTuijianArticle() {
        return this.tuijianArticle;
    }
    
    public void setTuijianArticle(String tuijianArticle) {
        this.tuijianArticle = tuijianArticle;
    }

    public String getDateRange() {
        return this.dateRange;
    }
    
    public void setDateRange(String dateRange) {
        this.dateRange = dateRange;
    }

    public String getPaixuField() {
        return this.paixuField;
    }
    
    public void setPaixuField(String paixuField) {
        this.paixuField = paixuField;
    }

    public String getPaixuMethod() {
        return this.paixuMethod;
    }
    
    public void setPaixuMethod(String paixuMethod) {
        this.paixuMethod = paixuMethod;
    }
   








}