package et.po;



/**
 * NewsArea generated by MyEclipse - Hibernate Tools
 */

public class NewsArea  implements java.io.Serializable {


    // Fields    

     private String id;
     private String styleId;
     private String newsAreaName;
     private String remark;


    // Constructors

    /** default constructor */
    public NewsArea() {
    }

	/** minimal constructor */
    public NewsArea(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public NewsArea(String id, String styleId, String newsAreaName, String remark) {
        this.id = id;
        this.styleId = styleId;
        this.newsAreaName = newsAreaName;
        this.remark = remark;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getStyleId() {
        return this.styleId;
    }
    
    public void setStyleId(String styleId) {
        this.styleId = styleId;
    }

    public String getNewsAreaName() {
        return this.newsAreaName;
    }
    
    public void setNewsAreaName(String newsAreaName) {
        this.newsAreaName = newsAreaName;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
   








}