package et.po;

import java.util.HashSet;
import java.util.Set;


/**
 * WorkflowDefine generated by MyEclipse - Hibernate Tools
 */

public class WorkflowDefine  implements java.io.Serializable {


    // Fields    

     private String id;
     private String name;
     private String remark;
     private Set flowDefines = new HashSet(0);
     private Set workflowInstances = new HashSet(0);


    // Constructors

    /** default constructor */
    public WorkflowDefine() {
    }

	/** minimal constructor */
    public WorkflowDefine(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public WorkflowDefine(String id, String name, String remark, Set flowDefines, Set workflowInstances) {
        this.id = id;
        this.name = name;
        this.remark = remark;
        this.flowDefines = flowDefines;
        this.workflowInstances = workflowInstances;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Set getFlowDefines() {
        return this.flowDefines;
    }
    
    public void setFlowDefines(Set flowDefines) {
        this.flowDefines = flowDefines;
    }

    public Set getWorkflowInstances() {
        return this.workflowInstances;
    }
    
    public void setWorkflowInstances(Set workflowInstances) {
        this.workflowInstances = workflowInstances;
    }
   








}