/*
 * Generated by XDoclet - Do not edit!
 */
package et.bo.interfaces;

/**
 * Remote interface for TestString.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface TestString
   extends javax.ejb.EJBObject
{

   public java.lang.String printString( java.lang.String s )
      throws java.rmi.RemoteException;

   /**
    * An example business method
    * @throws EJBException Thrown if method fails due to system-level error.    */
   public void replaceWithRealBusinessMethod(  )
      throws java.rmi.RemoteException;

}
