/*
 * Generated by XDoclet - Do not edit!
 */
package et.bo.interfaces;

/**
 * Home interface for Testa.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface TestaHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Testa";
   public static final String JNDI_NAME="ejb/Testa";

   public et.bo.interfaces.Testa create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
