/*
 * Generated by XDoclet - Do not edit!
 */
package et.bo.interfaces;

/**
 * Remote interface for Testa.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface Testa
   extends javax.ejb.EJBObject
{
   /**
    * An example business method
    * @throws EJBException Thrown if method fails due to system-level error.    */
   public void replaceWithRealBusinessMethod(  )
      throws java.rmi.RemoteException;

}
