package et.po;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BaseTree generated by MyEclipse Persistence Tools
 */

public class BaseTree implements java.io.Serializable {

	// Fields

	private String id;

	private String nickName;

	private String label;

	private String parentId;

	private String type;

	private Date createTime;

	private Date modifyTime;

	private String deleteMark;

	private String layerOrder;

	private String isRoot;

	private String remark;

	private Set sysRightUsers = new HashSet(0);

	private Set viewTreeDetails = new HashSet(0);

	private Set sysRightGroups = new HashSet(0);

	private Set ccIvrTreeInfos = new HashSet(0);

	private Set sysLeafRights = new HashSet(0);

	// Constructors

	/** default constructor */
	public BaseTree() {
	}

	/** minimal constructor */
	public BaseTree(String id) {
		this.id = id;
	}

	/** full constructor */
	public BaseTree(String id, String nickName, String label, String parentId,
			String type, Date createTime, Date modifyTime, String deleteMark,
			String layerOrder, String isRoot, String remark, Set sysRightUsers,
			Set viewTreeDetails, Set sysRightGroups, Set ccIvrTreeInfos,
			Set sysLeafRights) {
		this.id = id;
		this.nickName = nickName;
		this.label = label;
		this.parentId = parentId;
		this.type = type;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
		this.deleteMark = deleteMark;
		this.layerOrder = layerOrder;
		this.isRoot = isRoot;
		this.remark = remark;
		this.sysRightUsers = sysRightUsers;
		this.viewTreeDetails = viewTreeDetails;
		this.sysRightGroups = sysRightGroups;
		this.ccIvrTreeInfos = ccIvrTreeInfos;
		this.sysLeafRights = sysLeafRights;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getDeleteMark() {
		return this.deleteMark;
	}

	public void setDeleteMark(String deleteMark) {
		this.deleteMark = deleteMark;
	}

	public String getLayerOrder() {
		return this.layerOrder;
	}

	public void setLayerOrder(String layerOrder) {
		this.layerOrder = layerOrder;
	}

	public String getIsRoot() {
		return this.isRoot;
	}

	public void setIsRoot(String isRoot) {
		this.isRoot = isRoot;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set getSysRightUsers() {
		return this.sysRightUsers;
	}

	public void setSysRightUsers(Set sysRightUsers) {
		this.sysRightUsers = sysRightUsers;
	}

	public Set getViewTreeDetails() {
		return this.viewTreeDetails;
	}

	public void setViewTreeDetails(Set viewTreeDetails) {
		this.viewTreeDetails = viewTreeDetails;
	}

	public Set getSysRightGroups() {
		return this.sysRightGroups;
	}

	public void setSysRightGroups(Set sysRightGroups) {
		this.sysRightGroups = sysRightGroups;
	}

	public Set getCcIvrTreeInfos() {
		return this.ccIvrTreeInfos;
	}

	public void setCcIvrTreeInfos(Set ccIvrTreeInfos) {
		this.ccIvrTreeInfos = ccIvrTreeInfos;
	}

	public Set getSysLeafRights() {
		return this.sysLeafRights;
	}

	public void setSysLeafRights(Set sysLeafRights) {
		this.sysLeafRights = sysLeafRights;
	}

}