package et.po;

import java.util.Date;

/**
 * CcAgentInfo generated by MyEclipse Persistence Tools
 */

public class CcAgentInfo implements java.io.Serializable {

	// Fields

	private String id;

	private String agentId;

	private String tzxzt;

	private Date tdlsj;

	private Date tdqsj;

	private Integer trzxl;

	private String clmzxl;

	private Double tfwzs;

	private Double tbcsc;

	private Integer tdqpds;

	private String cldjl;

	private String czxzcr;

	private String czxzj;

	private Date insertDate;

	private Date updateDate;

	// Constructors

	/** default constructor */
	public CcAgentInfo() {
	}

	/** minimal constructor */
	public CcAgentInfo(String id) {
		this.id = id;
	}

	/** full constructor */
	public CcAgentInfo(String id, String agentId, String tzxzt, Date tdlsj,
			Date tdqsj, Integer trzxl, String clmzxl, Double tfwzs,
			Double tbcsc, Integer tdqpds, String cldjl, String czxzcr,
			String czxzj, Date insertDate, Date updateDate) {
		this.id = id;
		this.agentId = agentId;
		this.tzxzt = tzxzt;
		this.tdlsj = tdlsj;
		this.tdqsj = tdqsj;
		this.trzxl = trzxl;
		this.clmzxl = clmzxl;
		this.tfwzs = tfwzs;
		this.tbcsc = tbcsc;
		this.tdqpds = tdqpds;
		this.cldjl = cldjl;
		this.czxzcr = czxzcr;
		this.czxzj = czxzj;
		this.insertDate = insertDate;
		this.updateDate = updateDate;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAgentId() {
		return this.agentId;
	}

	public void setAgentId(String agentId) {
		this.agentId = agentId;
	}

	public String getTzxzt() {
		return this.tzxzt;
	}

	public void setTzxzt(String tzxzt) {
		this.tzxzt = tzxzt;
	}

	public Date getTdlsj() {
		return this.tdlsj;
	}

	public void setTdlsj(Date tdlsj) {
		this.tdlsj = tdlsj;
	}

	public Date getTdqsj() {
		return this.tdqsj;
	}

	public void setTdqsj(Date tdqsj) {
		this.tdqsj = tdqsj;
	}

	public Integer getTrzxl() {
		return this.trzxl;
	}

	public void setTrzxl(Integer trzxl) {
		this.trzxl = trzxl;
	}

	public String getClmzxl() {
		return this.clmzxl;
	}

	public void setClmzxl(String clmzxl) {
		this.clmzxl = clmzxl;
	}

	public Double getTfwzs() {
		return this.tfwzs;
	}

	public void setTfwzs(Double tfwzs) {
		this.tfwzs = tfwzs;
	}

	public Double getTbcsc() {
		return this.tbcsc;
	}

	public void setTbcsc(Double tbcsc) {
		this.tbcsc = tbcsc;
	}

	public Integer getTdqpds() {
		return this.tdqpds;
	}

	public void setTdqpds(Integer tdqpds) {
		this.tdqpds = tdqpds;
	}

	public String getCldjl() {
		return this.cldjl;
	}

	public void setCldjl(String cldjl) {
		this.cldjl = cldjl;
	}

	public String getCzxzcr() {
		return this.czxzcr;
	}

	public void setCzxzcr(String czxzcr) {
		this.czxzcr = czxzcr;
	}

	public String getCzxzj() {
		return this.czxzj;
	}

	public void setCzxzj(String czxzj) {
		this.czxzj = czxzj;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}