package et.po;

import java.util.Date;

/**
 * CcConfMember generated by MyEclipse Persistence Tools
 */

public class CcConfMember implements java.io.Serializable {

	// Fields

	private String memberId;

	private CcConf ccConf;

	private String trunkNum;

	private String telCode;

	private Date confBegintime;

	private Date confEndtime;

	private String confKeeptime;

	// Constructors

	/** default constructor */
	public CcConfMember() {
	}

	/** full constructor */
	public CcConfMember(CcConf ccConf, String trunkNum, String telCode,
			Date confBegintime, Date confEndtime, String confKeeptime) {
		this.ccConf = ccConf;
		this.trunkNum = trunkNum;
		this.telCode = telCode;
		this.confBegintime = confBegintime;
		this.confEndtime = confEndtime;
		this.confKeeptime = confKeeptime;
	}

	// Property accessors

	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	public CcConf getCcConf() {
		return this.ccConf;
	}

	public void setCcConf(CcConf ccConf) {
		this.ccConf = ccConf;
	}

	public String getTrunkNum() {
		return this.trunkNum;
	}

	public void setTrunkNum(String trunkNum) {
		this.trunkNum = trunkNum;
	}

	public String getTelCode() {
		return this.telCode;
	}

	public void setTelCode(String telCode) {
		this.telCode = telCode;
	}

	public Date getConfBegintime() {
		return this.confBegintime;
	}

	public void setConfBegintime(Date confBegintime) {
		this.confBegintime = confBegintime;
	}

	public Date getConfEndtime() {
		return this.confEndtime;
	}

	public void setConfEndtime(Date confEndtime) {
		this.confEndtime = confEndtime;
	}

	public String getConfKeeptime() {
		return this.confKeeptime;
	}

	public void setConfKeeptime(String confKeeptime) {
		this.confKeeptime = confKeeptime;
	}

}