package et.po;

/**
 * CcFax generated by MyEclipse Persistence Tools
 */

public class CcFax implements java.io.Serializable {

	// Fields

	private String id;

	private CcMain ccMain;

	private String faxPath;

	private String faxBeginTime;

	private String faxEndTime;

	private String faxSendMan;

	private String faxNumber;

	private String faxType;

	private String isDelete;

	private String remark;

	// Constructors

	/** default constructor */
	public CcFax() {
	}

	/** full constructor */
	public CcFax(CcMain ccMain, String faxPath, String faxBeginTime,
			String faxEndTime, String faxSendMan, String faxNumber,
			String faxType, String isDelete, String remark) {
		this.ccMain = ccMain;
		this.faxPath = faxPath;
		this.faxBeginTime = faxBeginTime;
		this.faxEndTime = faxEndTime;
		this.faxSendMan = faxSendMan;
		this.faxNumber = faxNumber;
		this.faxType = faxType;
		this.isDelete = isDelete;
		this.remark = remark;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public CcMain getCcMain() {
		return this.ccMain;
	}

	public void setCcMain(CcMain ccMain) {
		this.ccMain = ccMain;
	}

	public String getFaxPath() {
		return this.faxPath;
	}

	public void setFaxPath(String faxPath) {
		this.faxPath = faxPath;
	}

	public String getFaxBeginTime() {
		return this.faxBeginTime;
	}

	public void setFaxBeginTime(String faxBeginTime) {
		this.faxBeginTime = faxBeginTime;
	}

	public String getFaxEndTime() {
		return this.faxEndTime;
	}

	public void setFaxEndTime(String faxEndTime) {
		this.faxEndTime = faxEndTime;
	}

	public String getFaxSendMan() {
		return this.faxSendMan;
	}

	public void setFaxSendMan(String faxSendMan) {
		this.faxSendMan = faxSendMan;
	}

	public String getFaxNumber() {
		return this.faxNumber;
	}

	public void setFaxNumber(String faxNumber) {
		this.faxNumber = faxNumber;
	}

	public String getFaxType() {
		return this.faxType;
	}

	public void setFaxType(String faxType) {
		this.faxType = faxType;
	}

	public String getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}