package et.po;

import java.util.Date;

/**
 * CcFirewall generated by MyEclipse Persistence Tools
 */

public class CcFirewall implements java.io.Serializable {

	// Fields

	private String id;

	private String phoneNum;

	private Date beginTime;

	private Date endTime;

	private String isPass;

	private String isAvailable;

	private String remark;

	// Constructors

	/** default constructor */
	public CcFirewall() {
	}

	/** minimal constructor */
	public CcFirewall(String id) {
		this.id = id;
	}

	/** full constructor */
	public CcFirewall(String id, String phoneNum, Date beginTime, Date endTime,
			String isPass, String isAvailable, String remark) {
		this.id = id;
		this.phoneNum = phoneNum;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.isPass = isPass;
		this.isAvailable = isAvailable;
		this.remark = remark;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPhoneNum() {
		return this.phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getIsPass() {
		return this.isPass;
	}

	public void setIsPass(String isPass) {
		this.isPass = isPass;
	}

	public String getIsAvailable() {
		return this.isAvailable;
	}

	public void setIsAvailable(String isAvailable) {
		this.isAvailable = isAvailable;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}