package et.po;

/**
 * CcIvrDeploy generated by MyEclipse Persistence Tools
 */

public class CcIvrDeploy implements java.io.Serializable {

	// Fields

	private String id;

	private String functype;

	private String nickname;

	private String content;

	private String voicefilepath;

	private String voicetype;

	private String keystroke;

	// Constructors

	/** default constructor */
	public CcIvrDeploy() {
	}

	/** minimal constructor */
	public CcIvrDeploy(String id) {
		this.id = id;
	}

	/** full constructor */
	public CcIvrDeploy(String id, String functype, String nickname,
			String content, String voicefilepath, String voicetype,
			String keystroke) {
		this.id = id;
		this.functype = functype;
		this.nickname = nickname;
		this.content = content;
		this.voicefilepath = voicefilepath;
		this.voicetype = voicetype;
		this.keystroke = keystroke;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFunctype() {
		return this.functype;
	}

	public void setFunctype(String functype) {
		this.functype = functype;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getVoicefilepath() {
		return this.voicefilepath;
	}

	public void setVoicefilepath(String voicefilepath) {
		this.voicefilepath = voicefilepath;
	}

	public String getVoicetype() {
		return this.voicetype;
	}

	public void setVoicetype(String voicetype) {
		this.voicetype = voicetype;
	}

	public String getKeystroke() {
		return this.keystroke;
	}

	public void setKeystroke(String keystroke) {
		this.keystroke = keystroke;
	}

}