package et.po;

/**
 * CcIvrVoiceinfo generated by MyEclipse Persistence Tools
 */

public class CcIvrVoiceinfo implements java.io.Serializable {

	// Fields

	private Integer id;

	private String ivrType;

	private String name;

	private String path;

	private String remark;

	private String voicetype;

	// Constructors

	/** default constructor */
	public CcIvrVoiceinfo() {
	}

	/** full constructor */
	public CcIvrVoiceinfo(String ivrType, String name, String path,
			String remark, String voicetype) {
		this.ivrType = ivrType;
		this.name = name;
		this.path = path;
		this.remark = remark;
		this.voicetype = voicetype;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getIvrType() {
		return this.ivrType;
	}

	public void setIvrType(String ivrType) {
		this.ivrType = ivrType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getVoicetype() {
		return this.voicetype;
	}

	public void setVoicetype(String voicetype) {
		this.voicetype = voicetype;
	}

}