package et.po;

/**
 * CcIvrTreevoiceDetail generated by MyEclipse Persistence Tools
 */

public class CcIvrTreevoiceDetail implements java.io.Serializable {

	// Fields

	private String id;

	private CcIvrTreeInfo ccIvrTreeInfo;

	private String layerOrder;

	private String voicePath;

	private String isUse;

	private String remark;

	private String languageType;

	// Constructors

	/** default constructor */
	public CcIvrTreevoiceDetail() {
	}

	/** minimal constructor */
	public CcIvrTreevoiceDetail(String id) {
		this.id = id;
	}

	/** full constructor */
	public CcIvrTreevoiceDetail(String id, CcIvrTreeInfo ccIvrTreeInfo,
			String layerOrder, String voicePath, String isUse, String remark,
			String languageType) {
		this.id = id;
		this.ccIvrTreeInfo = ccIvrTreeInfo;
		this.layerOrder = layerOrder;
		this.voicePath = voicePath;
		this.isUse = isUse;
		this.remark = remark;
		this.languageType = languageType;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public CcIvrTreeInfo getCcIvrTreeInfo() {
		return this.ccIvrTreeInfo;
	}

	public void setCcIvrTreeInfo(CcIvrTreeInfo ccIvrTreeInfo) {
		this.ccIvrTreeInfo = ccIvrTreeInfo;
	}

	public String getLayerOrder() {
		return this.layerOrder;
	}

	public void setLayerOrder(String layerOrder) {
		this.layerOrder = layerOrder;
	}

	public String getVoicePath() {
		return this.voicePath;
	}

	public void setVoicePath(String voicePath) {
		this.voicePath = voicePath;
	}

	public String getIsUse() {
		return this.isUse;
	}

	public void setIsUse(String isUse) {
		this.isUse = isUse;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getLanguageType() {
		return this.languageType;
	}

	public void setLanguageType(String languageType) {
		this.languageType = languageType;
	}

}