package et.po;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CcIvr generated by MyEclipse Persistence Tools
 */

public class CcIvr implements java.io.Serializable {

	// Fields

	private String id;

	private CcMain ccMain;

	private Date ivrBegintime;

	private Date ivrEndtime;

	private String processType;

	private String isDelete;

	private String remark;

	private Set ccIvrDates = new HashSet(0);

	// Constructors

	/** default constructor */
	public CcIvr() {
	}

	/** minimal constructor */
	public CcIvr(String id) {
		this.id = id;
	}

	/** full constructor */
	public CcIvr(String id, CcMain ccMain, Date ivrBegintime, Date ivrEndtime,
			String processType, String isDelete, String remark, Set ccIvrDates) {
		this.id = id;
		this.ccMain = ccMain;
		this.ivrBegintime = ivrBegintime;
		this.ivrEndtime = ivrEndtime;
		this.processType = processType;
		this.isDelete = isDelete;
		this.remark = remark;
		this.ccIvrDates = ccIvrDates;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public CcMain getCcMain() {
		return this.ccMain;
	}

	public void setCcMain(CcMain ccMain) {
		this.ccMain = ccMain;
	}

	public Date getIvrBegintime() {
		return this.ivrBegintime;
	}

	public void setIvrBegintime(Date ivrBegintime) {
		this.ivrBegintime = ivrBegintime;
	}

	public Date getIvrEndtime() {
		return this.ivrEndtime;
	}

	public void setIvrEndtime(Date ivrEndtime) {
		this.ivrEndtime = ivrEndtime;
	}

	public String getProcessType() {
		return this.processType;
	}

	public void setProcessType(String processType) {
		this.processType = processType;
	}

	public String getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set getCcIvrDates() {
		return this.ccIvrDates;
	}

	public void setCcIvrDates(Set ccIvrDates) {
		this.ccIvrDates = ccIvrDates;
	}

}