package et.po;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CcMain generated by MyEclipse Persistence Tools
 */

public class CcMain implements java.io.Serializable {

	// Fields

	private String id;

	private String beginPost;

	private String postType;

	private String telNum;

	private Date ringBegintime;

	private Date processEndtime;

	private Date recordBuildtime;

	private String processKeeptime;

	private String processType;

	private String isDelete;

	private String remark;

	private Set ccFaxes = new HashSet(0);

	private Set ccConfs = new HashSet(0);

	private Set groupEgressives = new HashSet(0);

	// Constructors

	/** default constructor */
	public CcMain() {
	}

	/** full constructor */
	public CcMain(String beginPost, String postType, String telNum,
			Date ringBegintime, Date processEndtime, Date recordBuildtime,
			String processKeeptime, String processType, String isDelete,
			String remark, Set ccFaxes, Set ccConfs, Set groupEgressives) {
		this.beginPost = beginPost;
		this.postType = postType;
		this.telNum = telNum;
		this.ringBegintime = ringBegintime;
		this.processEndtime = processEndtime;
		this.recordBuildtime = recordBuildtime;
		this.processKeeptime = processKeeptime;
		this.processType = processType;
		this.isDelete = isDelete;
		this.remark = remark;
		this.ccFaxes = ccFaxes;
		this.ccConfs = ccConfs;
		this.groupEgressives = groupEgressives;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getBeginPost() {
		return this.beginPost;
	}

	public void setBeginPost(String beginPost) {
		this.beginPost = beginPost;
	}

	public String getPostType() {
		return this.postType;
	}

	public void setPostType(String postType) {
		this.postType = postType;
	}

	public String getTelNum() {
		return this.telNum;
	}

	public void setTelNum(String telNum) {
		this.telNum = telNum;
	}

	public Date getRingBegintime() {
		return this.ringBegintime;
	}

	public void setRingBegintime(Date ringBegintime) {
		this.ringBegintime = ringBegintime;
	}

	public Date getProcessEndtime() {
		return this.processEndtime;
	}

	public void setProcessEndtime(Date processEndtime) {
		this.processEndtime = processEndtime;
	}

	public Date getRecordBuildtime() {
		return this.recordBuildtime;
	}

	public void setRecordBuildtime(Date recordBuildtime) {
		this.recordBuildtime = recordBuildtime;
	}

	public String getProcessKeeptime() {
		return this.processKeeptime;
	}

	public void setProcessKeeptime(String processKeeptime) {
		this.processKeeptime = processKeeptime;
	}

	public String getProcessType() {
		return this.processType;
	}

	public void setProcessType(String processType) {
		this.processType = processType;
	}

	public String getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set getCcFaxes() {
		return this.ccFaxes;
	}

	public void setCcFaxes(Set ccFaxes) {
		this.ccFaxes = ccFaxes;
	}

	public Set getCcConfs() {
		return this.ccConfs;
	}

	public void setCcConfs(Set ccConfs) {
		this.ccConfs = ccConfs;
	}

	public Set getGroupEgressives() {
		return this.groupEgressives;
	}

	public void setGroupEgressives(Set groupEgressives) {
		this.groupEgressives = groupEgressives;
	}

}