package et.po;

import java.util.Date;

/**
 * CcTalk generated by MyEclipse Persistence Tools
 */

public class CcTalk implements java.io.Serializable {

	// Fields

	private String id;

	private CcMain ccMain;

	private Date ringBegintime;

	private Date touchBegintime;

	private String waitingKeeptime;

	private Date touchEndtime;

	private String touchKeeptime;

	private String touchPost;
	
	private String recordPath;

	private String postType;

	private String respondent;

	private String respondentType;

	private String phoneNum;

	private Date displaceBegintime;

	private String displaceKeeptime;

	private String processType;

	private String isDelete;

	private String address;

	private String remark;
	
	private Date inserttime;

	// Constructors

	/** default constructor */
	public CcTalk() {
	}

	/** minimal constructor */
	public CcTalk(String id) {
		this.id = id;
	}

	/** full constructor */
	public CcTalk(String id, CcMain ccMain, Date ringBegintime,
			Date touchBegintime, String waitingKeeptime, Date touchEndtime,
			String touchKeeptime, String touchPost, String recordPath, String postType,
			String respondent, String respondentType, String phoneNum,
			Date displaceBegintime, String displaceKeeptime,
			String processType, String isDelete, String address, String remark, Date inserttime) {
		this.id = id;
		this.ccMain = ccMain;
		this.ringBegintime = ringBegintime;
		this.touchBegintime = touchBegintime;
		this.waitingKeeptime = waitingKeeptime;
		this.touchEndtime = touchEndtime;
		this.touchKeeptime = touchKeeptime;
		this.touchPost = touchPost;
		this.recordPath = recordPath;
		this.postType = postType;
		this.respondent = respondent;
		this.respondentType = respondentType;
		this.phoneNum = phoneNum;
		this.displaceBegintime = displaceBegintime;
		this.displaceKeeptime = displaceKeeptime;
		this.processType = processType;
		this.isDelete = isDelete;
		this.address = address;
		this.remark = remark;
		this.inserttime = inserttime;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public CcMain getCcMain() {
		return this.ccMain;
	}

	public void setCcMain(CcMain ccMain) {
		this.ccMain = ccMain;
	}

	public Date getRingBegintime() {
		return this.ringBegintime;
	}

	public void setRingBegintime(Date ringBegintime) {
		this.ringBegintime = ringBegintime;
	}

	public Date getTouchBegintime() {
		return this.touchBegintime;
	}

	public void setTouchBegintime(Date touchBegintime) {
		this.touchBegintime = touchBegintime;
	}

	public String getWaitingKeeptime() {
		return this.waitingKeeptime;
	}

	public void setWaitingKeeptime(String waitingKeeptime) {
		this.waitingKeeptime = waitingKeeptime;
	}

	public Date getTouchEndtime() {
		return this.touchEndtime;
	}

	public void setTouchEndtime(Date touchEndtime) {
		this.touchEndtime = touchEndtime;
	}

	public String getTouchKeeptime() {
		return this.touchKeeptime;
	}

	public void setTouchKeeptime(String touchKeeptime) {
		this.touchKeeptime = touchKeeptime;
	}

	public String getTouchPost() {
		return this.touchPost;
	}

	public void setTouchPost(String touchPost) {
		this.touchPost = touchPost;
	}
	
	public String getRecordPath() {
		return this.recordPath;
	}

	public void setRecordPath(String recordPath) {
		this.recordPath = recordPath;
	}

	public String getPostType() {
		return this.postType;
	}

	public void setPostType(String postType) {
		this.postType = postType;
	}

	public String getRespondent() {
		return this.respondent;
	}

	public void setRespondent(String respondent) {
		this.respondent = respondent;
	}

	public String getRespondentType() {
		return this.respondentType;
	}

	public void setRespondentType(String respondentType) {
		this.respondentType = respondentType;
	}

	public String getPhoneNum() {
		return this.phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	public Date getDisplaceBegintime() {
		return this.displaceBegintime;
	}

	public void setDisplaceBegintime(Date displaceBegintime) {
		this.displaceBegintime = displaceBegintime;
	}

	public String getDisplaceKeeptime() {
		return this.displaceKeeptime;
	}

	public void setDisplaceKeeptime(String displaceKeeptime) {
		this.displaceKeeptime = displaceKeeptime;
	}

	public String getProcessType() {
		return this.processType;
	}

	public void setProcessType(String processType) {
		this.processType = processType;
	}

	public String getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getInserttime() {
		return inserttime;
	}

	public void setInserttime(Date inserttime) {
		this.inserttime = inserttime;
	}

}