package et.po;

import java.util.Date;

/**
 * CcUserAppraiseInfo generated by MyEclipse Persistence Tools
 */

public class CcUserAppraiseInfo implements java.io.Serializable {

	// Fields

	private Integer id;

	private String callerid;

	private String type;

	private String userAppraise;

	private String appraiseNum;

	private Date appraiseTime;

	private String remark;

	// Constructors

	/** default constructor */
	public CcUserAppraiseInfo() {
	}

	/** full constructor */
	public CcUserAppraiseInfo(String callerid, String type,
			String userAppraise, String appraiseNum, Date appraiseTime,
			String remark) {
		this.callerid = callerid;
		this.type = type;
		this.userAppraise = userAppraise;
		this.appraiseNum = appraiseNum;
		this.appraiseTime = appraiseTime;
		this.remark = remark;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCallerid() {
		return this.callerid;
	}

	public void setCallerid(String callerid) {
		this.callerid = callerid;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getUserAppraise() {
		return this.userAppraise;
	}

	public void setUserAppraise(String userAppraise) {
		this.userAppraise = userAppraise;
	}

	public String getAppraiseNum() {
		return this.appraiseNum;
	}

	public void setAppraiseNum(String appraiseNum) {
		this.appraiseNum = appraiseNum;
	}

	public Date getAppraiseTime() {
		return this.appraiseTime;
	}

	public void setAppraiseTime(Date appraiseTime) {
		this.appraiseTime = appraiseTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}