package et.po;

import java.util.Date;

/**
 * ColumnInfoSendtime generated by MyEclipse Persistence Tools
 */

public class ColumnInfoSendtime implements java.io.Serializable {

	// Fields

	private String id;

	private String columnInfo;

	private Date columnSendtime;

	private String remark;

	// Constructors

	/** default constructor */
	public ColumnInfoSendtime() {
	}

	/** minimal constructor */
	public ColumnInfoSendtime(String id) {
		this.id = id;
	}

	/** full constructor */
	public ColumnInfoSendtime(String id, String columnInfo,
			Date columnSendtime, String remark) {
		this.id = id;
		this.columnInfo = columnInfo;
		this.columnSendtime = columnSendtime;
		this.remark = remark;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getColumnInfo() {
		return this.columnInfo;
	}

	public void setColumnInfo(String columnInfo) {
		this.columnInfo = columnInfo;
	}

	public Date getColumnSendtime() {
		return this.columnSendtime;
	}

	public void setColumnSendtime(Date columnSendtime) {
		this.columnSendtime = columnSendtime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}