package et.po;

import java.util.Date;

/**
 * DbBackup generated by MyEclipse Persistence Tools
 */

public class DbBackup implements java.io.Serializable {

	// Fields

	private String id;

	private String baktype;

	private Date bakdate;

	private String baktime;

	private String remark;

	// Constructors

	/** default constructor */
	public DbBackup() {
	}

	/** minimal constructor */
	public DbBackup(String id) {
		this.id = id;
	}

	/** full constructor */
	public DbBackup(String id, String baktype, Date bakdate, String baktime,
			String remark) {
		this.id = id;
		this.baktype = baktype;
		this.bakdate = bakdate;
		this.baktime = baktime;
		this.remark = remark;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getBaktype() {
		return this.baktype;
	}

	public void setBaktype(String baktype) {
		this.baktype = baktype;
	}

	public Date getBakdate() {
		return this.bakdate;
	}

	public void setBakdate(Date bakdate) {
		this.bakdate = bakdate;
	}

	public String getBaktime() {
		return this.baktime;
	}

	public void setBaktime(String baktime) {
		this.baktime = baktime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}