package et.po;

/**
 * ExpertgroupHotline generated by MyEclipse Persistence Tools
 */

public class ExpertgroupHotline implements java.io.Serializable {

	// Fields

	private String id;

	private String callName;

	private String expertzone;

	private Integer agreelevel;

	private String expertPic;

	private String expertSummary;

	private String type;

	// Constructors

	/** default constructor */
	public ExpertgroupHotline() {
	}

	/** minimal constructor */
	public ExpertgroupHotline(String id) {
		this.id = id;
	}

	/** full constructor */
	public ExpertgroupHotline(String id, String callName, String expertzone,
			Integer agreelevel, String expertPic, String expertSummary,
			String type) {
		this.id = id;
		this.callName = callName;
		this.expertzone = expertzone;
		this.agreelevel = agreelevel;
		this.expertPic = expertPic;
		this.expertSummary = expertSummary;
		this.type = type;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCallName() {
		return this.callName;
	}

	public void setCallName(String callName) {
		this.callName = callName;
	}

	public String getExpertzone() {
		return this.expertzone;
	}

	public void setExpertzone(String expertzone) {
		this.expertzone = expertzone;
	}

	public Integer getAgreelevel() {
		return this.agreelevel;
	}

	public void setAgreelevel(Integer agreelevel) {
		this.agreelevel = agreelevel;
	}

	public String getExpertPic() {
		return this.expertPic;
	}

	public void setExpertPic(String expertPic) {
		this.expertPic = expertPic;
	}

	public String getExpertSummary() {
		return this.expertSummary;
	}

	public void setExpertSummary(String expertSummary) {
		this.expertSummary = expertSummary;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}