package et.po;

import java.util.Date;

/**
 * HandsetNoteInfoReceive generated by MyEclipse Persistence Tools
 */

public class HandsetNoteInfoReceive implements java.io.Serializable {

	// Fields

	private String id;

	private String sendNum;

	private String receiveNum;

	private String content;

	private Date sendTime;

	private String revertId;

	private String businessId;

	private String delSign;

	private String remark;

	// Constructors

	/** default constructor */
	public HandsetNoteInfoReceive() {
	}

	/** minimal constructor */
	public HandsetNoteInfoReceive(String id) {
		this.id = id;
	}

	/** full constructor */
	public HandsetNoteInfoReceive(String id, String sendNum, String receiveNum,
			String content, Date sendTime, String revertId, String businessId,
			String delSign, String remark) {
		this.id = id;
		this.sendNum = sendNum;
		this.receiveNum = receiveNum;
		this.content = content;
		this.sendTime = sendTime;
		this.revertId = revertId;
		this.businessId = businessId;
		this.delSign = delSign;
		this.remark = remark;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSendNum() {
		return this.sendNum;
	}

	public void setSendNum(String sendNum) {
		this.sendNum = sendNum;
	}

	public String getReceiveNum() {
		return this.receiveNum;
	}

	public void setReceiveNum(String receiveNum) {
		this.receiveNum = receiveNum;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	public String getRevertId() {
		return this.revertId;
	}

	public void setRevertId(String revertId) {
		this.revertId = revertId;
	}

	public String getBusinessId() {
		return this.businessId;
	}

	public void setBusinessId(String businessId) {
		this.businessId = businessId;
	}

	public String getDelSign() {
		return this.delSign;
	}

	public void setDelSign(String delSign) {
		this.delSign = delSign;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}