package et.po;

import java.util.Date;

/**
 * HandsetNoteInfoNot generated by MyEclipse Persistence Tools
 */

public class HandsetNoteInfoNot implements java.io.Serializable {

	// Fields

	private String id;

	private HandsetNoteInfo handsetNoteInfo;

	private String receiveNum;

	private String operCount;

	private Date schedularTime;

	private Date operTime;

	private String management;

	private String businessId;

	private String delSign;

	private String sendState;

	private String remark;

	private String columnInfo;

	// Constructors

	/** default constructor */
	public HandsetNoteInfoNot() {
	}

	/** minimal constructor */
	public HandsetNoteInfoNot(String id) {
		this.id = id;
	}

	/** full constructor */
	public HandsetNoteInfoNot(String id, HandsetNoteInfo handsetNoteInfo,
			String receiveNum, String operCount, Date schedularTime,
			Date operTime, String management, String businessId,
			String delSign, String sendState, String remark, String columnInfo) {
		this.id = id;
		this.handsetNoteInfo = handsetNoteInfo;
		this.receiveNum = receiveNum;
		this.operCount = operCount;
		this.schedularTime = schedularTime;
		this.operTime = operTime;
		this.management = management;
		this.businessId = businessId;
		this.delSign = delSign;
		this.sendState = sendState;
		this.remark = remark;
		this.columnInfo = columnInfo;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public HandsetNoteInfo getHandsetNoteInfo() {
		return this.handsetNoteInfo;
	}

	public void setHandsetNoteInfo(HandsetNoteInfo handsetNoteInfo) {
		this.handsetNoteInfo = handsetNoteInfo;
	}

	public String getReceiveNum() {
		return this.receiveNum;
	}

	public void setReceiveNum(String receiveNum) {
		this.receiveNum = receiveNum;
	}

	public String getOperCount() {
		return this.operCount;
	}

	public void setOperCount(String operCount) {
		this.operCount = operCount;
	}

	public Date getSchedularTime() {
		return this.schedularTime;
	}

	public void setSchedularTime(Date schedularTime) {
		this.schedularTime = schedularTime;
	}

	public Date getOperTime() {
		return this.operTime;
	}

	public void setOperTime(Date operTime) {
		this.operTime = operTime;
	}

	public String getManagement() {
		return this.management;
	}

	public void setManagement(String management) {
		this.management = management;
	}

	public String getBusinessId() {
		return this.businessId;
	}

	public void setBusinessId(String businessId) {
		this.businessId = businessId;
	}

	public String getDelSign() {
		return this.delSign;
	}

	public void setDelSign(String delSign) {
		this.delSign = delSign;
	}

	public String getSendState() {
		return this.sendState;
	}

	public void setSendState(String sendState) {
		this.sendState = sendState;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getColumnInfo() {
		return this.columnInfo;
	}

	public void setColumnInfo(String columnInfo) {
		this.columnInfo = columnInfo;
	}

}