package et.po;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HandsetNoteInfo generated by MyEclipse Persistence Tools
 */

public class HandsetNoteInfo implements java.io.Serializable {

	// Fields

	private String id;

	private String sendNum;

	private String sendPerson;

	private Date operTime;

	private String content;

	private String delSign;

	private String remark;

	private Set handsetNoteInfoNots = new HashSet(0);

	private Set handsetNoteInfoAlreadies = new HashSet(0);

	// Constructors

	/** default constructor */
	public HandsetNoteInfo() {
	}

	/** minimal constructor */
	public HandsetNoteInfo(String id) {
		this.id = id;
	}

	/** full constructor */
	public HandsetNoteInfo(String id, String sendNum, String sendPerson,
			Date operTime, String content, String delSign, String remark,
			Set handsetNoteInfoNots, Set handsetNoteInfoAlreadies) {
		this.id = id;
		this.sendNum = sendNum;
		this.sendPerson = sendPerson;
		this.operTime = operTime;
		this.content = content;
		this.delSign = delSign;
		this.remark = remark;
		this.handsetNoteInfoNots = handsetNoteInfoNots;
		this.handsetNoteInfoAlreadies = handsetNoteInfoAlreadies;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSendNum() {
		return this.sendNum;
	}

	public void setSendNum(String sendNum) {
		this.sendNum = sendNum;
	}

	public String getSendPerson() {
		return this.sendPerson;
	}

	public void setSendPerson(String sendPerson) {
		this.sendPerson = sendPerson;
	}

	public Date getOperTime() {
		return this.operTime;
	}

	public void setOperTime(Date operTime) {
		this.operTime = operTime;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getDelSign() {
		return this.delSign;
	}

	public void setDelSign(String delSign) {
		this.delSign = delSign;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set getHandsetNoteInfoNots() {
		return this.handsetNoteInfoNots;
	}

	public void setHandsetNoteInfoNots(Set handsetNoteInfoNots) {
		this.handsetNoteInfoNots = handsetNoteInfoNots;
	}

	public Set getHandsetNoteInfoAlreadies() {
		return this.handsetNoteInfoAlreadies;
	}

	public void setHandsetNoteInfoAlreadies(Set handsetNoteInfoAlreadies) {
		this.handsetNoteInfoAlreadies = handsetNoteInfoAlreadies;
	}

}