package et.po;

/**
 * LinkMan generated by MyEclipse Persistence Tools
 */

public class LinkMan implements java.io.Serializable {

	// Fields

	private String id;

	private LinkGroup linkGroup;

	private String name;

	private String mobile;

	private String sex;

	private String phonenum;

	private String email;

	private String branch;

	private String idcard;

	// Constructors

	/** default constructor */
	public LinkMan() {
	}

	/** minimal constructor */
	public LinkMan(String id, LinkGroup linkGroup) {
		this.id = id;
		this.linkGroup = linkGroup;
	}

	/** full constructor */
	public LinkMan(String id, LinkGroup linkGroup, String name, String mobile,
			String sex, String phonenum, String email, String branch,
			String idcard) {
		this.id = id;
		this.linkGroup = linkGroup;
		this.name = name;
		this.mobile = mobile;
		this.sex = sex;
		this.phonenum = phonenum;
		this.email = email;
		this.branch = branch;
		this.idcard = idcard;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public LinkGroup getLinkGroup() {
		return this.linkGroup;
	}

	public void setLinkGroup(LinkGroup linkGroup) {
		this.linkGroup = linkGroup;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getPhonenum() {
		return this.phonenum;
	}

	public void setPhonenum(String phonenum) {
		this.phonenum = phonenum;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getBranch() {
		return this.branch;
	}

	public void setBranch(String branch) {
		this.branch = branch;
	}

	public String getIdcard() {
		return this.idcard;
	}

	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

}