package et.po;

import java.util.Date;

/**
 * OperMedicinfo generated by MyEclipse Persistence Tools
 */

public class OperMedicinfo implements java.io.Serializable {

	// Fields

	private String id;

	private String medicRid;

	private String expert;

	private Date createTime;

	private String custName;

	private String custTel;

	private String dictSex;

	private String custAddr;

	private String state;

	private String isParter;

	private String contents;

	private String reply;

	private String traceService;

	private String remark;

	private String expertName;

	// Constructors

	/** default constructor */
	public OperMedicinfo() {
	}

	/** minimal constructor */
	public OperMedicinfo(String id) {
		this.id = id;
	}

	/** full constructor */
	public OperMedicinfo(String id, String medicRid, String expert,
			Date createTime, String custName, String custTel, String dictSex,
			String custAddr, String state, String isParter, String contents,
			String reply, String traceService, String remark, String expertName) {
		this.id = id;
		this.medicRid = medicRid;
		this.expert = expert;
		this.createTime = createTime;
		this.custName = custName;
		this.custTel = custTel;
		this.dictSex = dictSex;
		this.custAddr = custAddr;
		this.state = state;
		this.isParter = isParter;
		this.contents = contents;
		this.reply = reply;
		this.traceService = traceService;
		this.remark = remark;
		this.expertName = expertName;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMedicRid() {
		return this.medicRid;
	}

	public void setMedicRid(String medicRid) {
		this.medicRid = medicRid;
	}

	public String getExpert() {
		return this.expert;
	}

	public void setExpert(String expert) {
		this.expert = expert;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	public String getCustTel() {
		return this.custTel;
	}

	public void setCustTel(String custTel) {
		this.custTel = custTel;
	}

	public String getDictSex() {
		return this.dictSex;
	}

	public void setDictSex(String dictSex) {
		this.dictSex = dictSex;
	}

	public String getCustAddr() {
		return this.custAddr;
	}

	public void setCustAddr(String custAddr) {
		this.custAddr = custAddr;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getIsParter() {
		return this.isParter;
	}

	public void setIsParter(String isParter) {
		this.isParter = isParter;
	}

	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	public String getReply() {
		return this.reply;
	}

	public void setReply(String reply) {
		this.reply = reply;
	}

	public String getTraceService() {
		return this.traceService;
	}

	public void setTraceService(String traceService) {
		this.traceService = traceService;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getExpertName() {
		return this.expertName;
	}

	public void setExpertName(String expertName) {
		this.expertName = expertName;
	}

}