package et.po;

/**
 * OperHotline generated by MyEclipse Persistence Tools
 */

public class OperHotline implements java.io.Serializable {

	// Fields

	private String id;

	private String hotlineContent;

	// Constructors

	/** default constructor */
	public OperHotline() {
	}

	/** minimal constructor */
	public OperHotline(String id) {
		this.id = id;
	}

	/** full constructor */
	public OperHotline(String id, String hotlineContent) {
		this.id = id;
		this.hotlineContent = hotlineContent;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getHotlineContent() {
		return this.hotlineContent;
	}

	public void setHotlineContent(String hotlineContent) {
		this.hotlineContent = hotlineContent;
	}

}