package et.po;

import java.util.Date;

/**
 * OperInquiryCard generated by MyEclipse Persistence Tools
 */

public class OperInquiryCard implements java.io.Serializable {

	// Fields

	private String id;

	private OperInquiryinfo operInquiryinfo;

	private String question;

	private String dictQuestionType;

	private Integer displayOrder;

	private Date createTime;

	private String alternatives;

	private String remark;

	// Constructors

	/** default constructor */
	public OperInquiryCard() {
	}

	/** minimal constructor */
	public OperInquiryCard(String id, OperInquiryinfo operInquiryinfo) {
		this.id = id;
		this.operInquiryinfo = operInquiryinfo;
	}

	/** full constructor */
	public OperInquiryCard(String id, OperInquiryinfo operInquiryinfo,
			String question, String dictQuestionType, Integer displayOrder,
			Date createTime, String alternatives, String remark) {
		this.id = id;
		this.operInquiryinfo = operInquiryinfo;
		this.question = question;
		this.dictQuestionType = dictQuestionType;
		this.displayOrder = displayOrder;
		this.createTime = createTime;
		this.alternatives = alternatives;
		this.remark = remark;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public OperInquiryinfo getOperInquiryinfo() {
		return this.operInquiryinfo;
	}

	public void setOperInquiryinfo(OperInquiryinfo operInquiryinfo) {
		this.operInquiryinfo = operInquiryinfo;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getDictQuestionType() {
		return this.dictQuestionType;
	}

	public void setDictQuestionType(String dictQuestionType) {
		this.dictQuestionType = dictQuestionType;
	}

	public Integer getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Integer displayOrder) {
		this.displayOrder = displayOrder;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getAlternatives() {
		return this.alternatives;
	}

	public void setAlternatives(String alternatives) {
		this.alternatives = alternatives;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	/*public int compareTo(OperInquiryCard arg0) {
		
		if (this.displayOrder > arg0.getDisplayOrder())
			return 1;
		else if (this.displayOrder < arg0.getDisplayOrder())
			return -1;
		else
			return 0;
	}*/

}