package et.po;

import java.util.Date;

/**
 * OperCallback generated by MyEclipse Persistence Tools
 */

public class OperCallback implements java.io.Serializable {

	// Fields

	private String id;

	private OperQuestion operQuestion;

	private Date callbackTime;

	private String callbackContent;

	private String isCallbackSucc;

	private String isDelete;

	private String remark;

	// Constructors

	/** default constructor */
	public OperCallback() {
	}

	/** minimal constructor */
	public OperCallback(String id) {
		this.id = id;
	}

	/** full constructor */
	public OperCallback(String id, OperQuestion operQuestion,
			Date callbackTime, String callbackContent, String isCallbackSucc,
			String isDelete, String remark) {
		this.id = id;
		this.operQuestion = operQuestion;
		this.callbackTime = callbackTime;
		this.callbackContent = callbackContent;
		this.isCallbackSucc = isCallbackSucc;
		this.isDelete = isDelete;
		this.remark = remark;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public OperQuestion getOperQuestion() {
		return this.operQuestion;
	}

	public void setOperQuestion(OperQuestion operQuestion) {
		this.operQuestion = operQuestion;
	}

	public Date getCallbackTime() {
		return this.callbackTime;
	}

	public void setCallbackTime(Date callbackTime) {
		this.callbackTime = callbackTime;
	}

	public String getCallbackContent() {
		return this.callbackContent;
	}

	public void setCallbackContent(String callbackContent) {
		this.callbackContent = callbackContent;
	}

	public String getIsCallbackSucc() {
		return this.isCallbackSucc;
	}

	public void setIsCallbackSucc(String isCallbackSucc) {
		this.isCallbackSucc = isCallbackSucc;
	}

	public String getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}