package et.po;

import java.util.Date;

/**
 * OperBookMedicinfo generated by MyEclipse Persistence Tools
 */

public class OperBookMedicinfo implements java.io.Serializable {

	// Fields

	private String id;

	private String bookRid;

	private String expert;

	private Date createTime;

	private String custName;

	private String dictSex;

	private String custTel;

	private String custAddr;

	private String state;

	private String isParter;

	private String contents;

	private String reply;

	private String dictServiceType;

	private String isVisit;

	private Date bookVisitTime;

	private Date visitTime;

	private String hospitalAdvice;

	private String navigator;

	private String bed;

	private String items;

	private String charge;

	private String favours;

	private String visitResult;

	private String traceService;

	private String remark;

	private String expertSort;

	// Constructors

	/** default constructor */
	public OperBookMedicinfo() {
	}

	/** minimal constructor */
	public OperBookMedicinfo(String id) {
		this.id = id;
	}

	/** full constructor */
	public OperBookMedicinfo(String id, String bookRid, String expert,
			Date createTime, String custName, String dictSex, String custTel,
			String custAddr, String state, String isParter, String contents,
			String reply, String dictServiceType, String isVisit,
			Date bookVisitTime, Date visitTime, String hospitalAdvice,
			String navigator, String bed, String items, String charge,
			String favours, String visitResult, String traceService,
			String remark, String expertSort) {
		this.id = id;
		this.bookRid = bookRid;
		this.expert = expert;
		this.createTime = createTime;
		this.custName = custName;
		this.dictSex = dictSex;
		this.custTel = custTel;
		this.custAddr = custAddr;
		this.state = state;
		this.isParter = isParter;
		this.contents = contents;
		this.reply = reply;
		this.dictServiceType = dictServiceType;
		this.isVisit = isVisit;
		this.bookVisitTime = bookVisitTime;
		this.visitTime = visitTime;
		this.hospitalAdvice = hospitalAdvice;
		this.navigator = navigator;
		this.bed = bed;
		this.items = items;
		this.charge = charge;
		this.favours = favours;
		this.visitResult = visitResult;
		this.traceService = traceService;
		this.remark = remark;
		this.expertSort = expertSort;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getBookRid() {
		return this.bookRid;
	}

	public void setBookRid(String bookRid) {
		this.bookRid = bookRid;
	}

	public String getExpert() {
		return this.expert;
	}

	public void setExpert(String expert) {
		this.expert = expert;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	public String getDictSex() {
		return this.dictSex;
	}

	public void setDictSex(String dictSex) {
		this.dictSex = dictSex;
	}

	public String getCustTel() {
		return this.custTel;
	}

	public void setCustTel(String custTel) {
		this.custTel = custTel;
	}

	public String getCustAddr() {
		return this.custAddr;
	}

	public void setCustAddr(String custAddr) {
		this.custAddr = custAddr;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getIsParter() {
		return this.isParter;
	}

	public void setIsParter(String isParter) {
		this.isParter = isParter;
	}

	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	public String getReply() {
		return this.reply;
	}

	public void setReply(String reply) {
		this.reply = reply;
	}

	public String getDictServiceType() {
		return this.dictServiceType;
	}

	public void setDictServiceType(String dictServiceType) {
		this.dictServiceType = dictServiceType;
	}

	public String getIsVisit() {
		return this.isVisit;
	}

	public void setIsVisit(String isVisit) {
		this.isVisit = isVisit;
	}

	public Date getBookVisitTime() {
		return this.bookVisitTime;
	}

	public void setBookVisitTime(Date bookVisitTime) {
		this.bookVisitTime = bookVisitTime;
	}

	public Date getVisitTime() {
		return this.visitTime;
	}

	public void setVisitTime(Date visitTime) {
		this.visitTime = visitTime;
	}

	public String getHospitalAdvice() {
		return this.hospitalAdvice;
	}

	public void setHospitalAdvice(String hospitalAdvice) {
		this.hospitalAdvice = hospitalAdvice;
	}

	public String getNavigator() {
		return this.navigator;
	}

	public void setNavigator(String navigator) {
		this.navigator = navigator;
	}

	public String getBed() {
		return this.bed;
	}

	public void setBed(String bed) {
		this.bed = bed;
	}

	public String getItems() {
		return this.items;
	}

	public void setItems(String items) {
		this.items = items;
	}

	public String getCharge() {
		return this.charge;
	}

	public void setCharge(String charge) {
		this.charge = charge;
	}

	public String getFavours() {
		return this.favours;
	}

	public void setFavours(String favours) {
		this.favours = favours;
	}

	public String getVisitResult() {
		return this.visitResult;
	}

	public void setVisitResult(String visitResult) {
		this.visitResult = visitResult;
	}

	public String getTraceService() {
		return this.traceService;
	}

	public void setTraceService(String traceService) {
		this.traceService = traceService;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getExpertSort() {
		return this.expertSort;
	}

	public void setExpertSort(String expertSort) {
		this.expertSort = expertSort;
	}

}