package et.po;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OperQuestion generated by MyEclipse Persistence Tools
 */

public class OperQuestion implements java.io.Serializable {

	// Fields

	private String id;

	private OperCustinfo operCustinfo;

	private String talkId;

	private String custTel;

	private String rid;

	private String billNum;

	private String expertName;

	private String dictQuestionType1;

	private String dictQuestionType2;

	private String dictQuestionType3;

	private String dictQuestionType4;

	private String questionContent;

	private String answerContent;

	private String dictIsAnswerSucceed;

	private String answerMan;

	private String dictIsCallback;

	private Date callbackTime;

	private String callbackMan;

	private String callbackPhone;

	private String isCallbackSucc;

	private String dictIsRepository;

	private String dictQuestionScore;

	private String isOut;

	private String isDelete;

	private String remark;

	private Date addtime;

	private Date ringBegintime;

	private String answerAgent;

	private Set operCallbacks = new HashSet(0);

	// Constructors

	/** default constructor */
	public OperQuestion() {
	}

	/** minimal constructor */
	public OperQuestion(String id) {
		this.id = id;
	}

	/** full constructor */
	public OperQuestion(String id, OperCustinfo operCustinfo, String talkId, String custTel, String rid, String billNum, String expertName, String dictQuestionType1, String dictQuestionType2,
			String dictQuestionType3, String dictQuestionType4, String questionContent, String answerContent, String dictIsAnswerSucceed, String answerMan, String dictIsCallback, Date callbackTime,
			String callbackMan, String callbackPhone, String isCallbackSucc, String dictIsRepository, String dictQuestionScore, String isOut, String isDelete, String remark, Date addtime,
			Date ringBegintime, String answerAgent, Set operCallbacks) {
		this.id = id;
		this.operCustinfo = operCustinfo;
		this.talkId = talkId;
		this.custTel = custTel;
		this.rid = rid;
		this.billNum = billNum;
		this.expertName = expertName;
		this.dictQuestionType1 = dictQuestionType1;
		this.dictQuestionType2 = dictQuestionType2;
		this.dictQuestionType3 = dictQuestionType3;
		this.dictQuestionType4 = dictQuestionType4;
		this.questionContent = questionContent;
		this.answerContent = answerContent;
		this.dictIsAnswerSucceed = dictIsAnswerSucceed;
		this.answerMan = answerMan;
		this.dictIsCallback = dictIsCallback;
		this.callbackTime = callbackTime;
		this.callbackMan = callbackMan;
		this.callbackPhone = callbackPhone;
		this.isCallbackSucc = isCallbackSucc;
		this.dictIsRepository = dictIsRepository;
		this.dictQuestionScore = dictQuestionScore;
		this.isOut = isOut;
		this.isDelete = isDelete;
		this.remark = remark;
		this.addtime = addtime;
		this.ringBegintime = ringBegintime;
		this.answerAgent = answerAgent;
		this.operCallbacks = operCallbacks;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public OperCustinfo getOperCustinfo() {
		return this.operCustinfo;
	}

	public void setOperCustinfo(OperCustinfo operCustinfo) {
		this.operCustinfo = operCustinfo;
	}

	public String getTalkId() {
		return this.talkId;
	}

	public void setTalkId(String talkId) {
		this.talkId = talkId;
	}

	public String getCustTel() {
		return this.custTel;
	}

	public void setCustTel(String custTel) {
		this.custTel = custTel;
	}

	public String getRid() {
		return this.rid;
	}

	public void setRid(String rid) {
		this.rid = rid;
	}

	public String getBillNum() {
		return this.billNum;
	}

	public void setBillNum(String billNum) {
		this.billNum = billNum;
	}

	public String getExpertName() {
		return this.expertName;
	}

	public void setExpertName(String expertName) {
		this.expertName = expertName;
	}

	public String getDictQuestionType1() {
		return this.dictQuestionType1;
	}

	public void setDictQuestionType1(String dictQuestionType1) {
		this.dictQuestionType1 = dictQuestionType1;
	}

	public String getDictQuestionType2() {
		return this.dictQuestionType2;
	}

	public void setDictQuestionType2(String dictQuestionType2) {
		this.dictQuestionType2 = dictQuestionType2;
	}

	public String getDictQuestionType3() {
		return this.dictQuestionType3;
	}

	public void setDictQuestionType3(String dictQuestionType3) {
		this.dictQuestionType3 = dictQuestionType3;
	}

	public String getDictQuestionType4() {
		return this.dictQuestionType4;
	}

	public void setDictQuestionType4(String dictQuestionType4) {
		this.dictQuestionType4 = dictQuestionType4;
	}

	public String getQuestionContent() {
		return this.questionContent;
	}

	public void setQuestionContent(String questionContent) {
		this.questionContent = questionContent;
	}

	public String getAnswerContent() {
		return this.answerContent;
	}

	public void setAnswerContent(String answerContent) {
		this.answerContent = answerContent;
	}

	public String getDictIsAnswerSucceed() {
		return this.dictIsAnswerSucceed;
	}

	public void setDictIsAnswerSucceed(String dictIsAnswerSucceed) {
		this.dictIsAnswerSucceed = dictIsAnswerSucceed;
	}

	public String getAnswerMan() {
		return this.answerMan;
	}

	public void setAnswerMan(String answerMan) {
		this.answerMan = answerMan;
	}

	public String getDictIsCallback() {
		return this.dictIsCallback;
	}

	public void setDictIsCallback(String dictIsCallback) {
		this.dictIsCallback = dictIsCallback;
	}

	public Date getCallbackTime() {
		return this.callbackTime;
	}

	public void setCallbackTime(Date callbackTime) {
		this.callbackTime = callbackTime;
	}

	public String getCallbackMan() {
		return this.callbackMan;
	}

	public void setCallbackMan(String callbackMan) {
		this.callbackMan = callbackMan;
	}

	public String getCallbackPhone() {
		return this.callbackPhone;
	}

	public void setCallbackPhone(String callbackPhone) {
		this.callbackPhone = callbackPhone;
	}

	public String getIsCallbackSucc() {
		return this.isCallbackSucc;
	}

	public void setIsCallbackSucc(String isCallbackSucc) {
		this.isCallbackSucc = isCallbackSucc;
	}

	public String getDictIsRepository() {
		return this.dictIsRepository;
	}

	public void setDictIsRepository(String dictIsRepository) {
		this.dictIsRepository = dictIsRepository;
	}

	public String getDictQuestionScore() {
		return this.dictQuestionScore;
	}

	public void setDictQuestionScore(String dictQuestionScore) {
		this.dictQuestionScore = dictQuestionScore;
	}

	public String getIsOut() {
		return this.isOut;
	}

	public void setIsOut(String isOut) {
		this.isOut = isOut;
	}

	public String getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getAddtime() {
		return this.addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	public Date getRingBegintime() {
		return this.ringBegintime;
	}

	public void setRingBegintime(Date ringBegintime) {
		this.ringBegintime = ringBegintime;
	}

	public String getAnswerAgent() {
		return this.answerAgent;
	}

	public void setAnswerAgent(String answerAgent) {
		this.answerAgent = answerAgent;
	}

	public Set getOperCallbacks() {
		return this.operCallbacks;
	}

	public void setOperCallbacks(Set operCallbacks) {
		this.operCallbacks = operCallbacks;
	}

}