package et.po;

import java.util.Date;

/**
 * OperPriceinfo generated by MyEclipse Persistence Tools
 */

public class OperPriceinfo implements java.io.Serializable {

	// Fields

	private String priceId;

	private OperCustinfo operCustinfo;

	private String priceRid;

	private String priceExpert;

	private Date operTime;

	private String custName;

	private String custAddr;

	private String custTel;

	private String state;

	private String dictPriceType;

	private String dictProductType1;

	private String dictProductType2;

	private String productName;

	private String productScale;

	private String productPrice;

	private String priceUnit;

	private Date deployTime;

	private String remark;

	private String questionId;

	private Date addtime;
	
	private String custNumber;
	
	private String custType;

	// Constructors

	/** default constructor */
	public OperPriceinfo() {
	}

	/** minimal constructor */
	public OperPriceinfo(String priceId) {
		this.priceId = priceId;
	}

	/** full constructor */
	public OperPriceinfo(String priceId, OperCustinfo operCustinfo, String priceRid, String priceExpert, Date operTime, String custName, String custAddr, String custTel, String state,
			String dictPriceType, String dictProductType1, String dictProductType2, String productName, String productScale, String productPrice, String priceUnit, Date deployTime, String remark,
			String questionId, Date addtime, String custNumber, String custType) {
		this.priceId = priceId;
		this.operCustinfo = operCustinfo;
		this.priceRid = priceRid;
		this.priceExpert = priceExpert;
		this.operTime = operTime;
		this.custName = custName;
		this.custAddr = custAddr;
		this.custTel = custTel;
		this.state = state;
		this.dictPriceType = dictPriceType;
		this.dictProductType1 = dictProductType1;
		this.dictProductType2 = dictProductType2;
		this.productName = productName;
		this.productScale = productScale;
		this.productPrice = productPrice;
		this.priceUnit = priceUnit;
		this.deployTime = deployTime;
		this.remark = remark;
		this.questionId = questionId;
		this.addtime = addtime;
		this.custNumber = custNumber;
		this.custType = custType;
	}

	// Property accessors

	public String getPriceId() {
		return this.priceId;
	}

	public void setPriceId(String priceId) {
		this.priceId = priceId;
	}

	public OperCustinfo getOperCustinfo() {
		return this.operCustinfo;
	}

	public void setOperCustinfo(OperCustinfo operCustinfo) {
		this.operCustinfo = operCustinfo;
	}

	public String getPriceRid() {
		return this.priceRid;
	}

	public void setPriceRid(String priceRid) {
		this.priceRid = priceRid;
	}

	public String getPriceExpert() {
		return this.priceExpert;
	}

	public void setPriceExpert(String priceExpert) {
		this.priceExpert = priceExpert;
	}

	public Date getOperTime() {
		return this.operTime;
	}

	public void setOperTime(Date operTime) {
		this.operTime = operTime;
	}

	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	public String getCustAddr() {
		return this.custAddr;
	}

	public void setCustAddr(String custAddr) {
		this.custAddr = custAddr;
	}

	public String getCustTel() {
		return this.custTel;
	}

	public void setCustTel(String custTel) {
		this.custTel = custTel;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getDictPriceType() {
		return this.dictPriceType;
	}

	public void setDictPriceType(String dictPriceType) {
		this.dictPriceType = dictPriceType;
	}

	public String getDictProductType1() {
		return this.dictProductType1;
	}

	public void setDictProductType1(String dictProductType1) {
		this.dictProductType1 = dictProductType1;
	}

	public String getDictProductType2() {
		return this.dictProductType2;
	}

	public void setDictProductType2(String dictProductType2) {
		this.dictProductType2 = dictProductType2;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductScale() {
		return this.productScale;
	}

	public void setProductScale(String productScale) {
		this.productScale = productScale;
	}

	public String getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(String productPrice) {
		this.productPrice = productPrice;
	}

	public String getPriceUnit() {
		return this.priceUnit;
	}

	public void setPriceUnit(String priceUnit) {
		this.priceUnit = priceUnit;
	}

	public Date getDeployTime() {
		return this.deployTime;
	}

	public void setDeployTime(Date deployTime) {
		this.deployTime = deployTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(String questionId) {
		this.questionId = questionId;
	}

	public Date getAddtime() {
		return this.addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	public String getCustNumber() {
		return custNumber;
	}

	public void setCustNumber(String custNumber) {
		this.custNumber = custNumber;
	}

	public String getCustType() {
		return custType;
	}

	public void setCustType(String custType) {
		this.custType = custType;
	}

}