package et.po;

import java.util.Date;

/**
 * OperMessages generated by MyEclipse Persistence Tools
 */

public class OperMessages implements java.io.Serializable {

	// Fields

	private String messageId;

	private String sendId;

	private String sendName;

	private String receiveId;

	private String messageContent;

	private Date sendTime;

	private String dictReadFlag;

	// Constructors

	/** default constructor */
	public OperMessages() {
	}

	/** minimal constructor */
	public OperMessages(String messageId) {
		this.messageId = messageId;
	}

	/** full constructor */
	public OperMessages(String messageId, String sendId, String sendName,
			String receiveId, String messageContent, Date sendTime,
			String dictReadFlag) {
		this.messageId = messageId;
		this.sendId = sendId;
		this.sendName = sendName;
		this.receiveId = receiveId;
		this.messageContent = messageContent;
		this.sendTime = sendTime;
		this.dictReadFlag = dictReadFlag;
	}

	// Property accessors

	public String getMessageId() {
		return this.messageId;
	}

	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	public String getSendId() {
		return this.sendId;
	}

	public void setSendId(String sendId) {
		this.sendId = sendId;
	}

	public String getSendName() {
		return this.sendName;
	}

	public void setSendName(String sendName) {
		this.sendName = sendName;
	}

	public String getReceiveId() {
		return this.receiveId;
	}

	public void setReceiveId(String receiveId) {
		this.receiveId = receiveId;
	}

	public String getMessageContent() {
		return this.messageContent;
	}

	public void setMessageContent(String messageContent) {
		this.messageContent = messageContent;
	}

	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	public String getDictReadFlag() {
		return this.dictReadFlag;
	}

	public void setDictReadFlag(String dictReadFlag) {
		this.dictReadFlag = dictReadFlag;
	}

}