package et.po;

import java.util.Date;

/**
 * OperFlow generated by MyEclipse Persistence Tools
 */

public class OperFlow implements java.io.Serializable {

	// Fields

	private String flowId;

	private String type;

	private String power;

	private String submitId;

	private String submitIdEnd;

	private Date submitTime;

	private Date submitTimeEnd;

	private String state;

	private String isRead;

	// Constructors

	/** default constructor */
	public OperFlow() {
	}

	/** minimal constructor */
	public OperFlow(String flowId) {
		this.flowId = flowId;
	}

	/** full constructor */
	public OperFlow(String flowId, String type, String power, String submitId, String submitIdEnd, Date submitTime, Date submitTimeEnd, String state, String isRead) {
		this.flowId = flowId;
		this.type = type;
		this.power = power;
		this.submitId = submitId;
		this.submitIdEnd = submitIdEnd;
		this.submitTime = submitTime;
		this.submitTimeEnd = submitTimeEnd;
		this.state = state;
		this.isRead = isRead;
	}

	// Property accessors

	public String getFlowId() {
		return this.flowId;
	}

	public void setFlowId(String flowId) {
		this.flowId = flowId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getPower() {
		return this.power;
	}

	public void setPower(String power) {
		this.power = power;
	}

	public String getSubmitId() {
		return this.submitId;
	}

	public void setSubmitId(String submitId) {
		this.submitId = submitId;
	}

	public String getSubmitIdEnd() {
		return this.submitIdEnd;
	}

	public void setSubmitIdEnd(String submitIdEnd) {
		this.submitIdEnd = submitIdEnd;
	}

	public Date getSubmitTime() {
		return this.submitTime;
	}

	public void setSubmitTime(Date submitTime) {
		this.submitTime = submitTime;
	}

	public Date getSubmitTimeEnd() {
		return this.submitTimeEnd;
	}

	public void setSubmitTimeEnd(Date submitTimeEnd) {
		this.submitTimeEnd = submitTimeEnd;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getIsRead() {
		return this.isRead;
	}

	public void setIsRead(String isRead) {
		this.isRead = isRead;
	}

}