package et.po;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OperCustinfo generated by MyEclipse Persistence Tools
 */

public class OperCustinfo implements java.io.Serializable {

	// Fields

	private String custId;

	private String custName;

	private String custAddr;

	private String dictSex;

	private String custTelHome;

	private String custTelWork;

	private String custTelMob;

	private String custFax;

	private String custPcode;

	private String custEmail;

	private String dictCustVoc;

	private String dictCustScale;

	private String dictCustType;

	private String isDelete;

	private String custIdentityCard;

	private Date custDevelopTime;

	private Date custPositiveTime;

	private String expertType;

	private String expertNum;

	private String custPicName;

	private String custPicPath;

	private String custRid;

	private String custAge;

	private String custDegree;

	private String custUnit;

	private String custDuty;

	private String custHomepage;

	private String workItem;

	private String custIntru;

	private String custBanner;

	private String custWayBy;

	private String custLinkmanName;

	private String custLinkmanDuty;

	private String custJob;

	private String remark;

	private String custRole;

	private String custNature;

	private String enterpriseIntru;

	private String enterpriseNet;

	private String custServerName;

	private String uploadfile;

	private Date addtime;
	
	private Date modifyTime;
	
	private String screenExpertType;
	
	private String custNumber;
	
	private String custWorkWay;
	
	private String isEliminate;
	
	private String eliminateReason;

	private Set operSadinfos = new HashSet(0);

	private Set operPriceinfos = new HashSet(0);

	private Set operQuestions = new HashSet(0);

	// Constructors

	/** default constructor */
	public OperCustinfo() {
	}

	/** full constructor */
	public OperCustinfo(String custName, String custAddr, String dictSex,
			String custTelHome, String custTelWork, String custTelMob,
			String custFax, String custPcode, String custEmail,
			String dictCustVoc, String dictCustScale, String dictCustType,
			String isDelete, String custIdentityCard, Date custDevelopTime,
			Date custPositiveTime, String expertType, String expertNum,
			String custPicName, String custPicPath, String custRid,
			String custAge, String custDegree, String custUnit,
			String custDuty, String custHomepage, String workItem,
			String custIntru, String custBanner, String custWayBy,
			String custLinkmanName, String custLinkmanDuty, String custJob,
			String remark, String custRole, String custNature,
			String enterpriseIntru, String enterpriseNet,
			String custServerName, String uploadfile, Date addtime,
			String screenExpertType, String custNumber,
			String custWorkWay, String isEliminate, String eliminateReason,
			Set operSadinfos, Set operPriceinfos,
			Set operQuestions,Date modifyTime) {
		this.custName = custName;
		this.custAddr = custAddr;
		this.dictSex = dictSex;
		this.custTelHome = custTelHome;
		this.custTelWork = custTelWork;
		this.custTelMob = custTelMob;
		this.custFax = custFax;
		this.custPcode = custPcode;
		this.custEmail = custEmail;
		this.dictCustVoc = dictCustVoc;
		this.dictCustScale = dictCustScale;
		this.dictCustType = dictCustType;
		this.isDelete = isDelete;
		this.custIdentityCard = custIdentityCard;
		this.custDevelopTime = custDevelopTime;
		this.custPositiveTime = custPositiveTime;
		this.expertType = expertType;
		this.expertNum = expertNum;
		this.custPicName = custPicName;
		this.custPicPath = custPicPath;
		this.custRid = custRid;
		this.custAge = custAge;
		this.custDegree = custDegree;
		this.custUnit = custUnit;
		this.custDuty = custDuty;
		this.custHomepage = custHomepage;
		this.workItem = workItem;
		this.custIntru = custIntru;
		this.custBanner = custBanner;
		this.custWayBy = custWayBy;
		this.custLinkmanName = custLinkmanName;
		this.custLinkmanDuty = custLinkmanDuty;
		this.custJob = custJob;
		this.remark = remark;
		this.custRole = custRole;
		this.custNature = custNature;
		this.enterpriseIntru = enterpriseIntru;
		this.enterpriseNet = enterpriseNet;
		this.custServerName = custServerName;
		this.uploadfile = uploadfile;
		this.addtime = addtime;
		this.screenExpertType = screenExpertType;
		this.custNumber = custNumber;
		this.custWorkWay = custWorkWay;
		this.isEliminate = isEliminate;
		this.eliminateReason = eliminateReason;
		this.operSadinfos = operSadinfos;
		this.operPriceinfos = operPriceinfos;
		this.operQuestions = operQuestions;
		this.modifyTime = modifyTime;
	}

	// Property accessors
	
	public String getCustId() {
		return this.custId;
	}

	public void setCustId(String custId) {
		this.custId = custId;
	}

	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	public String getCustAddr() {
		return this.custAddr;
	}

	public void setCustAddr(String custAddr) {
		this.custAddr = custAddr;
	}

	public String getDictSex() {
		return this.dictSex;
	}

	public void setDictSex(String dictSex) {
		this.dictSex = dictSex;
	}

	public String getCustTelHome() {
		return this.custTelHome;
	}

	public void setCustTelHome(String custTelHome) {
		this.custTelHome = custTelHome;
	}

	public String getCustTelWork() {
		return this.custTelWork;
	}

	public void setCustTelWork(String custTelWork) {
		this.custTelWork = custTelWork;
	}

	public String getCustTelMob() {
		return this.custTelMob;
	}

	public void setCustTelMob(String custTelMob) {
		this.custTelMob = custTelMob;
	}

	public String getCustFax() {
		return this.custFax;
	}

	public void setCustFax(String custFax) {
		this.custFax = custFax;
	}

	public String getCustPcode() {
		return this.custPcode;
	}

	public void setCustPcode(String custPcode) {
		this.custPcode = custPcode;
	}

	public String getCustEmail() {
		return this.custEmail;
	}

	public void setCustEmail(String custEmail) {
		this.custEmail = custEmail;
	}

	public String getDictCustVoc() {
		return this.dictCustVoc;
	}

	public void setDictCustVoc(String dictCustVoc) {
		this.dictCustVoc = dictCustVoc;
	}

	public String getDictCustScale() {
		return this.dictCustScale;
	}

	public void setDictCustScale(String dictCustScale) {
		this.dictCustScale = dictCustScale;
	}

	public String getDictCustType() {
		return this.dictCustType;
	}

	public void setDictCustType(String dictCustType) {
		this.dictCustType = dictCustType;
	}

	public String getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete;
	}

	public String getCustIdentityCard() {
		return this.custIdentityCard;
	}

	public void setCustIdentityCard(String custIdentityCard) {
		this.custIdentityCard = custIdentityCard;
	}

	public Date getCustDevelopTime() {
		return this.custDevelopTime;
	}

	public void setCustDevelopTime(Date custDevelopTime) {
		this.custDevelopTime = custDevelopTime;
	}

	public Date getCustPositiveTime() {
		return this.custPositiveTime;
	}

	public void setCustPositiveTime(Date custPositiveTime) {
		this.custPositiveTime = custPositiveTime;
	}

	public String getExpertType() {
		return this.expertType;
	}

	public void setExpertType(String expertType) {
		this.expertType = expertType;
	}

	public String getExpertNum() {
		return this.expertNum;
	}

	public void setExpertNum(String expertNum) {
		this.expertNum = expertNum;
	}

	public String getCustPicName() {
		return this.custPicName;
	}

	public void setCustPicName(String custPicName) {
		this.custPicName = custPicName;
	}

	public String getCustPicPath() {
		return this.custPicPath;
	}

	public void setCustPicPath(String custPicPath) {
		this.custPicPath = custPicPath;
	}

	public String getCustRid() {
		return this.custRid;
	}

	public void setCustRid(String custRid) {
		this.custRid = custRid;
	}

	public String getCustAge() {
		return this.custAge;
	}

	public void setCustAge(String custAge) {
		this.custAge = custAge;
	}

	public String getCustDegree() {
		return this.custDegree;
	}

	public void setCustDegree(String custDegree) {
		this.custDegree = custDegree;
	}

	public String getCustUnit() {
		return this.custUnit;
	}

	public void setCustUnit(String custUnit) {
		this.custUnit = custUnit;
	}

	public String getCustDuty() {
		return this.custDuty;
	}

	public void setCustDuty(String custDuty) {
		this.custDuty = custDuty;
	}

	public String getCustHomepage() {
		return this.custHomepage;
	}

	public void setCustHomepage(String custHomepage) {
		this.custHomepage = custHomepage;
	}

	public String getWorkItem() {
		return this.workItem;
	}

	public void setWorkItem(String workItem) {
		this.workItem = workItem;
	}

	public String getCustIntru() {
		return this.custIntru;
	}

	public void setCustIntru(String custIntru) {
		this.custIntru = custIntru;
	}

	public String getCustBanner() {
		return this.custBanner;
	}

	public void setCustBanner(String custBanner) {
		this.custBanner = custBanner;
	}

	public String getCustWayBy() {
		return this.custWayBy;
	}

	public void setCustWayBy(String custWayBy) {
		this.custWayBy = custWayBy;
	}

	public String getCustLinkmanName() {
		return this.custLinkmanName;
	}

	public void setCustLinkmanName(String custLinkmanName) {
		this.custLinkmanName = custLinkmanName;
	}

	public String getCustLinkmanDuty() {
		return this.custLinkmanDuty;
	}

	public void setCustLinkmanDuty(String custLinkmanDuty) {
		this.custLinkmanDuty = custLinkmanDuty;
	}

	public String getCustJob() {
		return this.custJob;
	}

	public void setCustJob(String custJob) {
		this.custJob = custJob;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getCustRole() {
		return this.custRole;
	}

	public void setCustRole(String custRole) {
		this.custRole = custRole;
	}

	public String getCustNature() {
		return this.custNature;
	}

	public void setCustNature(String custNature) {
		this.custNature = custNature;
	}

	public String getEnterpriseIntru() {
		return this.enterpriseIntru;
	}

	public void setEnterpriseIntru(String enterpriseIntru) {
		this.enterpriseIntru = enterpriseIntru;
	}

	public String getEnterpriseNet() {
		return this.enterpriseNet;
	}

	public void setEnterpriseNet(String enterpriseNet) {
		this.enterpriseNet = enterpriseNet;
	}

	public String getCustServerName() {
		return this.custServerName;
	}

	public void setCustServerName(String custServerName) {
		this.custServerName = custServerName;
	}

	public String getUploadfile() {
		return this.uploadfile;
	}

	public void setUploadfile(String uploadfile) {
		this.uploadfile = uploadfile;
	}

	public Date getAddtime() {
		return this.addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	public String getScreenExpertType() {
		return this.screenExpertType;
	}

	public void setScreenExpertType(String screenExpertType) {
		this.screenExpertType = screenExpertType;
	}

	public Set getOperSadinfos() {
		return this.operSadinfos;
	}

	public void setOperSadinfos(Set operSadinfos) {
		this.operSadinfos = operSadinfos;
	}

	public Set getOperPriceinfos() {
		return this.operPriceinfos;
	}

	public void setOperPriceinfos(Set operPriceinfos) {
		this.operPriceinfos = operPriceinfos;
	}

	public Set getOperQuestions() {
		return this.operQuestions;
	}

	public void setOperQuestions(Set operQuestions) {
		this.operQuestions = operQuestions;
	}

	public String getCustNumber() {
		return custNumber;
	}

	public void setCustNumber(String custNumber) {
		this.custNumber = custNumber;
	}

	public String getCustWorkWay() {
		return custWorkWay;
	}

	public void setCustWorkWay(String custWorkWay) {
		this.custWorkWay = custWorkWay;
	}

	public String getEliminateReason() {
		return eliminateReason;
	}

	public void setEliminateReason(String eliminateReason) {
		this.eliminateReason = eliminateReason;
	}

	public String getIsEliminate() {
		return isEliminate;
	}

	public void setIsEliminate(String isEliminate) {
		this.isEliminate = isEliminate;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

}