package et.po;

import java.util.Date;

/**
 * OrderMenu generated by MyEclipse Persistence Tools
 */

public class OrderMenu implements java.io.Serializable {

	// Fields

	private Integer id;

	private String menuType;

	private Date menuBegintime;

	private Date menuEndtime;

	private String ivrTreeInfoId;

	private Date egressiveTime;

	private String telnum;

	private String egressiveFlag;

	private String deleteMark;

	private String comingcall;

	// Constructors

	/** default constructor */
	public OrderMenu() {
	}

	/** full constructor */
	public OrderMenu(String menuType, Date menuBegintime, Date menuEndtime,
			String ivrTreeInfoId, Date egressiveTime, String telnum,
			String egressiveFlag, String deleteMark, String comingcall) {
		this.menuType = menuType;
		this.menuBegintime = menuBegintime;
		this.menuEndtime = menuEndtime;
		this.ivrTreeInfoId = ivrTreeInfoId;
		this.egressiveTime = egressiveTime;
		this.telnum = telnum;
		this.egressiveFlag = egressiveFlag;
		this.deleteMark = deleteMark;
		this.comingcall = comingcall;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMenuType() {
		return this.menuType;
	}

	public void setMenuType(String menuType) {
		this.menuType = menuType;
	}

	public Date getMenuBegintime() {
		return this.menuBegintime;
	}

	public void setMenuBegintime(Date menuBegintime) {
		this.menuBegintime = menuBegintime;
	}

	public Date getMenuEndtime() {
		return this.menuEndtime;
	}

	public void setMenuEndtime(Date menuEndtime) {
		this.menuEndtime = menuEndtime;
	}

	public String getIvrTreeInfoId() {
		return this.ivrTreeInfoId;
	}

	public void setIvrTreeInfoId(String ivrTreeInfoId) {
		this.ivrTreeInfoId = ivrTreeInfoId;
	}

	public Date getEgressiveTime() {
		return this.egressiveTime;
	}

	public void setEgressiveTime(Date egressiveTime) {
		this.egressiveTime = egressiveTime;
	}

	public String getTelnum() {
		return this.telnum;
	}

	public void setTelnum(String telnum) {
		this.telnum = telnum;
	}

	public String getEgressiveFlag() {
		return this.egressiveFlag;
	}

	public void setEgressiveFlag(String egressiveFlag) {
		this.egressiveFlag = egressiveFlag;
	}

	public String getDeleteMark() {
		return this.deleteMark;
	}

	public void setDeleteMark(String deleteMark) {
		this.deleteMark = deleteMark;
	}

	public String getComingcall() {
		return this.comingcall;
	}

	public void setComingcall(String comingcall) {
		this.comingcall = comingcall;
	}

}