package et.po;

/**
 * PortPbxIvr generated by MyEclipse Persistence Tools
 */

public class PortPbxIvr implements java.io.Serializable {

	// Fields

	private String id;

	private String pbxPort;

	private String pbxType;

	private String ivrPort;

	private String remark;

	// Constructors

	/** default constructor */
	public PortPbxIvr() {
	}

	/** minimal constructor */
	public PortPbxIvr(String id) {
		this.id = id;
	}

	/** full constructor */
	public PortPbxIvr(String id, String pbxPort, String pbxType,
			String ivrPort, String remark) {
		this.id = id;
		this.pbxPort = pbxPort;
		this.pbxType = pbxType;
		this.ivrPort = ivrPort;
		this.remark = remark;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPbxPort() {
		return this.pbxPort;
	}

	public void setPbxPort(String pbxPort) {
		this.pbxPort = pbxPort;
	}

	public String getPbxType() {
		return this.pbxType;
	}

	public void setPbxType(String pbxType) {
		this.pbxType = pbxType;
	}

	public String getIvrPort() {
		return this.ivrPort;
	}

	public void setIvrPort(String ivrPort) {
		this.ivrPort = ivrPort;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}