package et.po;

/**
 * Record generated by MyEclipse Persistence Tools
 */

public class Record implements java.io.Serializable {

	// Fields

	private RecordId id;

	// Constructors

	/** default constructor */
	public Record() {
	}

	/** full constructor */
	public Record(RecordId id) {
		this.id = id;
	}

	// Property accessors

	public RecordId getId() {
		return this.id;
	}

	public void setId(RecordId id) {
		this.id = id;
	}

}