package et.po;

import java.util.Date;

/**
 * RecordId generated by MyEclipse Persistence Tools
 */

public class RecordId implements java.io.Serializable {

	// Fields

	private Integer id;

	private String filename;

	private Date starttime;

	private Date endtime;

	private Integer dir;

	private Integer channo;

	private String caller;

	private String callee;

	private Integer flag;

	private String comment;

	private String wid;

	// Constructors

	/** default constructor */
	public RecordId() {
	}

	/** full constructor */
	public RecordId(Integer id, String filename, Date starttime, Date endtime,
			Integer dir, Integer channo, String caller, String callee,
			Integer flag, String comment, String wid) {
		this.id = id;
		this.filename = filename;
		this.starttime = starttime;
		this.endtime = endtime;
		this.dir = dir;
		this.channo = channo;
		this.caller = caller;
		this.callee = callee;
		this.flag = flag;
		this.comment = comment;
		this.wid = wid;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public Integer getDir() {
		return this.dir;
	}

	public void setDir(Integer dir) {
		this.dir = dir;
	}

	public Integer getChanno() {
		return this.channo;
	}

	public void setChanno(Integer channo) {
		this.channo = channo;
	}

	public String getCaller() {
		return this.caller;
	}

	public void setCaller(String caller) {
		this.caller = caller;
	}

	public String getCallee() {
		return this.callee;
	}

	public void setCallee(String callee) {
		this.callee = callee;
	}

	public Integer getFlag() {
		return this.flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getWid() {
		return this.wid;
	}

	public void setWid(String wid) {
		this.wid = wid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RecordId))
			return false;
		RecordId castOther = (RecordId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getFilename() == castOther.getFilename()) || (this
						.getFilename() != null
						&& castOther.getFilename() != null && this
						.getFilename().equals(castOther.getFilename())))
				&& ((this.getStarttime() == castOther.getStarttime()) || (this
						.getStarttime() != null
						&& castOther.getStarttime() != null && this
						.getStarttime().equals(castOther.getStarttime())))
				&& ((this.getEndtime() == castOther.getEndtime()) || (this
						.getEndtime() != null
						&& castOther.getEndtime() != null && this.getEndtime()
						.equals(castOther.getEndtime())))
				&& ((this.getDir() == castOther.getDir()) || (this.getDir() != null
						&& castOther.getDir() != null && this.getDir().equals(
						castOther.getDir())))
				&& ((this.getChanno() == castOther.getChanno()) || (this
						.getChanno() != null
						&& castOther.getChanno() != null && this.getChanno()
						.equals(castOther.getChanno())))
				&& ((this.getCaller() == castOther.getCaller()) || (this
						.getCaller() != null
						&& castOther.getCaller() != null && this.getCaller()
						.equals(castOther.getCaller())))
				&& ((this.getCallee() == castOther.getCallee()) || (this
						.getCallee() != null
						&& castOther.getCallee() != null && this.getCallee()
						.equals(castOther.getCallee())))
				&& ((this.getFlag() == castOther.getFlag()) || (this.getFlag() != null
						&& castOther.getFlag() != null && this.getFlag()
						.equals(castOther.getFlag())))
				&& ((this.getComment() == castOther.getComment()) || (this
						.getComment() != null
						&& castOther.getComment() != null && this.getComment()
						.equals(castOther.getComment())))
				&& ((this.getWid() == castOther.getWid()) || (this.getWid() != null
						&& castOther.getWid() != null && this.getWid().equals(
						castOther.getWid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getFilename() == null ? 0 : this.getFilename().hashCode());
		result = 37 * result
				+ (getStarttime() == null ? 0 : this.getStarttime().hashCode());
		result = 37 * result
				+ (getEndtime() == null ? 0 : this.getEndtime().hashCode());
		result = 37 * result
				+ (getDir() == null ? 0 : this.getDir().hashCode());
		result = 37 * result
				+ (getChanno() == null ? 0 : this.getChanno().hashCode());
		result = 37 * result
				+ (getCaller() == null ? 0 : this.getCaller().hashCode());
		result = 37 * result
				+ (getCallee() == null ? 0 : this.getCallee().hashCode());
		result = 37 * result
				+ (getFlag() == null ? 0 : this.getFlag().hashCode());
		result = 37 * result
				+ (getComment() == null ? 0 : this.getComment().hashCode());
		result = 37 * result
				+ (getWid() == null ? 0 : this.getWid().hashCode());
		return result;
	}

}