package et.po;

import java.util.Date;

/**
 * ScreenSpecialSurvey generated by MyEclipse Persistence Tools
 */

public class ScreenSpecialSurvey implements java.io.Serializable {

	// Fields

	private String id;

	private String surveyTitle;

	private Date surveyTime;

	private Date surveyUpdatetime;

	private String surveyExample;

	private String delegateDep;

	private String writter;

	private String keywords;

	private String summary;

	// Constructors

	/** default constructor */
	public ScreenSpecialSurvey() {
	}

	/** minimal constructor */
	public ScreenSpecialSurvey(String id) {
		this.id = id;
	}

	/** full constructor */
	public ScreenSpecialSurvey(String id, String surveyTitle, Date surveyTime,
			Date surveyUpdatetime, String surveyExample, String delegateDep,
			String writter, String keywords, String summary) {
		this.id = id;
		this.surveyTitle = surveyTitle;
		this.surveyTime = surveyTime;
		this.surveyUpdatetime = surveyUpdatetime;
		this.surveyExample = surveyExample;
		this.delegateDep = delegateDep;
		this.writter = writter;
		this.keywords = keywords;
		this.summary = summary;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSurveyTitle() {
		return this.surveyTitle;
	}

	public void setSurveyTitle(String surveyTitle) {
		this.surveyTitle = surveyTitle;
	}

	public Date getSurveyTime() {
		return this.surveyTime;
	}

	public void setSurveyTime(Date surveyTime) {
		this.surveyTime = surveyTime;
	}

	public Date getSurveyUpdatetime() {
		return this.surveyUpdatetime;
	}

	public void setSurveyUpdatetime(Date surveyUpdatetime) {
		this.surveyUpdatetime = surveyUpdatetime;
	}

	public String getSurveyExample() {
		return this.surveyExample;
	}

	public void setSurveyExample(String surveyExample) {
		this.surveyExample = surveyExample;
	}

	public String getDelegateDep() {
		return this.delegateDep;
	}

	public void setDelegateDep(String delegateDep) {
		this.delegateDep = delegateDep;
	}

	public String getWritter() {
		return this.writter;
	}

	public void setWritter(String writter) {
		this.writter = writter;
	}

	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

}