package et.po;

import java.util.Date;

/**
 * ScreenDoctor generated by MyEclipse Persistence Tools
 */

public class ScreenDoctor implements java.io.Serializable {

	// Fields

	private String id;

	private String docContent;

	private String type;

	private Date addtime;

	// Constructors

	/** default constructor */
	public ScreenDoctor() {
	}

	/** full constructor */
	public ScreenDoctor(String id,String docContent, String type, Date addtime) {
		this.id=id;
		this.docContent = docContent;
		this.type = type;
		this.addtime = addtime;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getDocContent() {
		return this.docContent;
	}

	public void setDocContent(String docContent) {
		this.docContent = docContent;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getAddtime() {
		return this.addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

}