package et.po;

import java.util.Date;

/**
 * ScreenQuickMessage generated by MyEclipse Persistence Tools
 */

public class ScreenQuickMessage implements java.io.Serializable {

	// Fields

	private String id;

	private String msgTitle;

	private String msgContent;

	private String inputMan;

	private Date createDate;

	private String remark;

	// Constructors

	/** default constructor */
	public ScreenQuickMessage() {
	}

	/** minimal constructor */
	public ScreenQuickMessage(String id) {
		this.id = id;
	}

	/** full constructor */
	public ScreenQuickMessage(String id, String msgTitle, String msgContent,
			String inputMan, Date createDate, String remark) {
		this.id = id;
		this.msgTitle = msgTitle;
		this.msgContent = msgContent;
		this.inputMan = inputMan;
		this.createDate = createDate;
		this.remark = remark;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMsgTitle() {
		return this.msgTitle;
	}

	public void setMsgTitle(String msgTitle) {
		this.msgTitle = msgTitle;
	}

	public String getMsgContent() {
		return this.msgContent;
	}

	public void setMsgContent(String msgContent) {
		this.msgContent = msgContent;
	}

	public String getInputMan() {
		return this.inputMan;
	}

	public void setInputMan(String inputMan) {
		this.inputMan = inputMan;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}