package et.po;

import java.util.Date;

/**
 * SmsLose generated by MyEclipse Persistence Tools
 */

public class SmsLose implements java.io.Serializable {

	// Fields

	private String id;

	private SmsContent smsContent;

	private String receiveNum;

	private String receiveManId;

	private String operCount;

	private Date schedularTime;

	private String managementId;

	private String operationId;

	private String successSign;

	private String sendState;

	private String loseReason;

	private String delSign;

	private String remark;

	// Constructors

	/** default constructor */
	public SmsLose() {
	}

	/** minimal constructor */
	public SmsLose(String id, SmsContent smsContent) {
		this.id = id;
		this.smsContent = smsContent;
	}

	/** full constructor */
	public SmsLose(String id, SmsContent smsContent, String receiveNum,
			String receiveManId, String operCount, Date schedularTime,
			String managementId, String operationId, String successSign,
			String sendState, String loseReason, String delSign, String remark) {
		this.id = id;
		this.smsContent = smsContent;
		this.receiveNum = receiveNum;
		this.receiveManId = receiveManId;
		this.operCount = operCount;
		this.schedularTime = schedularTime;
		this.managementId = managementId;
		this.operationId = operationId;
		this.successSign = successSign;
		this.sendState = sendState;
		this.loseReason = loseReason;
		this.delSign = delSign;
		this.remark = remark;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public SmsContent getSmsContent() {
		return this.smsContent;
	}

	public void setSmsContent(SmsContent smsContent) {
		this.smsContent = smsContent;
	}

	public String getReceiveNum() {
		return this.receiveNum;
	}

	public void setReceiveNum(String receiveNum) {
		this.receiveNum = receiveNum;
	}

	public String getReceiveManId() {
		return this.receiveManId;
	}

	public void setReceiveManId(String receiveManId) {
		this.receiveManId = receiveManId;
	}

	public String getOperCount() {
		return this.operCount;
	}

	public void setOperCount(String operCount) {
		this.operCount = operCount;
	}

	public Date getSchedularTime() {
		return this.schedularTime;
	}

	public void setSchedularTime(Date schedularTime) {
		this.schedularTime = schedularTime;
	}

	public String getManagementId() {
		return this.managementId;
	}

	public void setManagementId(String managementId) {
		this.managementId = managementId;
	}

	public String getOperationId() {
		return this.operationId;
	}

	public void setOperationId(String operationId) {
		this.operationId = operationId;
	}

	public String getSuccessSign() {
		return this.successSign;
	}

	public void setSuccessSign(String successSign) {
		this.successSign = successSign;
	}

	public String getSendState() {
		return this.sendState;
	}

	public void setSendState(String sendState) {
		this.sendState = sendState;
	}

	public String getLoseReason() {
		return this.loseReason;
	}

	public void setLoseReason(String loseReason) {
		this.loseReason = loseReason;
	}

	public String getDelSign() {
		return this.delSign;
	}

	public void setDelSign(String delSign) {
		this.delSign = delSign;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}