package et.po;

/**
 * SmsOperation generated by MyEclipse Persistence Tools
 */

public class SmsOperation implements java.io.Serializable {

	// Fields

	private String id;

	private String operationName;

	private String operationNum;

	private String delSign;

	private String remark;

	// Constructors

	/** default constructor */
	public SmsOperation() {
	}

	/** minimal constructor */
	public SmsOperation(String id) {
		this.id = id;
	}

	/** full constructor */
	public SmsOperation(String id, String operationName, String operationNum,
			String delSign, String remark) {
		this.id = id;
		this.operationName = operationName;
		this.operationNum = operationNum;
		this.delSign = delSign;
		this.remark = remark;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOperationName() {
		return this.operationName;
	}

	public void setOperationName(String operationName) {
		this.operationName = operationName;
	}

	public String getOperationNum() {
		return this.operationNum;
	}

	public void setOperationNum(String operationNum) {
		this.operationNum = operationNum;
	}

	public String getDelSign() {
		return this.delSign;
	}

	public void setDelSign(String delSign) {
		this.delSign = delSign;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}