package et.po;

import java.util.Date;

/**
 * SmsReceive generated by MyEclipse Persistence Tools
 */

public class SmsReceive implements java.io.Serializable {

	// Fields

	private String id;

	private String sendNum;

	private String receiveNum;

	private String content;

	private Date receiveTime;

	private String revertId;

	private String revertSign;

	private String operationId;

	private String delSign;

	private String remark;

	// Constructors

	/** default constructor */
	public SmsReceive() {
	}

	/** minimal constructor */
	public SmsReceive(String id) {
		this.id = id;
	}

	/** full constructor */
	public SmsReceive(String id, String sendNum, String receiveNum,
			String content, Date receiveTime, String revertId,
			String revertSign, String operationId, String delSign, String remark) {
		this.id = id;
		this.sendNum = sendNum;
		this.receiveNum = receiveNum;
		this.content = content;
		this.receiveTime = receiveTime;
		this.revertId = revertId;
		this.revertSign = revertSign;
		this.operationId = operationId;
		this.delSign = delSign;
		this.remark = remark;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSendNum() {
		return this.sendNum;
	}

	public void setSendNum(String sendNum) {
		this.sendNum = sendNum;
	}

	public String getReceiveNum() {
		return this.receiveNum;
	}

	public void setReceiveNum(String receiveNum) {
		this.receiveNum = receiveNum;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getReceiveTime() {
		return this.receiveTime;
	}

	public void setReceiveTime(Date receiveTime) {
		this.receiveTime = receiveTime;
	}

	public String getRevertId() {
		return this.revertId;
	}

	public void setRevertId(String revertId) {
		this.revertId = revertId;
	}

	public String getRevertSign() {
		return this.revertSign;
	}

	public void setRevertSign(String revertSign) {
		this.revertSign = revertSign;
	}

	public String getOperationId() {
		return this.operationId;
	}

	public void setOperationId(String operationId) {
		this.operationId = operationId;
	}

	public String getDelSign() {
		return this.delSign;
	}

	public void setDelSign(String delSign) {
		this.delSign = delSign;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}