package et.po;

import java.util.Date;

/**
 * StaffExperience generated by MyEclipse Persistence Tools
 */

public class StaffExperience implements java.io.Serializable {

	// Fields

	private String id;

	private StaffBasic staffBasic;

	private String dictExperienceType;

	private Date beginTime;

	private Date endTime;

	private String company;

	private String duty;

	private String address;

	private String message;

	private String proveMan;

	private String remark;

	// Constructors

	/** default constructor */
	public StaffExperience() {
	}

	/** minimal constructor */
	public StaffExperience(String id) {
		this.id = id;
	}

	/** full constructor */
	public StaffExperience(String id, StaffBasic staffBasic,
			String dictExperienceType, Date beginTime, Date endTime,
			String company, String duty, String address, String message,
			String proveMan, String remark) {
		this.id = id;
		this.staffBasic = staffBasic;
		this.dictExperienceType = dictExperienceType;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.company = company;
		this.duty = duty;
		this.address = address;
		this.message = message;
		this.proveMan = proveMan;
		this.remark = remark;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public StaffBasic getStaffBasic() {
		return this.staffBasic;
	}

	public void setStaffBasic(StaffBasic staffBasic) {
		this.staffBasic = staffBasic;
	}

	public String getDictExperienceType() {
		return this.dictExperienceType;
	}

	public void setDictExperienceType(String dictExperienceType) {
		this.dictExperienceType = dictExperienceType;
	}

	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getDuty() {
		return this.duty;
	}

	public void setDuty(String duty) {
		this.duty = duty;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getProveMan() {
		return this.proveMan;
	}

	public void setProveMan(String proveMan) {
		this.proveMan = proveMan;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}