package et.po;

import java.util.Date;

/**
 * StaffHortation generated by MyEclipse Persistence Tools
 */

public class StaffHortation implements java.io.Serializable {

	// Fields

	private String id;

	private StaffBasic staffBasic;

	private String hortationInfo;

	private Date hortationTime;

	private String hortationType;

	private String remark;

	// Constructors

	/** default constructor */
	public StaffHortation() {
	}

	/** minimal constructor */
	public StaffHortation(String id) {
		this.id = id;
	}

	/** full constructor */
	public StaffHortation(String id, StaffBasic staffBasic,
			String hortationInfo, Date hortationTime, String hortationType,
			String remark) {
		this.id = id;
		this.staffBasic = staffBasic;
		this.hortationInfo = hortationInfo;
		this.hortationTime = hortationTime;
		this.hortationType = hortationType;
		this.remark = remark;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public StaffBasic getStaffBasic() {
		return this.staffBasic;
	}

	public void setStaffBasic(StaffBasic staffBasic) {
		this.staffBasic = staffBasic;
	}

	public String getHortationInfo() {
		return this.hortationInfo;
	}

	public void setHortationInfo(String hortationInfo) {
		this.hortationInfo = hortationInfo;
	}

	public Date getHortationTime() {
		return this.hortationTime;
	}

	public void setHortationTime(Date hortationTime) {
		this.hortationTime = hortationTime;
	}

	public String getHortationType() {
		return this.hortationType;
	}

	public void setHortationType(String hortationType) {
		this.hortationType = hortationType;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}