package et.po;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * StaffBasic generated by MyEclipse Persistence Tools
 */

public class StaffBasic implements java.io.Serializable {

	// Fields

	private String staffId;

	private WorkUnitInfo workUnitInfo;

	private String BStaffNum;

	private String BPhotoPath;

	private String BStaffName;

	private String BStaffNickname;

	private String BStaffSex;

	private String BDictCountry;

	private String BDictProvince;

	private String BDictCity;

	private String BDictDistrict;

	private String BCtSchoolAge;

	private Date BBirthday;

	private String BNation;

	private String BAge;

	private String BNationAt;

	private String BDictPolity;

	private String BDictPaperType;

	private String BPaperNum;

	private String BDictIsMarry;

	private String BMarriage;

	private String BInterest;

	private String BHealthState;

	private String BDictDepartment;

	private String BDictDuty;

	private String BGrade;

	private String linkMobileNum;

	private String linkHomeNum;

	private String linkExtNum;

	private String linkQq;

	private String linkMsn;

	private String linkHomepage;

	private String CAddress;

	private String CPostalcode;

	private String CFaxNum;

	private String dictIsBeginwork;

	private String remark;

	private Set staffParents = new HashSet(0);

	private Set staffLanguages = new HashSet(0);

	private Set staffExperiences = new HashSet(0);

	private Set staffOtherInfos = new HashSet(0);

	private Set staffHortations = new HashSet(0);

	// Constructors

	/** default constructor */
	public StaffBasic() {
	}

	/** minimal constructor */
	public StaffBasic(String staffId) {
		this.staffId = staffId;
	}

	/** full constructor */
	public StaffBasic(String staffId, WorkUnitInfo workUnitInfo,
			String BStaffNum, String BPhotoPath, String BStaffName,
			String BStaffNickname, String BStaffSex, String BDictCountry,
			String BDictProvince, String BDictCity, String BDictDistrict,
			String BCtSchoolAge, Date BBirthday, String BNation, String BAge,
			String BNationAt, String BDictPolity, String BDictPaperType,
			String BPaperNum, String BDictIsMarry, String BMarriage,
			String BInterest, String BHealthState, String BDictDepartment,
			String BDictDuty, String BGrade, String linkMobileNum,
			String linkHomeNum, String linkExtNum, String linkQq,
			String linkMsn, String linkHomepage, String CAddress,
			String CPostalcode, String CFaxNum, String dictIsBeginwork,
			String remark, Set staffParents, Set staffLanguages,
			Set staffExperiences, Set staffOtherInfos, Set staffHortations) {
		this.staffId = staffId;
		this.workUnitInfo = workUnitInfo;
		this.BStaffNum = BStaffNum;
		this.BPhotoPath = BPhotoPath;
		this.BStaffName = BStaffName;
		this.BStaffNickname = BStaffNickname;
		this.BStaffSex = BStaffSex;
		this.BDictCountry = BDictCountry;
		this.BDictProvince = BDictProvince;
		this.BDictCity = BDictCity;
		this.BDictDistrict = BDictDistrict;
		this.BCtSchoolAge = BCtSchoolAge;
		this.BBirthday = BBirthday;
		this.BNation = BNation;
		this.BAge = BAge;
		this.BNationAt = BNationAt;
		this.BDictPolity = BDictPolity;
		this.BDictPaperType = BDictPaperType;
		this.BPaperNum = BPaperNum;
		this.BDictIsMarry = BDictIsMarry;
		this.BMarriage = BMarriage;
		this.BInterest = BInterest;
		this.BHealthState = BHealthState;
		this.BDictDepartment = BDictDepartment;
		this.BDictDuty = BDictDuty;
		this.BGrade = BGrade;
		this.linkMobileNum = linkMobileNum;
		this.linkHomeNum = linkHomeNum;
		this.linkExtNum = linkExtNum;
		this.linkQq = linkQq;
		this.linkMsn = linkMsn;
		this.linkHomepage = linkHomepage;
		this.CAddress = CAddress;
		this.CPostalcode = CPostalcode;
		this.CFaxNum = CFaxNum;
		this.dictIsBeginwork = dictIsBeginwork;
		this.remark = remark;
		this.staffParents = staffParents;
		this.staffLanguages = staffLanguages;
		this.staffExperiences = staffExperiences;
		this.staffOtherInfos = staffOtherInfos;
		this.staffHortations = staffHortations;
	}

	// Property accessors

	public String getStaffId() {
		return this.staffId;
	}

	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}

	public WorkUnitInfo getWorkUnitInfo() {
		return this.workUnitInfo;
	}

	public void setWorkUnitInfo(WorkUnitInfo workUnitInfo) {
		this.workUnitInfo = workUnitInfo;
	}

	public String getBStaffNum() {
		return this.BStaffNum;
	}

	public void setBStaffNum(String BStaffNum) {
		this.BStaffNum = BStaffNum;
	}

	public String getBPhotoPath() {
		return this.BPhotoPath;
	}

	public void setBPhotoPath(String BPhotoPath) {
		this.BPhotoPath = BPhotoPath;
	}

	public String getBStaffName() {
		return this.BStaffName;
	}

	public void setBStaffName(String BStaffName) {
		this.BStaffName = BStaffName;
	}

	public String getBStaffNickname() {
		return this.BStaffNickname;
	}

	public void setBStaffNickname(String BStaffNickname) {
		this.BStaffNickname = BStaffNickname;
	}

	public String getBStaffSex() {
		return this.BStaffSex;
	}

	public void setBStaffSex(String BStaffSex) {
		this.BStaffSex = BStaffSex;
	}

	public String getBDictCountry() {
		return this.BDictCountry;
	}

	public void setBDictCountry(String BDictCountry) {
		this.BDictCountry = BDictCountry;
	}

	public String getBDictProvince() {
		return this.BDictProvince;
	}

	public void setBDictProvince(String BDictProvince) {
		this.BDictProvince = BDictProvince;
	}

	public String getBDictCity() {
		return this.BDictCity;
	}

	public void setBDictCity(String BDictCity) {
		this.BDictCity = BDictCity;
	}

	public String getBDictDistrict() {
		return this.BDictDistrict;
	}

	public void setBDictDistrict(String BDictDistrict) {
		this.BDictDistrict = BDictDistrict;
	}

	public String getBCtSchoolAge() {
		return this.BCtSchoolAge;
	}

	public void setBCtSchoolAge(String BCtSchoolAge) {
		this.BCtSchoolAge = BCtSchoolAge;
	}

	public Date getBBirthday() {
		return this.BBirthday;
	}

	public void setBBirthday(Date BBirthday) {
		this.BBirthday = BBirthday;
	}

	public String getBNation() {
		return this.BNation;
	}

	public void setBNation(String BNation) {
		this.BNation = BNation;
	}

	public String getBAge() {
		return this.BAge;
	}

	public void setBAge(String BAge) {
		this.BAge = BAge;
	}

	public String getBNationAt() {
		return this.BNationAt;
	}

	public void setBNationAt(String BNationAt) {
		this.BNationAt = BNationAt;
	}

	public String getBDictPolity() {
		return this.BDictPolity;
	}

	public void setBDictPolity(String BDictPolity) {
		this.BDictPolity = BDictPolity;
	}

	public String getBDictPaperType() {
		return this.BDictPaperType;
	}

	public void setBDictPaperType(String BDictPaperType) {
		this.BDictPaperType = BDictPaperType;
	}

	public String getBPaperNum() {
		return this.BPaperNum;
	}

	public void setBPaperNum(String BPaperNum) {
		this.BPaperNum = BPaperNum;
	}

	public String getBDictIsMarry() {
		return this.BDictIsMarry;
	}

	public void setBDictIsMarry(String BDictIsMarry) {
		this.BDictIsMarry = BDictIsMarry;
	}

	public String getBMarriage() {
		return this.BMarriage;
	}

	public void setBMarriage(String BMarriage) {
		this.BMarriage = BMarriage;
	}

	public String getBInterest() {
		return this.BInterest;
	}

	public void setBInterest(String BInterest) {
		this.BInterest = BInterest;
	}

	public String getBHealthState() {
		return this.BHealthState;
	}

	public void setBHealthState(String BHealthState) {
		this.BHealthState = BHealthState;
	}

	public String getBDictDepartment() {
		return this.BDictDepartment;
	}

	public void setBDictDepartment(String BDictDepartment) {
		this.BDictDepartment = BDictDepartment;
	}

	public String getBDictDuty() {
		return this.BDictDuty;
	}

	public void setBDictDuty(String BDictDuty) {
		this.BDictDuty = BDictDuty;
	}

	public String getBGrade() {
		return this.BGrade;
	}

	public void setBGrade(String BGrade) {
		this.BGrade = BGrade;
	}

	public String getLinkMobileNum() {
		return this.linkMobileNum;
	}

	public void setLinkMobileNum(String linkMobileNum) {
		this.linkMobileNum = linkMobileNum;
	}

	public String getLinkHomeNum() {
		return this.linkHomeNum;
	}

	public void setLinkHomeNum(String linkHomeNum) {
		this.linkHomeNum = linkHomeNum;
	}

	public String getLinkExtNum() {
		return this.linkExtNum;
	}

	public void setLinkExtNum(String linkExtNum) {
		this.linkExtNum = linkExtNum;
	}

	public String getLinkQq() {
		return this.linkQq;
	}

	public void setLinkQq(String linkQq) {
		this.linkQq = linkQq;
	}

	public String getLinkMsn() {
		return this.linkMsn;
	}

	public void setLinkMsn(String linkMsn) {
		this.linkMsn = linkMsn;
	}

	public String getLinkHomepage() {
		return this.linkHomepage;
	}

	public void setLinkHomepage(String linkHomepage) {
		this.linkHomepage = linkHomepage;
	}

	public String getCAddress() {
		return this.CAddress;
	}

	public void setCAddress(String CAddress) {
		this.CAddress = CAddress;
	}

	public String getCPostalcode() {
		return this.CPostalcode;
	}

	public void setCPostalcode(String CPostalcode) {
		this.CPostalcode = CPostalcode;
	}

	public String getCFaxNum() {
		return this.CFaxNum;
	}

	public void setCFaxNum(String CFaxNum) {
		this.CFaxNum = CFaxNum;
	}

	public String getDictIsBeginwork() {
		return this.dictIsBeginwork;
	}

	public void setDictIsBeginwork(String dictIsBeginwork) {
		this.dictIsBeginwork = dictIsBeginwork;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set getStaffParents() {
		return this.staffParents;
	}

	public void setStaffParents(Set staffParents) {
		this.staffParents = staffParents;
	}

	public Set getStaffLanguages() {
		return this.staffLanguages;
	}

	public void setStaffLanguages(Set staffLanguages) {
		this.staffLanguages = staffLanguages;
	}

	public Set getStaffExperiences() {
		return this.staffExperiences;
	}

	public void setStaffExperiences(Set staffExperiences) {
		this.staffExperiences = staffExperiences;
	}

	public Set getStaffOtherInfos() {
		return this.staffOtherInfos;
	}

	public void setStaffOtherInfos(Set staffOtherInfos) {
		this.staffOtherInfos = staffOtherInfos;
	}

	public Set getStaffHortations() {
		return this.staffHortations;
	}

	public void setStaffHortations(Set staffHortations) {
		this.staffHortations = staffHortations;
	}

}