package et.po;

import java.util.Date;

/**
 * SynodNote generated by MyEclipse Persistence Tools
 */

public class SynodNote implements java.io.Serializable {

	// Fields

	private String id;

	private Date synodDate;

	private String synodAddr;

	private String synodOwner;

	private String synodPeople;

	private String synodTopic;

	private String synodOutline;

	private String synodFile;

	private Date applyTime;

	private String flowId;

	private String remark;

	private String examId;

	private String examResult;

	private String endFlag;

	private String endDoc;

	// Constructors

	/** default constructor */
	public SynodNote() {
	}

	/** minimal constructor */
	public SynodNote(String id) {
		this.id = id;
	}

	/** full constructor */
	public SynodNote(String id, Date synodDate, String synodAddr,
			String synodOwner, String synodPeople, String synodTopic,
			String synodOutline, String synodFile, Date applyTime,
			String flowId, String remark, String examId, String examResult,
			String endFlag, String endDoc) {
		this.id = id;
		this.synodDate = synodDate;
		this.synodAddr = synodAddr;
		this.synodOwner = synodOwner;
		this.synodPeople = synodPeople;
		this.synodTopic = synodTopic;
		this.synodOutline = synodOutline;
		this.synodFile = synodFile;
		this.applyTime = applyTime;
		this.flowId = flowId;
		this.remark = remark;
		this.examId = examId;
		this.examResult = examResult;
		this.endFlag = endFlag;
		this.endDoc = endDoc;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getSynodDate() {
		return this.synodDate;
	}

	public void setSynodDate(Date synodDate) {
		this.synodDate = synodDate;
	}

	public String getSynodAddr() {
		return this.synodAddr;
	}

	public void setSynodAddr(String synodAddr) {
		this.synodAddr = synodAddr;
	}

	public String getSynodOwner() {
		return this.synodOwner;
	}

	public void setSynodOwner(String synodOwner) {
		this.synodOwner = synodOwner;
	}

	public String getSynodPeople() {
		return this.synodPeople;
	}

	public void setSynodPeople(String synodPeople) {
		this.synodPeople = synodPeople;
	}

	public String getSynodTopic() {
		return this.synodTopic;
	}

	public void setSynodTopic(String synodTopic) {
		this.synodTopic = synodTopic;
	}

	public String getSynodOutline() {
		return this.synodOutline;
	}

	public void setSynodOutline(String synodOutline) {
		this.synodOutline = synodOutline;
	}

	public String getSynodFile() {
		return this.synodFile;
	}

	public void setSynodFile(String synodFile) {
		this.synodFile = synodFile;
	}

	public Date getApplyTime() {
		return this.applyTime;
	}

	public void setApplyTime(Date applyTime) {
		this.applyTime = applyTime;
	}

	public String getFlowId() {
		return this.flowId;
	}

	public void setFlowId(String flowId) {
		this.flowId = flowId;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getExamId() {
		return this.examId;
	}

	public void setExamId(String examId) {
		this.examId = examId;
	}

	public String getExamResult() {
		return this.examResult;
	}

	public void setExamResult(String examResult) {
		this.examResult = examResult;
	}

	public String getEndFlag() {
		return this.endFlag;
	}

	public void setEndFlag(String endFlag) {
		this.endFlag = endFlag;
	}

	public String getEndDoc() {
		return this.endDoc;
	}

	public void setEndDoc(String endDoc) {
		this.endDoc = endDoc;
	}

}