package et.po;

import java.util.HashSet;
import java.util.Set;

/**
 * SysLeafRight generated by MyEclipse Persistence Tools
 */

public class SysLeafRight implements java.io.Serializable {

	// Fields

	private String id;

	private BaseTree baseTree;

	private String type;

	private String icon;

	private String label;

	private String nickName;

	private String deleteMark;

	private String remark;

	private Set sysRightRoles = new HashSet(0);

	// Constructors

	/** default constructor */
	public SysLeafRight() {
	}

	/** minimal constructor */
	public SysLeafRight(String id) {
		this.id = id;
	}

	/** full constructor */
	public SysLeafRight(String id, BaseTree baseTree, String type, String icon,
			String label, String nickName, String deleteMark, String remark,
			Set sysRightRoles) {
		this.id = id;
		this.baseTree = baseTree;
		this.type = type;
		this.icon = icon;
		this.label = label;
		this.nickName = nickName;
		this.deleteMark = deleteMark;
		this.remark = remark;
		this.sysRightRoles = sysRightRoles;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public BaseTree getBaseTree() {
		return this.baseTree;
	}

	public void setBaseTree(BaseTree baseTree) {
		this.baseTree = baseTree;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getDeleteMark() {
		return this.deleteMark;
	}

	public void setDeleteMark(String deleteMark) {
		this.deleteMark = deleteMark;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set getSysRightRoles() {
		return this.sysRightRoles;
	}

	public void setSysRightRoles(Set sysRightRoles) {
		this.sysRightRoles = sysRightRoles;
	}

}