package et.po;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SysLog generated by MyEclipse Persistence Tools
 */

public class SysLog implements java.io.Serializable {

	// Fields

	private String id;

	private SysUser sysUser;

	private String modu;

	private String ip;

	private Date operTime;

	private String oper;

	private String remark;

	private Set sysLogDetails = new HashSet(0);

	// Constructors

	/** default constructor */
	public SysLog() {
	}

	/** minimal constructor */
	public SysLog(String id) {
		this.id = id;
	}

	/** full constructor */
	public SysLog(String id, SysUser sysUser, String modu, String ip,
			Date operTime, String oper, String remark, Set sysLogDetails) {
		this.id = id;
		this.sysUser = sysUser;
		this.modu = modu;
		this.ip = ip;
		this.operTime = operTime;
		this.oper = oper;
		this.remark = remark;
		this.sysLogDetails = sysLogDetails;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public SysUser getSysUser() {
		return this.sysUser;
	}

	public void setSysUser(SysUser sysUser) {
		this.sysUser = sysUser;
	}

	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Date getOperTime() {
		return this.operTime;
	}

	public void setOperTime(Date operTime) {
		this.operTime = operTime;
	}

	public String getOper() {
		return this.oper;
	}

	public void setOper(String oper) {
		this.oper = oper;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set getSysLogDetails() {
		return this.sysLogDetails;
	}

	public void setSysLogDetails(Set sysLogDetails) {
		this.sysLogDetails = sysLogDetails;
	}

}