package et.po;

/**
 * SysRightGroup generated by MyEclipse Persistence Tools
 */

public class SysRightGroup implements java.io.Serializable {

	// Fields

	private String id;

	private BaseTree baseTree;

	private SysGroup sysGroup;

	// Constructors

	/** default constructor */
	public SysRightGroup() {
	}

	/** minimal constructor */
	public SysRightGroup(String id) {
		this.id = id;
	}

	/** full constructor */
	public SysRightGroup(String id, BaseTree baseTree, SysGroup sysGroup) {
		this.id = id;
		this.baseTree = baseTree;
		this.sysGroup = sysGroup;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public BaseTree getBaseTree() {
		return this.baseTree;
	}

	public void setBaseTree(BaseTree baseTree) {
		this.baseTree = baseTree;
	}

	public SysGroup getSysGroup() {
		return this.sysGroup;
	}

	public void setSysGroup(SysGroup sysGroup) {
		this.sysGroup = sysGroup;
	}

}