package et.po;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SysUser generated by MyEclipse Persistence Tools
 */

public class SysUser implements java.io.Serializable {

	// Fields

	private String userId;

	private SysDepartment sysDepartment;

	private SysRole sysRole;

	private SysGroup sysGroup;

	private String password;

	private String userName;

	private String deleteMark;

	private String remark;

	private String staffSign;

	private String isFreeze;

	private String isSys;

	private String skill;

	private Date createTime;

	private String auditing;

	private Set sysRightUsers = new HashSet(0);

	private Set sysUserInfos = new HashSet(0);

	private Set sysLogs = new HashSet(0);

	// Constructors

	/** default constructor */
	public SysUser() {
	}

	/** minimal constructor */
	public SysUser(String userId) {
		this.userId = userId;
	}

	/** full constructor */
	public SysUser(String userId, SysDepartment sysDepartment, SysRole sysRole, SysGroup sysGroup, String password, String userName, String deleteMark,
			String remark, String staffSign, String isFreeze, String isSys, String skill, Date createTime, String auditing, Set sysRightUsers,
			Set sysUserInfos, Set sysLogs) {
		this.userId = userId;
		this.sysDepartment = sysDepartment;
		this.sysRole = sysRole;
		this.sysGroup = sysGroup;
		this.password = password;
		this.userName = userName;
		this.deleteMark = deleteMark;
		this.remark = remark;
		this.staffSign = staffSign;
		this.isFreeze = isFreeze;
		this.isSys = isSys;
		this.skill = skill;
		this.createTime = createTime;
		this.auditing = auditing;
		this.sysRightUsers = sysRightUsers;
		this.sysUserInfos = sysUserInfos;
		this.sysLogs = sysLogs;
	}

	// Property accessors

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public SysDepartment getSysDepartment() {
		return this.sysDepartment;
	}

	public void setSysDepartment(SysDepartment sysDepartment) {
		this.sysDepartment = sysDepartment;
	}

	public SysRole getSysRole() {
		return this.sysRole;
	}

	public void setSysRole(SysRole sysRole) {
		this.sysRole = sysRole;
	}

	public SysGroup getSysGroup() {
		return this.sysGroup;
	}

	public void setSysGroup(SysGroup sysGroup) {
		this.sysGroup = sysGroup;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getDeleteMark() {
		return this.deleteMark;
	}

	public void setDeleteMark(String deleteMark) {
		this.deleteMark = deleteMark;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getStaffSign() {
		return this.staffSign;
	}

	public void setStaffSign(String staffSign) {
		this.staffSign = staffSign;
	}

	public String getIsFreeze() {
		return this.isFreeze;
	}

	public void setIsFreeze(String isFreeze) {
		this.isFreeze = isFreeze;
	}

	public String getIsSys() {
		return this.isSys;
	}

	public void setIsSys(String isSys) {
		this.isSys = isSys;
	}

	public String getSkill() {
		return this.skill;
	}

	public void setSkill(String skill) {
		this.skill = skill;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getAuditing() {
		return this.auditing;
	}

	public void setAuditing(String auditing) {
		this.auditing = auditing;
	}

	public Set getSysRightUsers() {
		return this.sysRightUsers;
	}

	public void setSysRightUsers(Set sysRightUsers) {
		this.sysRightUsers = sysRightUsers;
	}

	public Set getSysUserInfos() {
		return this.sysUserInfos;
	}

	public void setSysUserInfos(Set sysUserInfos) {
		this.sysUserInfos = sysUserInfos;
	}

	public Set getSysLogs() {
		return this.sysLogs;
	}

	public void setSysLogs(Set sysLogs) {
		this.sysLogs = sysLogs;
	}

}