package et.po;

import java.util.Date;


/**
 * ThirdLog generated by MyEclipse Persistence Tools
 */

public class ThirdLog  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String agcwid;
     private Date callBetintime;
     private String remark;


    // Constructors

    /** default constructor */
    public ThirdLog() {
    }

    
    /** full constructor */
    public ThirdLog(String agcwid, Date callBetintime, String remark) {
        this.agcwid = agcwid;
        this.callBetintime = callBetintime;
        this.remark = remark;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getAgcwid() {
        return this.agcwid;
    }
    
    public void setAgcwid(String agcwid) {
        this.agcwid = agcwid;
    }

    public Date getCallBetintime() {
        return this.callBetintime;
    }
    
    public void setCallBetintime(Date callBetintime) {
        this.callBetintime = callBetintime;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
   








}