package et.po;

import java.util.HashSet;
import java.util.Set;

/**
 * WorkUnitInfo generated by MyEclipse Persistence Tools
 */

public class WorkUnitInfo implements java.io.Serializable {

	// Fields

	private String id;

	private String companyName;

	private String companyTel;

	private String fax;

	private String companyAddress;

	private String post;

	private String dictCompanyType;

	private String helpsign;

	private String homepage;

	private String remark;

	private Set staffBasics = new HashSet(0);

	// Constructors

	/** default constructor */
	public WorkUnitInfo() {
	}

	/** minimal constructor */
	public WorkUnitInfo(String id) {
		this.id = id;
	}

	/** full constructor */
	public WorkUnitInfo(String id, String companyName, String companyTel,
			String fax, String companyAddress, String post,
			String dictCompanyType, String helpsign, String homepage,
			String remark, Set staffBasics) {
		this.id = id;
		this.companyName = companyName;
		this.companyTel = companyTel;
		this.fax = fax;
		this.companyAddress = companyAddress;
		this.post = post;
		this.dictCompanyType = dictCompanyType;
		this.helpsign = helpsign;
		this.homepage = homepage;
		this.remark = remark;
		this.staffBasics = staffBasics;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getCompanyTel() {
		return this.companyTel;
	}

	public void setCompanyTel(String companyTel) {
		this.companyTel = companyTel;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getCompanyAddress() {
		return this.companyAddress;
	}

	public void setCompanyAddress(String companyAddress) {
		this.companyAddress = companyAddress;
	}

	public String getPost() {
		return this.post;
	}

	public void setPost(String post) {
		this.post = post;
	}

	public String getDictCompanyType() {
		return this.dictCompanyType;
	}

	public void setDictCompanyType(String dictCompanyType) {
		this.dictCompanyType = dictCompanyType;
	}

	public String getHelpsign() {
		return this.helpsign;
	}

	public void setHelpsign(String helpsign) {
		this.helpsign = helpsign;
	}

	public String getHomepage() {
		return this.homepage;
	}

	public void setHomepage(String homepage) {
		this.homepage = homepage;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set getStaffBasics() {
		return this.staffBasics;
	}

	public void setStaffBasics(Set staffBasics) {
		this.staffBasics = staffBasics;
	}

}