// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jbpm.bpel.tutorial.account;

public interface AccountSystem extends java.rmi.Remote {
    public boolean checkAccess(java.lang.String customerName) throws 
         java.rmi.RemoteException;
    public double queryBalance(java.lang.String customerName) throws 
         java.rmi.RemoteException;
    public double updateBalance(org.jbpm.bpel.tutorial.account.types.TAccountOperation body) throws 
         java.rmi.RemoteException;
}
