// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jbpm.bpel.tutorial.account.types;


public class TAccountOperation {
    protected java.lang.String customerName;
    protected double amount;
    
    public TAccountOperation() {
    }
    
    public TAccountOperation(java.lang.String customerName, double amount) {
        this.customerName = customerName;
        this.amount = amount;
    }
    
    public java.lang.String getCustomerName() {
        return customerName;
    }
    
    public void setCustomerName(java.lang.String customerName) {
        this.customerName = customerName;
    }
    
    public double getAmount() {
        return amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }
}
