/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin */

#ifndef _Included_et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
#define _Included_et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    LoadDRV
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_LoadDRV
  (JNIEnv *, jobject);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    FreeDRV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_FreeDRV
  (JNIEnv *, jobject);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    EnableCard
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_EnableCard
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    DisableCard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_DisableCard
  (JNIEnv *, jobject);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    GetSysInfo
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_GetSysInfo
  (JNIEnv *, jobject);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    GetSysInfoMore
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_GetSysInfoMore
  (JNIEnv *, jobject);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    CheckValidCh
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_CheckValidCh
  (JNIEnv *, jobject);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    CheckChType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_CheckChType
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    CheckChTypeNew
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_CheckChTypeNew
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    IsSupportCallerID
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_IsSupportCallerID
  (JNIEnv *, jobject);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    SetPackRate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_SetPackRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    PUSH_PLAY
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_PUSH_1PLAY
  (JNIEnv *, jobject);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    SetBusyPara
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_SetBusyPara
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    SetDialPara
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_SetDialPara
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    NewReadPass
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_NewReadPass
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    D_SetWorkMode
 * Signature: (ICC)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_D_1SetWorkMode
  (JNIEnv *, jobject, jint, jchar, jchar);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    RingDetect
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_RingDetect
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    OffHook
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_OffHook
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    HangUp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_HangUp
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    StartPlay
 * Signature: (ILjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_StartPlay
  (JNIEnv *, jobject, jint, jstring, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    StopPlay
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_StopPlay
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    CheckPlayEnd
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_CheckPlayEnd
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    StartPlayFile
 * Signature: (ILjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_StartPlayFile
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    StopPlayFile
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_StopPlayFile
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    RsetIndexPlayFile
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_RsetIndexPlayFile
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    AddIndexPlayFile
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_AddIndexPlayFile
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    StartIndexPlayFile
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_StartIndexPlayFile
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    CheckIndexPlayFile
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_CheckIndexPlayFile
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    StopIndexPlayFile
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_StopIndexPlayFile
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    ResetIndex
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_ResetIndex
  (JNIEnv *, jobject);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    SetIndex
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_SetIndex
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    StartPlayIndex
 * Signature: (I[II)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_StartPlayIndex
  (JNIEnv *, jobject, jint, jintArray, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    StartRecordFile
 * Signature: (ILjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_StartRecordFile
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    StartRecordFileNew
 * Signature: (ILjava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_StartRecordFileNew
  (JNIEnv *, jobject, jint, jstring, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    CheckRecordEnd
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_CheckRecordEnd
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    StopRecordFile
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_StopRecordFile
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    InitDtmfBuf
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_InitDtmfBuf
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    GetDtmfCode
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_GetDtmfCode
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    DtmfHit
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_DtmfHit
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    SendDtmfBuf
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_SendDtmfBuf
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    CheckSendEnd
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_CheckSendEnd
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    SetSendPara
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_SetSendPara
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    NewSendDtmfBuf
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_NewSendDtmfBuf
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    NewCheckSendEnd
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_NewCheckSendEnd
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    StartSigCheck
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_StartSigCheck
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    StopSigCheck
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_StopSigCheck
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    ReadCheckResult
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_ReadCheckResult
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    ReadBusyCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_ReadBusyCount
  (JNIEnv *, jobject);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    CheckPolarity
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_CheckPolarity
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    CheckSilence
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_CheckSilence
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    StartPlaySignal
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_StartPlaySignal
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    StartHangUpDetect
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_StartHangUpDetect
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    HangUpDetect
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_HangUpDetect
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    FeedRing
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_FeedRing
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    FeedRealRing
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_FeedRealRing
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    FeedPower
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_FeedPower
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    OffHookDetect
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_OffHookDetect
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    ReadGenerateSigBuf
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_ReadGenerateSigBuf
  (JNIEnv *, jobject, jstring);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    FeedSigFunc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_FeedSigFunc
  (JNIEnv *, jobject);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    StartTimer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_StartTimer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    ElapseTime
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_ElapseTime
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    SetLink
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_SetLink
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    ClearLink
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_ClearLink
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    LinkOneToAnother
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_LinkOneToAnother
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    ClearOneFromAnother
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_ClearOneFromAnother
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    LinkThree
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_LinkThree
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    ClearThree
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_ClearThree
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    ResetCallerIDBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_ResetCallerIDBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    GetCallerIDRawStr
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_GetCallerIDRawStr
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    GetCallerIDStr
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_GetCallerIDStr
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    PcmtoWave
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_PcmtoWave
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    WavetoPcm
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_WavetoPcm
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    AdtoPcm
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_AdtoPcm
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    PcmtoAd
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_PcmtoAd
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    Ad6ktoPcm
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_Ad6ktoPcm
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    D_AdjustVocVol
 * Signature: (ICC)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_D_1AdjustVocVol
  (JNIEnv *, jobject, jint, jchar, jchar);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    D_AdjustVocVol_ForVB
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_D_1AdjustVocVol_1ForVB
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    DRec_OffHookDetect
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_DRec_1OffHookDetect
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    VR_SetRefreshSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_VR_1SetRefreshSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    VR_StartRecord
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_VR_1StartRecord
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    VR_StopRecord
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_VR_1StopRecord
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    VR_GetRecordData
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_VR_1GetRecordData
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    VR_SetEcrMode
 * Signature: (IBII)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_VR_1SetEcrMode
  (JNIEnv *, jobject, jint, jbyte, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    DJFsk_InitForFsk
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_DJFsk_1InitForFsk
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    DJFsk_ResetFskBuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_DJFsk_1ResetFskBuffer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    DJFsk_CheckSendFSKEnd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_DJFsk_1CheckSendFSKEnd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    DJFsk_SendFSK
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_DJFsk_1SendFSK
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    DJFsk_GetFSK
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_DJFsk_1GetFSK
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    DJFsk_StopSend
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_DJFsk_1StopSend
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    DJFsk_Release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_DJFsk_1Release
  (JNIEnv *, jobject);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    DJFsk_SendFSKA
 * Signature: (I[BIII)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_DJFsk_1SendFSKA
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    DJFsk_SendFSKBit
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_DJFsk_1SendFSKBit
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    D160PCI_GetTimeSlot
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_D160PCI_1GetTimeSlot
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    D160PCI_ConnectFromTS
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_D160PCI_1ConnectFromTS
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    D160PCI_DisconnectTS
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_D160PCI_1DisconnectTS
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    AddChnl
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_AddChnl
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    SubChnl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_SubChnl
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    AddListenChnl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_AddListenChnl
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    SubListenChnk
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_SubListenChnk
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    DConf_EnableConfCard
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_DConf_1EnableConfCard
  (JNIEnv *, jobject);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    DConf_DisableConfCard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_DConf_1DisableConfCard
  (JNIEnv *, jobject);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    DConf_AddRecListenChnl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_DConf_1AddRecListenChnl
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    DConf_SubRecListenChnl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_DConf_1SubRecListenChnl
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    DConf_GetResNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_DConf_1GetResNumber
  (JNIEnv *, jobject);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    sigInit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_sigInit
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    sigCheckBusy
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_sigCheckBusy
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    sigResetCheck
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_sigResetCheck
  (JNIEnv *, jobject, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    sigStartDial
 * Signature: (I[C[CI)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_sigStartDial
  (JNIEnv *, jobject, jint, jstring, jstring, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    sigGetCadenceCount
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_sigGetCadenceCount
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     et_bo_callcenter_plant_dongjin_c161a_impl_Dongjin
 * Method:    sigCheckDial
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_et_bo_callcenter_plant_dongjin_1c161a_impl_Dongjin_sigCheckDial
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
