package et.po;

import java.util.Date;


/**
 * SysUserInfo generated by MyEclipse - Hibernate Tools
 */

public class SysUserInfo  implements java.io.Serializable {


    // Fields    

     private String userId;
     private SysUser sysUser;
     private String realName;
     private String sexId;
     private String identityKind;
     private String identityCard;
     private String email;
     private Date birthday;
     private String countryId;
     private String provinceId;
     private String cityId;
     private String qq;
     private String bloodType;
     private String address;
     private String postalcode;
     private String mobile;
     private String finishSchool;
     private String speciality;
     private String workId;
     private String homepage;
     private String remark;


    // Constructors

    /** default constructor */
    public SysUserInfo() {
    }

	/** minimal constructor */
    public SysUserInfo(String userId, SysUser sysUser) {
        this.userId = userId;
        this.sysUser = sysUser;
    }
    
    /** full constructor */
    public SysUserInfo(String userId, SysUser sysUser, String realName, String sexId, String identityKind, String identityCard, String email, Date birthday, String countryId, String provinceId, String cityId, String qq, String bloodType, String address, String postalcode, String mobile, String finishSchool, String speciality, String workId, String homepage, String remark) {
        this.userId = userId;
        this.sysUser = sysUser;
        this.realName = realName;
        this.sexId = sexId;
        this.identityKind = identityKind;
        this.identityCard = identityCard;
        this.email = email;
        this.birthday = birthday;
        this.countryId = countryId;
        this.provinceId = provinceId;
        this.cityId = cityId;
        this.qq = qq;
        this.bloodType = bloodType;
        this.address = address;
        this.postalcode = postalcode;
        this.mobile = mobile;
        this.finishSchool = finishSchool;
        this.speciality = speciality;
        this.workId = workId;
        this.homepage = homepage;
        this.remark = remark;
    }

   
    // Property accessors

    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    public SysUser getSysUser() {
        return this.sysUser;
    }
    
    public void setSysUser(SysUser sysUser) {
        this.sysUser = sysUser;
    }

    public String getRealName() {
        return this.realName;
    }
    
    public void setRealName(String realName) {
        this.realName = realName;
    }

    public String getSexId() {
        return this.sexId;
    }
    
    public void setSexId(String sexId) {
        this.sexId = sexId;
    }

    public String getIdentityKind() {
        return this.identityKind;
    }
    
    public void setIdentityKind(String identityKind) {
        this.identityKind = identityKind;
    }

    public String getIdentityCard() {
        return this.identityCard;
    }
    
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(String countryId) {
        this.countryId = countryId;
    }

    public String getProvinceId() {
        return this.provinceId;
    }
    
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId;
    }

    public String getCityId() {
        return this.cityId;
    }
    
    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    public String getQq() {
        return this.qq;
    }
    
    public void setQq(String qq) {
        this.qq = qq;
    }

    public String getBloodType() {
        return this.bloodType;
    }
    
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getPostalcode() {
        return this.postalcode;
    }
    
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }

    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getFinishSchool() {
        return this.finishSchool;
    }
    
    public void setFinishSchool(String finishSchool) {
        this.finishSchool = finishSchool;
    }

    public String getSpeciality() {
        return this.speciality;
    }
    
    public void setSpeciality(String speciality) {
        this.speciality = speciality;
    }

    public String getWorkId() {
        return this.workId;
    }
    
    public void setWorkId(String workId) {
        this.workId = workId;
    }

    public String getHomepage() {
        return this.homepage;
    }
    
    public void setHomepage(String homepage) {
        this.homepage = homepage;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
   








}