/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package et.bo.screen.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.json.JSONArray;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import et.bo.screen.service.SpecialSurveyService;
import excellence.common.page.PageInfo;
import excellence.common.page.PageTurning;
import excellence.framework.base.action.BaseAction;
import excellence.framework.base.dto.impl.DynaActionFormDTO;

/**
 * MyEclipse Struts Creation date: 03-09-2009 author: 李丹 XDoclet definition:
 * 
 * @struts.action path="/scrspesur" name="sssFormBean" parameter="method"
 *                scope="request" validate="true"
 */
public class ScrspesurAction extends BaseAction { 
	/*
	 * Generated Methods
	 */

	private SpecialSurveyService sss = null;

	public SpecialSurveyService getSss() {
		return sss;
	}

	public void setSss(SpecialSurveyService sss) {
		this.sss = sss;
	}

	/**
	 * 调查信息管理主页 Method execute
	 * 
	 * @param map
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward toSSSMain(ActionMapping map, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// DynaActionFormDTO dto = (DynaActionFormDTO) form;
		System.out.println("进入main");
		return map.findForward("main");
	}

	/**
	 * 调查信息查询页
	 * 
	 * @param map
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward toSSSQuery(ActionMapping map, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//DynaActionFormDTO dto = (DynaActionFormDTO) form;
		return map.findForward("query");
	}

	/**
	 * 调查信息Load页
	 * 
	 * @param map
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward toSSSLoad(ActionMapping map, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaActionFormDTO dto = (DynaActionFormDTO) form;
		String operType = request.getParameter("opertype");
		String id = request.getParameter("id");
		if(operType.equals("insert")){
			request.setAttribute("opertype", "insert");
			return map.findForward("load");
		}
		
		//删 改 查 要先把调查信息读出来显示
		request.setAttribute(map.getName(), sss.getObjById(id));
		if(operType.equals("delete")){
			request.setAttribute("opertype", "delete");
		}
		if(operType.equals("update")){
			request.setAttribute("opertype", "update");
		
		}
		if(operType.equals("detail")){

			request.setAttribute("opertype", "detail");	
		}
		return map.findForward("load");
	}
	/**
	 * 专题调查中的数据信息
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward specialSurvey(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
//		GeneralCaseinfoService gcs = (GeneralCaseinfoService)SpringRunningContainer.getInstance().getBean("GeneralCaseinfoService");
		JSONArray jsonArray = JSONArray.fromObject(sss.screenList());
		outJsonString(response,jsonArray.toString());
		return null;
	}

	/**
	 * 调查信息列表页
	 * 
	 * @param map
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward toSSSList(ActionMapping map, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaActionFormDTO dto = (DynaActionFormDTO) form;

		
		List list = null;
		String pageState = null;
		PageInfo pageInfo = null;
		pageState = (String) request.getParameter("pagestate");
		if (pageState == null) {
			pageInfo = new PageInfo();
		} else {
			PageTurning pageTurning = (PageTurning) request.getSession()
					.getAttribute("sssPageTurning");
			pageInfo = pageTurning.getPage();
			pageInfo.setState(pageState);
			dto = (DynaActionFormDTO) pageInfo.getQl();
		}
		pageInfo.setPageSize(20);
		try {
			System.out.println("进入list 转载list");
			list = sss.getSSSList(dto, pageInfo);
		} catch (Exception e) {
			// TODO: handle exception			
			e.printStackTrace();
		}

		int size = sss.getRecordSize();
		pageInfo.setRowCount(size);
		pageInfo.setQl(dto);
		request.setAttribute("list", list);
		PageTurning pt = new PageTurning(pageInfo, "", map, request);
		request.getSession().setAttribute("sssPageTurning", pt);
		return map.findForward("list");
	}

	/**
	 * 执行 增 删 改操作
	 * 
	 * @param map
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward toSSSOper(ActionMapping map, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaActionFormDTO dto = (DynaActionFormDTO) form;
		String opertype = request.getParameter("opertype");
		request.setAttribute("opertype", opertype);
		if (opertype.equals("insert")) {
			try{
				sss.addSpecialSurvey(dto);
				request.setAttribute("operSign", "true");
			}catch(Exception ex){
			
			}
		}
		if (opertype.equals("update")) {

			if (sss.updateSpecialSurvey(dto)) {
				request.setAttribute("operSign", "true");
				System.out.println("修改成功");
			}
		}
		if (opertype.equals("delete")) {
			try{
				sss.delSpecialSurvey(dto.get("sssId").toString());
				request.setAttribute("operSign", "true");
			}catch(Exception ex){
				request.setAttribute("operSign", null);
				ex.printStackTrace();
			}
		}
		return map.findForward("load");
	}
}