package et.po;

import java.util.Date;


/**
 * CcInfo generated by MyEclipse - Hibernate Tools
 */

public class CcInfo  implements java.io.Serializable {


    // Fields    

     private String id;
     private String clientId;
     private String tagIo;
     private String phonenum;
     private Date curtime;
     private String fileLink;
     private String content;
     private String isValidate;
     private String isExcuteOk;
     private String remark;


    // Constructors

    /** default constructor */
    public CcInfo() {
    }

	/** minimal constructor */
    public CcInfo(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public CcInfo(String id, String clientId, String tagIo, String phonenum, Date curtime, String fileLink, String content, String isValidate, String isExcuteOk, String remark) {
        this.id = id;
        this.clientId = clientId;
        this.tagIo = tagIo;
        this.phonenum = phonenum;
        this.curtime = curtime;
        this.fileLink = fileLink;
        this.content = content;
        this.isValidate = isValidate;
        this.isExcuteOk = isExcuteOk;
        this.remark = remark;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getClientId() {
        return this.clientId;
    }
    
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public String getTagIo() {
        return this.tagIo;
    }
    
    public void setTagIo(String tagIo) {
        this.tagIo = tagIo;
    }

    public String getPhonenum() {
        return this.phonenum;
    }
    
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum;
    }

    public Date getCurtime() {
        return this.curtime;
    }
    
    public void setCurtime(Date curtime) {
        this.curtime = curtime;
    }

    public String getFileLink() {
        return this.fileLink;
    }
    
    public void setFileLink(String fileLink) {
        this.fileLink = fileLink;
    }

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    public String getIsValidate() {
        return this.isValidate;
    }
    
    public void setIsValidate(String isValidate) {
        this.isValidate = isValidate;
    }

    public String getIsExcuteOk() {
        return this.isExcuteOk;
    }
    
    public void setIsExcuteOk(String isExcuteOk) {
        this.isExcuteOk = isExcuteOk;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
   








}