// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jbpm.bpel.tutorial.ticket;

public interface TicketIssuer extends java.rmi.Remote {
    public int createTicket() throws 
         java.rmi.RemoteException;
}
