/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package et.bo.export.action;

import java.io.IOException;
import java.sql.Blob;
import java.sql.SQLException;
import java.util.List;

import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import et.bo.export.service.ExportService;
import excellence.common.page.PageInfo;
import excellence.common.page.PageTurning;
import excellence.framework.base.action.BaseAction;
import excellence.framework.base.dto.IBaseDTO;
import excellence.framework.base.dto.impl.DynaActionFormDTO;

/**
 * MyEclipse Struts Creation date: 07-21-2008  wang lichun
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/export" name="ExportForm" parameter="method"
 *                scope="request" validate="true"
 */
public class ExportAction extends BaseAction {
	/*
	 * Generated Methods
	 */
static Logger log = Logger.getLogger(ExportAction.class.getName());
	
	private ExportService exportService = null;
	
	/**
	 * 根据URL参数执行 toExportMain 方法，返回要forward页面。
	 * 
	 * @param ActionMapping
	 * @param ActionForm
	 * @param HttpServletRequest
	 * @param HttpServletResponse
	 * @return ActionForward 返回main框架页面
	 */
	public ActionForward toExportMain(ActionMapping map, ActionForm form,
            HttpServletRequest request, HttpServletResponse response){
		return map.findForward("main");
		
	}
	/**
	 * 根据URL参数执行 toExportQuery 方法，返回要forward页面。
	 * 
	 * @param ActionMapping
	 * @param ActionForm
	 * @param HttpServletRequest
	 * @param HttpServletResponse
	 * @return ActionForward 返回查询页面
	 */
	public ActionForward toExportQuery(ActionMapping map, ActionForm form,
            HttpServletRequest request, HttpServletResponse response){
		
		return map.findForward("query");
		
	}
	/**
	 * 根据URL参数执行 toExportList 方法，返回要forward页面。
	 * 
	 * @param ActionMapping
	 * @param ActionForm
	 * @param HttpServletRequest
	 * @param HttpServletResponse
	 * @return ActionForward 返回列表页面
	 */
	public ActionForward toExportList(ActionMapping map, ActionForm form,
            HttpServletRequest request, HttpServletResponse response){

		DynaActionFormDTO dto = (DynaActionFormDTO)form;
		String pageState = null;
        PageInfo pageInfo = null;
        pageState = (String)request.getParameter("pagestate");
        if (pageState==null) {
            pageInfo = new PageInfo();
        }else{
            PageTurning pageTurning = (PageTurning)request.getSession().getAttribute("userpageTurning");
            pageInfo = pageTurning.getPage();
            pageInfo.setState(pageState);
            dto = (DynaActionFormDTO)pageInfo.getQl();
        }
        pageInfo.setPageSize(16);
       // 取得list及条数
        List list = exportService.exportQuery(dto,pageInfo);
        int size = exportService.getExportSize();
       
        pageInfo.setRowCount(size);
        pageInfo.setQl(dto);
        request.setAttribute("list",list);
        PageTurning pt = new PageTurning(pageInfo,"",map,request);
        request.getSession().setAttribute("userpageTurning",pt);

		return map.findForward("list");
	}
	
	/**
	 * 根据URL参数执行 toExportList2 方法，返回要forward页面。
	 * 
	 * @param ActionMapping
	 * @param ActionForm
	 * @param HttpServletRequest
	 * @param HttpServletResponse
	 * @return ActionForward 返回列表页面
	 */
	public ActionForward toExportList2(ActionMapping map, ActionForm form,
            HttpServletRequest request, HttpServletResponse response){

        List list = exportService.exportQuery2();
        request.setAttribute("list",list);

		return map.findForward("list2");
	}
	
	/**
	 * 获得专家的照片
	 * 
	 * @param map
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward toExportPhoto(ActionMapping map, ActionForm form,
            HttpServletRequest request, HttpServletResponse response){
		String id=request.getParameter("id");		
		try {
			IBaseDTO dto=exportService.getExportInfo(id);
			Blob blob=(Blob)dto.get("photo");
			int length=(int)blob.length();
			byte   []   byte_array     = blob.getBytes(1, length);
            response.setContentType("image/jpeg");  
            ServletOutputStream   sos   =   response.getOutputStream();  
   
          for(int   i=0;i<byte_array.length;i++) {  
        	  sos.write(byte_array[i]);  
          }  
            sos.close();  
           
		} catch (SQLException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
		return null;
		
	}
	/**
	 * 根据URL参数执行 toExportLoad 方法，返回要forward页面。 并且根据URL参数中type的值来判断所执行的操作:CRUD
	 * 
	 * @param ActionMapping
	 * @param ActionForm
	 * @param HttpServletRequest
	 * @param HttpServletResponse
	 * @return ActionForward 返回列表页面
	 */	
	
	public ActionForward toExportLoad(ActionMapping map, ActionForm form,
            HttpServletRequest request, HttpServletResponse response){

		String type = request.getParameter("type");
        request.setAttribute("opertype",type);
        // 根本type参数判断执行所需要的操作
        if(type.equals("insert")){        	
        	return map.findForward("load");
        }
        
        if(type.equals("detail")){
        	
        	String id = request.getParameter("id");
        	IBaseDTO dto = exportService.getExportInfo(id);
        	request.setAttribute(map.getName(),dto);
        	request.setAttribute("id",id);
        	return map.findForward("load");
        }
        
        if(type.equals("update")){
        	
        	request.setAttribute("opertype", "update");
        	String id = request.getParameter("id");
        	IBaseDTO dto = exportService.getExportInfo(id);
        	request.setAttribute(map.getName(),dto);
        	request.setAttribute("id",id);
        	return map.findForward("load");
        }
        if(type.equals("delete")){
        	
        	String id = request.getParameter("id");
        	IBaseDTO dto = exportService.getExportInfo(id);
        	request.setAttribute(map.getName(), dto);
        	request.setAttribute("id",id);
        	return map.findForward("load");
        }
        
		return map.findForward("load");
	}
	
	/**
	 * 根据URL参数执行 toExportOper 方法，返回要forward页面。 并且根据URL参数中type的值来判断所执行的操作:CRUD.
	 * 
	 * @param map the map
	 * @param form the form
	 * @param request the request
	 * @param response the response
	 * 
	 * @return ActionForward 返回列表页面
	 */
	public ActionForward toExportOper(ActionMapping map, ActionForm form,
            HttpServletRequest request, HttpServletResponse response){

		DynaActionFormDTO dto = (DynaActionFormDTO)form;
		
		String type = request.getParameter("type");
		request.setAttribute("opertype",type);
        
        if (type.equals("insert")) {
			try {	
				exportService.addExport(dto);			
				request.setAttribute("operSign", "sys.common.operSuccess");
				return map.findForward("load");
				
			} catch (RuntimeException e) {
				return map.findForward("error");
			}
		}     
        
        if (type.equals("update")){
			try {
				
				boolean b=exportService.updateExport(dto);
				if(b==true){
					request.setAttribute("operSign", "修改成功");
					return map.findForward("load");
				}else{
					request.setAttribute("operSign","修改失败");
					return map.findForward("load");
				}
				
			} catch (RuntimeException e) {
				log.error("PortCompareAction : update ERROR");
				e.printStackTrace();
				return map.findForward("error");
			}
		}
        
        if (type.equals("delete")){
			try {
				String id=request.getParameter("id");
				// 下面这块是标记删除
				exportService.delExport(id);				
				request.setAttribute("operSign", "删除成功");
				return map.findForward("load");
			} catch (RuntimeException e) {
				request.setAttribute("operSign","删除失败");
				return map.findForward("load");
			}
		}		
        
        
		return map.findForward("load");
	}
	public ExportService getExportService() {
		return exportService;
	}
	public void setExportService(ExportService exportService) {
		this.exportService = exportService;
	}

}

