package et.po;



/**
 * ForumPostContent generated by MyEclipse - Hibernate Tools
 */

public class ForumPostContent  implements java.io.Serializable {


    // Fields    

     private String id;
     private String content;


    // Constructors

    /** default constructor */
    public ForumPostContent() {
    }

	/** minimal constructor */
    public ForumPostContent(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public ForumPostContent(String id, String content) {
        this.id = id;
        this.content = content;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
   








}