package et.po;



/**
 * ForumTopten generated by MyEclipse - Hibernate Tools
 */

public class ForumTopten  implements java.io.Serializable {


    // Fields    

     private String id;
     private String postsId;
     private String postType;
     private String clickCount;
     private String repostCount;
     private String postTitle;
     private String imgUrl;
     private String areaId;
     private String topicId;
     private String type;
     private String remark;


    // Constructors

    /** default constructor */
    public ForumTopten() {
    }

	/** minimal constructor */
    public ForumTopten(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public ForumTopten(String id, String postsId, String postType, String clickCount, String repostCount, String postTitle, String imgUrl, String areaId, String topicId, String type, String remark) {
        this.id = id;
        this.postsId = postsId;
        this.postType = postType;
        this.clickCount = clickCount;
        this.repostCount = repostCount;
        this.postTitle = postTitle;
        this.imgUrl = imgUrl;
        this.areaId = areaId;
        this.topicId = topicId;
        this.type = type;
        this.remark = remark;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getPostsId() {
        return this.postsId;
    }
    
    public void setPostsId(String postsId) {
        this.postsId = postsId;
    }

    public String getPostType() {
        return this.postType;
    }
    
    public void setPostType(String postType) {
        this.postType = postType;
    }

    public String getClickCount() {
        return this.clickCount;
    }
    
    public void setClickCount(String clickCount) {
        this.clickCount = clickCount;
    }

    public String getRepostCount() {
        return this.repostCount;
    }
    
    public void setRepostCount(String repostCount) {
        this.repostCount = repostCount;
    }

    public String getPostTitle() {
        return this.postTitle;
    }
    
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle;
    }

    public String getImgUrl() {
        return this.imgUrl;
    }
    
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public String getAreaId() {
        return this.areaId;
    }
    
    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    public String getTopicId() {
        return this.topicId;
    }
    
    public void setTopicId(String topicId) {
        this.topicId = topicId;
    }

    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
   








}