package et.po;

import java.util.Date;


/**
 * ForumFriend generated by MyEclipse - Hibernate Tools
 */

public class ForumFriend  implements java.io.Serializable {


    // Fields    

     private String id;
     private String userId;
     private String friendId;
     private String friendName;
     private Date addDate;
     private String remark;


    // Constructors

    /** default constructor */
    public ForumFriend() {
    }

	/** minimal constructor */
    public ForumFriend(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public ForumFriend(String id, String userId, String friendId, String friendName, Date addDate, String remark) {
        this.id = id;
        this.userId = userId;
        this.friendId = friendId;
        this.friendName = friendName;
        this.addDate = addDate;
        this.remark = remark;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getFriendId() {
        return this.friendId;
    }
    
    public void setFriendId(String friendId) {
        this.friendId = friendId;
    }

    public String getFriendName() {
        return this.friendName;
    }
    
    public void setFriendName(String friendName) {
        this.friendName = friendName;
    }

    public Date getAddDate() {
        return this.addDate;
    }
    
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
   








}