package et.po;



/**
 * ForumWeapon generated by MyEclipse - Hibernate Tools
 */

public class ForumWeapon  implements java.io.Serializable {


    // Fields    

     private String id;
     private String weaponName;
     private String dictWeapon;
     private String weaponScore;
     private String weaponIcon;
     private String weaponUrl;
     private String delMark;
     private String remark;


    // Constructors

    /** default constructor */
    public ForumWeapon() {
    }

	/** minimal constructor */
    public ForumWeapon(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public ForumWeapon(String id, String weaponName, String dictWeapon, String weaponScore, String weaponIcon, String weaponUrl, String delMark, String remark) {
        this.id = id;
        this.weaponName = weaponName;
        this.dictWeapon = dictWeapon;
        this.weaponScore = weaponScore;
        this.weaponIcon = weaponIcon;
        this.weaponUrl = weaponUrl;
        this.delMark = delMark;
        this.remark = remark;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getWeaponName() {
        return this.weaponName;
    }
    
    public void setWeaponName(String weaponName) {
        this.weaponName = weaponName;
    }

    public String getDictWeapon() {
        return this.dictWeapon;
    }
    
    public void setDictWeapon(String dictWeapon) {
        this.dictWeapon = dictWeapon;
    }

    public String getWeaponScore() {
        return this.weaponScore;
    }
    
    public void setWeaponScore(String weaponScore) {
        this.weaponScore = weaponScore;
    }

    public String getWeaponIcon() {
        return this.weaponIcon;
    }
    
    public void setWeaponIcon(String weaponIcon) {
        this.weaponIcon = weaponIcon;
    }

    public String getWeaponUrl() {
        return this.weaponUrl;
    }
    
    public void setWeaponUrl(String weaponUrl) {
        this.weaponUrl = weaponUrl;
    }

    public String getDelMark() {
        return this.delMark;
    }
    
    public void setDelMark(String delMark) {
        this.delMark = delMark;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
   








}